### ISSUE TITLE
size() not working on Mac Mojave 10.14 and Processing 3.5.3

### ISSUE THREAD

**Issue by ElPepe101** [processing/processing#5791] opened 2019-02-11 21:30 UTC
## Description
size() not working. It displays to the window size but not at fullscreen.

Seems related to #3381  because when I disabled "Display have separated spaces" option and logged out, it worked as expected.

This already happened with three different macs.

## Expected Behavior
size() function should set Processing canvas size.

## Current Behavior
It throws an error into console:
```shell
Could not check the status of “Displays have separate spaces.”
Received message '2019-02-11 11:28:29.588 defaults[994:57256] The domain/default pair of (com.apple.spaces, spans-displays) does not exist' and result code 1.
```

## Steps to Reproduce
Using settings or setup gives the same result:
```processing
void settings() {
  size(200, 300);
}

// or

void setup() {
  size(200, 300);
}
```

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: MacOS 10.14

## Possible Causes / Solutions
Dunno.

Meanwhile, disable "Display have separated spaces" option at System Preferences > Mission Control and log out.

**Comment by DataNeel** [comment] 2019-02-13 11:11
I'm having a similar issue. I'm on os x 10.14.3. size() doesn't work, and my sketch dimensions are always the resolution of my desktop. I don't believe I get an error, though.

**Comment by benfry** [comment] 2019-02-15 19:34
Working fine here (3.5.x has all been built/debugged on multiple Mojave machines). For the machine that's giving you trouble, has it only ever had Mojave installed on it (i.e. it wasn't an upgrade from 10.3 or earlier)? 

<img width="964" alt="screen shot 2019-02-15 at 2 32 13 pm" src="https://user-images.githubusercontent.com/1623101/52879939-9a63d000-312e-11e9-863d-17c13ddb9bc2.png">

**Comment by benfry** [comment] 2019-02-15 19:36
Are you leaving something out of your example? The only time `Could not check the status of “Displays have separate spaces.”` is shown is when using `fullScreen(SPAN)` on macOS.

**Comment by ElPepe101** [comment] 2019-02-15 23:34
@benfry May be related to using a mirrored screen. I'll try tonight to recreate the issue and send you more info, right now I don't have my laptop around.

**Comment by DataNeel** [comment] 2019-02-16 11:45
I have a single monitor, and my computer was upgraded to mojave from an earlier version of mac os. Here's a video of me running a simple script that only has the size command. The script uses settings(), but the issue also happens with setup().

https://youtu.be/9HkRFqUhIuE

**Comment by Tapestes** [comment] 2019-03-05 19:03
+1.  On Mojave 10.14.3.  Brand new macbook, that's only ever had Mojave installed.  Copied Ben's one line sketch of "size(400,400);".  Sketch is sized to desktop resolution (but is not in full screen mode).  Doesn't matter if I'm running to a mirrored display or not (I've disconnected the mirrored display to verify). 

 One difference from the original poster... if I disable "Display have separated spaces", the error message in the console goes away, but the result is the same. Probably unrelated, but I'll note the only way I could get v3.x to run on my machine was by installing the Java runtime.

**Comment by Tapestes** [comment] 2019-03-05 19:44
One last comment.  I was able to get size() working by adding Processing to System Preferences -> Security & Privacy -> Accessibility.   I tried this because Magnet (a window management tool for Mac) requires this same process.  Oddly, after adding Processing to Accessibility and verifying size() works, removing it didn't break size().

**Comment by sulea054** [comment] 2019-03-06 04:02
I am having the same issue with my Mac and Processing - sketch is displaying full screen instead of the dimension I give it in size()

Tried adding Processing to my Mac's Accessibility, restarting the app, still the same error.

**Comment by Tapestes** [comment] 2019-03-06 16:22
One other thing you might try, in the same section of Security & Privacy as Accessibility is adding Processing to Full Disk Access.  It’s possible I did this when I got it working...  unfortunately I wasn’t particularly systematic and was trying everything that came to mind.

**Comment by sulea054** [comment] 2019-03-07 01:14
Thanks for the reply.

Not sure how to get to Full Disk access... here is a screenshot of what I see.... and note that advance preferences do not have that option either. 

<img width="659" alt="screen shot 2019-03-06 at 8 11 32 pm" src="https://user-images.githubusercontent.com/8666578/53924973-39a02700-404c-11e9-9cf8-852380a8fb06.png">


I also turned off all Spaces preferences in my Mission Control panel then restarted my Mac. Still have the full screen issue.

**Comment by nielmistry** [comment] 2019-03-26 17:14
With Processing 3.5.3 and MacOS 10.14.4 on a 2018 MacMini, the following works as expected: 

``` java
void setup() {
  size(200, 300);
}
```

**Comment by kr0y1247** [comment] 2019-04-18 22:40
Similar issue with the console error/s:

NSWindow(NSWindow_Theme...etc. etc.

`
void setup()  { 
size(640, 360, P3D);  
} 
 `

Sketch is displayed as correct size but it's related to P3D. Omit P3D and no error. Issue is on both MacMini (2014) and a MBP (2013) running latest Mojave 10.14.3. Also tested on Processing 3.4 with same results. 

Tried suggestions above however they didn't solve this unfortunately. Further advice or suggestions?

**Comment by benrubin** [comment] 2019-06-13 18:25
I'm also running Mac OS Mojave (10.14.5) and Processing 3.5.3. 

In Java mode, size(P2D) generally seems to be working for me, although [I'm seeing weird console output ](https://github.com/processing/processing/issues/5880 )similar to @Tapestes However, [in Python mode, P2D is causing crashes](https://github.com/processing/processing/issues/5879). Anyone else have similar experiences?

**Comment by crystalfiction** [comment] 2019-07-08 21:18
I have had this issue for months now and no clear solution or direction in which to search for the solution. There are only a bunch of references to other threads that also have no solution. Is this being solved? Or are we just being ignored?

All I have to do to throw the error is set up a window size with P3D on Mac Mojave and I get the error every time. It's annoying. It only happens with P3D, not P2D or regular rendering. How do we fix this?...

**Comment by minakimm** [comment] 2019-07-10 01:23
I'm also having this issue on El Capitan where size() doesn't work and the sketch is even larger than the full-screen size. How do we fix this...?

**Comment by contractorwolf** [comment] 2019-08-10 04:04
I am running a Macbook Pro with Mojavi v10.14.6 and using processing for the first time. Sketches were always displaying fullscreen no matter how I set the size(). Found that I was running Processing v3.5.3.  Downloaded and ran Processing v3.4 (overwrote 3.5.3) and now size() works properly after being set in setup(). I think it is v3.5.3 that may have an issue for macs, my guess.  Anyways v3.4 fixed the issue for me.

**Comment by xgandibleux** [comment] 2019-12-27 16:35
Concerning : 
`void setup() { size(10,10,P3D); }`

On **MacBook (2016)**, I tried processing **v3.5.3**, **v3.4** and **v3.2** on **Mojave v10.14.6**, nothing better. Same with **Catalina v10.15.2**. and processing **v3.5.3**.

Always the same error:

2019-12-27 17:25:03.285 java[98680:16302000] pid(98680)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2019-12-27 17:25:03.810 java[98680:16302000] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff31967607 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 378
	1   AppKit                              0x00007fff319649f7 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1479
	2   AppKit                              0x00007fff3196442a -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	3   libnativewindow_macosx.jnilib       0x000000011dc113fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	4   ???                                 0x00000001091d6a88 0x0 + 4447890056
)

Any idea to fix it or step over?
No problem with **HighSierra v10.13.6** with a MacBook Pro (2015).

**Comment by hajdebliem** [comment] 2020-01-02 21:59
This is not a professional standpoint; i have just an elaborate guess to share. Something is messing with Spaces and Display Management in general. 
My wife had the duet display software running in the background to use an iPad as a second monitor! 

As soon as i turned it off the error was gone.

**Comment by benfry** [comment] 2020-01-17 22:08
Folks, I can't reproduce this bug on any machines here. 

Also, I'm not even sure where to start. The original post said `size()` wasn't working, but as evidence, included an error message that only shows up with `fullScreen()`, not with the code that was included.

The follow-up posts are about OpenGL errors on startup, which are totally unrelated. Is there also a problem with OpenGL? 

I've tried Mojave and Catalina machines. With and without “Displays Have Separate Spaces” checked. 

I'm going to close this version of the issue, but if you run into this and can replicate it, please file a new issue with a clear explanation of what's going on. There's simply nothing I can do with this thread… I'd really like to fix it, however, so help me out by tracking down things that might be going on: 

* Maybe try with a clean user account
* Try with a brand new OS install from an external drive
* Report whether you're using multiple displays, or any other display extending technology
* What type of Mac are you using? 
* Is it on the latest version of Mojave or Catalina?
* When filing, don't mix `size(200, 200)` with the `P2D` and `P3D` or `fullScreen()` issues… they have nothing to do with one another
* Do you have any other display technology installed?
* Have you tried with an empty sketchbook? Maybe there's a Library or Tool that's breaking something

**Closed by benfry** 2020-01-17 22:08 UTC

**Comment by benfry** [comment] 2020-01-19 01:09
Additional things to try, for anyone running into this: 

* Replace the core.jar file in Procesing 3.5.4 with the one from Processing 3.4, and see if that fixes the issue. If so, we'll know it's a regression in the `PApplet` code, versus an issue happening somewhere inside Java. 

* Also, try using a [Processing 4](https://github.com/processing/processing4) alpha release (once it's available) to see if it has the same problem.

…and if you find anything, please file a new issue, as detailed as possible.
