### ISSUE TITLE
3.3/Windows 10 64-bit fails on first run with stack trace

### ISSUE THREAD

**Issue by jdf** [processing/processing#4996] opened 2017-04-09 02:07 UTC
![screenshot 1](https://cloud.githubusercontent.com/assets/55948/24834021/9a677fcc-1ca7-11e7-8ffc-971fe9c6e078.png)

Newly created user on Windows 10 64-bit machine.

User name is Chinese--may be relevant?

**Comment by jdf** [comment] 2017-04-09 02:11
Every attempt gives this dialog.

**Comment by gohai** [comment] 2017-04-09 15:18
@jdf 32-bit version of Processing by chance?

**Comment by jdf** [comment] 2017-04-09 17:16
No.

**Comment by gohai** [comment] 2017-04-09 19:23
This is the same issue as in #4929.

@jdf If you have a chance to triage, I'd test the following:

* whether running Processing from a path like `C:\Processing\` makes it work
* whether Processing [3.0.2](https://github.com/processing/processing/releases/tag/processing-0248-3.0.2) works (release 3.1 included and updated JNA)
* or whether it's indeed the username (but my guess is on the install path, since I can't see how the latter is involved with class loading)

**Comment by benfry** [comment] 2017-04-23 20:48
Closing this as a duplicate of https://github.com/processing/processing/issues/4929. But @gohai's comments on how to debug are all relevant.

**Closed by benfry** 2017-04-23 20:48 UTC
