### ISSUE TITLE
Switching Mode causes an exception (3.0a8/a9)

### ISSUE THREAD

**Issue by ciaron** [processing/processing#3362] opened 2015-06-08 16:01 UTC
When switching mode from Java to Python, Javascript or Android mode, an exception occurs and Processing quits. The first line of the exception reads:

```
java.lang.NoSuchMethodError: processing.app.EditorToolbar.(Lprocessing/app/Editor;Lprocessing/app/Base;)
```

Python mode:
![python-mode-error](https://cloud.githubusercontent.com/assets/214666/8039170/3940a408-0e08-11e5-85b7-34c46841c1dc.png)

Javascript mode:
![javascript-mode-error](https://cloud.githubusercontent.com/assets/214666/8039174/3f2b436e-0e08-11e5-8d52-2f641dc64b15.png)

Android mode:
![android-mode-error](https://cloud.githubusercontent.com/assets/214666/8039177/4540a5c8-0e08-11e5-96cd-98b3b0859be2.png)

This is a regression from 3.0a5.

Screenshots of the errors are attached.

**Comment by aengelke** [comment] 2015-06-08 18:24
It comes from the major changes to the PDE... these modes are not updated (yet).

**Comment by benfry** [comment] 2015-06-08 18:56
Duplicate of https://github.com/processing/processing/issues/3080

**Closed by benfry** 2015-06-08 18:56 UTC
