### ISSUE TITLE
Keyboard Shortcut for debugging 'step' and 'step into' inserts a blank line into the code

### ISSUE THREAD

**Issue by bfishman** [processing/processing#4184] opened 2015-12-04 02:09 UTC
When the keyboard shortcut for 'step' or 'step into' is used, it inserts a blank line (i.e. an '/n') wherever the (typing) cursor is located when the keypress occurred.

Reproducible example:

```java
void setup(){
    size(400,600);
}

void draw(){
    background(0);
    function();
}

void function(){
    fill(0,0,255);
    ellipse(width/2, height/2, 40,40);
}
```

Now add a breakpoint to line 7, where function() is called.

Now run, and once the debugger has paused execution, "step-into" with Ctrl+Shift+J.

Below are screenshots of before and after. Ctrl+Shift+J was pressed 3 times. This also occurs with just Ctrl+J for 'step'. (although the line break pattern differs). This does not occur when the 'step' button is used, nor when either of the menu options are used.

Before:
![image](https://cloud.githubusercontent.com/assets/3529531/11580041/dc492bd8-99f0-11e5-937e-ba3c24b0e381.png)

After:
![image](https://cloud.githubusercontent.com/assets/3529531/11580060/ee55569e-99f0-11e5-9f6b-3b9b7f7e870c.png)

**Comment by nbourre** [comment] 2015-12-15 01:08
I do have the exact same problem. I'm under Windows 10 Pro with a non-US keyboard configuration.

**Comment by iamutkarshtiwari** [comment] 2016-01-21 04:29
https://github.com/processing/processing/issues/3830

**Comment by benfry** [comment] 2016-02-13 21:35
Closing; duplicate of https://github.com/processing/processing/issues/3830

**Closed by benfry** 2016-02-13 21:35 UTC
