### ISSUE TITLE
When I use pixelDensity(2), set()'s display is strange

### ISSUE THREAD

**Issue by hellowewe** [processing/processing#5010] opened 2017-04-17 13:56 UTC
I'm going to use two `for()` to draw a gradient circular

My computer is a retina screen, when I used the `pixelDensity(2)`, and then `set()` to draw a circle. The results can only be displayed in the upper left corner of the 1/4 space. I also use `point()` to draw the same circle, can normally display, but each pixel seems to have a white pixel. The gradient looks pale.

How should I normally show?
Thanks in advance - any help or suggestions would be appreciated.

```
int interV = 0;
float distance1;
float distance2;
color from = color(255, 58, 34);
color to = color(178, 68, 152);

void setup() {
  size(500, 500);
  pixelDensity(2);
}

void draw() {
  background(255);
  fill(from);
  for (int i=0; i<=500; i++) {
    for (int j=0; j<=500; j++) {
      distance1=dist(i, j, 250, 250);
      if (distance1<=250) {
        distance2=dist(i, j, i, 500);
        interV = int(map(distance2, 0, 500, 0, 100));
        //println(interV);
        color inter = lerpColor(from, to, interV*0.01);
        stroke(inter);
        point(i,j);
        set(i, j, inter);
      }
    }
  }
}

```

**Comment by benfry** [comment] 2017-04-21 21:27
That's the expected behavior… `pixelDensity(2)` means that all the pixel-based operations (get, set, pixels[], loadPixels, updatePixels, etc) will be operating in 2x space. Otherwise we'd just make it the default if you have a retina display—the idea behind pixelDensity() is that you're saying "I know I'm moving to double pixel mode." 

But… it looks like the reference isn't clear enough on that point. Sorry about that.

**Closed by benfry** 2017-04-21 21:27 UTC
