### ISSUE TITLE
"Your sketch has been modified..." appearing on OS X when sketches are stored on FAT32 volumes

### ISSUE THREAD

**Issue by rapatski** [processing/processing#3387] opened 2015-06-15 12:36 UTC
With any sketch that stored on my FAT32 partition, Processing (3.0a10) prompts the "Your sketch has been modified externally..." dialog whenever the sketch's IDE window gains focus.

![screen shot 2015-06-15 at 13 32 03](https://cloud.githubusercontent.com/assets/1821058/8159941/6a9a9c74-1363-11e5-8f9a-443f2d560f8c.png)

**Comment by benfry** [comment] 2015-06-15 12:45
If someone is interested in looking into this, the issue is that the time reported by the file system is out of sync, since there are resolution differences between FAT32 and HFS+ and the rest. Need to take a look at the time deltas to see if it's something specific that we can pinpoint (the way that OS X-specific 1000L check works in the source) or if we just need to expand the time window in general.

**Comment by gerbyzation** [comment] 2015-07-12 16:41
this is happening to me as well but I'm storing my sketches on my main drive in my Macbook

**Comment by benfry** [comment] 2015-07-13 14:47
@gerbyzation That's a different issue, and likely already fixed in the current source.

**Comment by gerbyzation** [comment] 2015-07-13 16:01
@benfry oh, sorry!

**Comment by benfry** [comment] 2015-07-14 11:04
@gerbyzation But if you still see the problem in the next release, please file a new issue and let us know!

**Comment by benfry** [comment] 2015-09-15 21:20
Can you try this pre-release and report back the results? 
http://download.processing.org/processing-150915b-macosx.zip

**Comment by benfry** [comment] 2015-09-20 19:35
Fingers crossed that we have this fixed for 3.0 beta 7.

**Comment by benfry** [comment] 2015-09-29 18:38
Appears to still be broken according to #3898.

**Comment by rapatski** [comment] 2015-09-30 13:35
Indeed, apologies Ben- downloaded the release and get the same dialog whilst the processing console prints "<sketch_name> file count now 10 instead of 5” that repeats while clicking No. Yes does the same, but plus a java exception I can’t read because of the dialog. Is the console written to disk somewhere?

**Comment by benfry** [comment] 2015-09-30 13:44
Yep, we've found the problem and are working on a fix. Stay tuned...

**Closed** 2015-09-30 15:11 UTC
Labels: help, macosx
