### ISSUE TITLE
Output window cannot be set as non-resizable with the P2D or P3D renderers

### ISSUE THREAD

**Issue by daimonWolf** [processing/processing#3952] opened 2015-10-02 18:20 UTC
Resize the window does not work without P2D or P3D inside size(), for example size(100,100) no work reisze from the cursor on the window, size (100, 100, P3D (or P2D)) work fine

**Comment by REAS** [comment] 2015-10-02 18:45
I think the issue is reversed. You shouldn't be able to resize a window unless `surface.setResizable(true);` is defined. @codeanticode will have a better sense of it.

**Comment by codeanticode** [comment] 2015-10-02 18:53
Yes, that's correct. Right now the default renderer initializes the window as non-resizable, and one can set it as resizable with the ```surface.setResizable(true);`` call. Due to a [bug](https://jogamp.org/bugzilla/show_bug.cgi?id=1188) in the version of JOGL bundled with Processing 3, windows cannot be set as non-resizable with the P2D or P3D renderers. This will fixed as soon as we bundle the upcoming version of JOGL in Processing 3.0.x

**Comment by codeanticode** [comment] 2015-10-10 10:50
Fixed with https://github.com/processing/processing/commit/d357d301f3a952a7dcfae13e7b50ddb0673dfd91

**Closed by codeanticode** 2015-10-10 10:50 UTC
Labels: opengl
