### ISSUE TITLE
Command-Shift-N sometimes stops working

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#188] opened 2013-02-10 16:05 UTC
_Original author: b...@processing.org (June 07, 2010 01:11:18)_

This bug automatically added from:
http://dev.processing.org/bugs/show_bug.cgi?id=1081

Comment from g00dnight, 2008-11-29 11:55

When I try to press Shift-Command-N in Processing 1.0 on my Mac OS X 10.4.11 new tab is 
not creating.

_Original issue: http://code.google.com/p/processing/issues/detail?id=149_

**Comment by JakubValtar** [comment] 2015-08-11 14:52
Can't reproduce. Is this still an issue?

**Comment by benfry** [comment] 2015-08-11 16:24
I think it was fixed in the past few months and never closed, undermining my claims otherwise from a few months earlier.

**Closed by benfry** 2015-08-11 16:24 UTC
Labels: help, imported, pde, revised
