### ISSUE TITLE
Conway shader sketch that runs fine with 3.0b7, is failing with 3.0 release

### ISSUE THREAD

**Issue by monkstone** [processing/processing#3947] opened 2015-10-01 19:40 UTC
On my 64 bit linux box (mint essentially ubuntu) I get following:-

`NullPointerException` in red zone 

and pg.endDraw(); is highlighted in yellow in the processing ide

**Comment by codeanticode** [comment] 2015-10-02 04:12
This is a regression due to https://github.com/processing/processing/commit/707703260c5ce74fcd27c8af24631fc015912dfa, fixed with https://github.com/processing/processing/commit/bfc277d96386e10f01ddce6b2f53af83234feca0. Thanks for the report!

**Closed** 2015-10-02 04:11 UTC
Labels: opengl
