### ISSUE TITLE
Search and replace infinite loop

### ISSUE THREAD

**Issue by Idrias** [processing/processing#4270] opened 2016-02-04 18:09 UTC
When using the search and replace feature of the editor, clicking "replace all", the editor does not respond anymore. This happens when the replacement term contains the term we search for itself.

For example:
Search for: bcd
Replace with: abcd

-> Replace all

Will end up crashing Processing because it always finds the term "bcd" and puts another "a" in front of it (like "aaaaaaaaaaaaaaaaaaabcd").

**Comment by Akarshit** [comment] 2016-02-04 19:45
@Idrias I was testing this(with the above example) but am unable to reproduce the issue. I when select `Replace All` `bcd` gets replaced with `abcd` only once and the editor is fully responsive. Could you please post a snippet of the code that is causing the error.

**Comment by Idrias** [comment] 2016-02-04 19:57
@Akarshit I think my description did not accurately meet the problem, because it only seems to happen when you check the "all tabs" box, no matter if you actually have more than one tab open or not.
It freezes for me once it finds "bcd"  AND "all tabs" is checked"

![screenshot 10](https://cloud.githubusercontent.com/assets/13923216/12827805/c0d7b7ee-cb81-11e5-9833-390341e79411.png)

**Comment by Akarshit** [comment] 2016-02-04 21:07
Thanks @Idrias 
This has been fixed in #4271

**Comment by JobLeonard** [comment] 2016-02-05 15:10
I could swear I remember this being an issue in Processing 2 and it having been fixed at some point. Did it somehow sneak back in?

**Comment by benfry** [comment] 2016-02-14 00:09
Fix incorporated for 3.0.2.

**Closed by benfry** 2016-02-14 00:09 UTC
