### ISSUE TITLE
Crashing error on launch with macOS Big Sur Beta

### ISSUE THREAD

**Issue by Shpigford** [processing/processing#6062] opened 2020-06-30 20:32 UTC
## Description

On macOS Big Sur, Processing doesn't work at all. It immediately throws an error and then closes the entire app after clicking "OK".

_(Sorry I can't put the actual text of the error here...the error dialogue won't let me copy/paste.)_

<img width="779" alt="CleanShot 2020-06-30 at 15 26 16@2x" src="https://user-images.githubusercontent.com/35243/86173939-618b8780-bae6-11ea-8a3c-a72950466d26.png">

This isn't terribly surprising, given Big Sur is beta software, but could potentially be an issue once Big Sur is out of beta.

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: macOS Big Sur 11.0 Beta (20A4299v)

**Comment by benfry** [comment] 2020-08-20 23:47
Looks like a duplicate of https://github.com/processing/processing/issues/6034

**Closed by benfry** 2020-08-20 23:47 UTC
