### ISSUE TITLE
In P2D/P3D the background is cleared to black on each frame

### ISSUE THREAD

**Issue by hamoid** [processing/processing#3559] opened 2015-08-09 11:27 UTC
void setup() {
      size(600, 600, P2D);
    }
    void draw() {
      // no background() call here, but background is cleared to black anyway.
      float r = height * 0.4;
      float a = frameCount * 0.1;
      ellipse(width/2 + r*cos(a), height/2 + r*sin(a), 50, 50);
    }

I'm assuming that for consistency, it should behave the same way in JAVA2D and P2D/P3D.

// ArchLinux 64bit, Processing 3 beta 1, i3 window manager, Intel HD 4600

**Comment by benfry** [comment] 2015-08-09 11:41
This is working fine here, I'm guessing it depends on your graphics drivers and chipset. 

<img width="712" alt="screen shot 2015-08-09 at 7 39 54 am" src="https://cloud.githubusercontent.com/assets/1623101/9154662/e2f2fa96-3e69-11e5-8032-1744cdfeabd8.png">

@JakubValtar is this a regression from the flickering patch?

**Comment by JakubValtar** [comment] 2015-08-09 11:53
Works fine here on Win 8.1, Intel HD 4600. Will investigate.

**Comment by JakubValtar** [comment] 2015-08-09 12:20
@hamoid Btw, do you have any other window manager to try? It seems that there are lots of problems with i3.

**Comment by codeanticode** [comment] 2015-08-13 17:41
@hamoid could you try your code with a processing build after commit https://github.com/processing/processing/commit/eeb9deccb2601793fd3e19b015f956d9da14954f and let us know if the issue is still present?

**Comment by hamoid** [comment] 2015-08-13 19:04
It currently complains that EditorException and ExamplesFrame are
unknown. I did pull and clean. Are some classes missing maybe?

**Comment by benfry** [comment] 2015-08-13 19:06
That sounds like something didn't complete when you did the pull. I just tried a fresh clone and it's working fine: 
```
% git clone --depth=1 https://github.com/processing/processing.git
Cloning into 'processing'...
remote: Counting objects: 1172, done.
remote: Compressing objects: 100% (743/743), done.
remote: Total 1172 (delta 398), reused 787 (delta 323), pack-reused 0
Receiving objects: 100% (1172/1172), 45.75 MiB | 9.16 MiB/s, done.
Resolving deltas: 100% (398/398), done.
Checking connectivity... done.
fry@fivek:~/Desktop
% cd processing/
fry@fivek:~/Desktop/processing
% cd build/
fry@fivek:~/Desktop/processing/build
% ant run
Buildfile: /Users/fry/Desktop/processing/build/build.xml

run:

revision-check:

macosx-check-os:

subprojects-build:

methods-check:

methods-build:

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/core/methods/bin
    [javac] Compiling 1 source file to /Users/fry/Desktop/processing/core/methods/bin

dist:
      [jar] Building jar: /Users/fry/Desktop/processing/core/methods/methods.jar

compile:
  [methods] No changes to PApplet API.
    [mkdir] Created dir: /Users/fry/Desktop/processing/core/bin
    [javac] Compiling 52 source files to /Users/fry/Desktop/processing/core/bin
     [copy] Copying 1 file to /Users/fry/Desktop/processing/core/bin/japplemenubar
     [copy] Copying 23 files to /Users/fry/Desktop/processing/core/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/core/library/core.jar

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/app/bin
    [javac] Compiling 92 source files to /Users/fry/Desktop/processing/app/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/app/pde.jar

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/java/libraries/dxf/bin
    [javac] Compiling 1 source file to /Users/fry/Desktop/processing/java/libraries/dxf/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/java/libraries/dxf/library/dxf.jar

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/java/libraries/net/bin
    [javac] Compiling 2 source files to /Users/fry/Desktop/processing/java/libraries/net/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/java/libraries/net/library/net.jar

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/java/libraries/pdf/bin
    [javac] Compiling 1 source file to /Users/fry/Desktop/processing/java/libraries/pdf/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/java/libraries/pdf/library/pdf.jar

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/java/libraries/serial/bin
    [javac] Compiling 1 source file to /Users/fry/Desktop/processing/java/libraries/serial/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/java/libraries/serial/library/serial.jar

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/java/libraries/svg/bin
    [javac] Compiling 2 source files to /Users/fry/Desktop/processing/java/libraries/svg/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/java/libraries/svg/library/svg.jar

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/build/shared/tools/MovieMaker/bin
    [javac] Compiling 14 source files to /Users/fry/Desktop/processing/build/shared/tools/MovieMaker/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/build/shared/tools/MovieMaker/tool/MovieMaker.jar
    [mkdir] Created dir: /Users/fry/Desktop/processing/java/generated/processing/mode/java/preproc

preproc:
    [antlr] ANTLR Parser Generator   Version 2.7.7 (2006-11-01)   1989-2005
    [antlr] /Users/fry/Desktop/processing/java/src/processing/mode/java/preproc/java15.g:941: warning:Syntactic predicate superfluous for single alternative
    [antlr] /Users/fry/Desktop/processing/java/src/processing/mode/java/preproc/java15.g:1397: warning:empty alternative makes no sense in (...)* or (...)+
    [antlr] ANTLR Parser Generator   Version 2.7.7 (2006-11-01)   1989-2005
    [antlr] /Users/fry/Desktop/processing/java/generated/processing/mode/java/preproc/expandedpde.g:1155: warning:empty alternative makes no sense in (...)* or (...)+
    [antlr] /Users/fry/Desktop/processing/java/generated/processing/mode/java/preproc/expandedpde.g:804: warning:Syntactic predicate superfluous for single alternative

compile:
    [mkdir] Created dir: /Users/fry/Desktop/processing/java/bin
    [javac] Compiling 65 source files to /Users/fry/Desktop/processing/java/bin

build:
      [jar] Building jar: /Users/fry/Desktop/processing/java/mode/JavaMode.jar

macosx-build:
    [mkdir] Created dir: /Users/fry/Desktop/processing/build/macosx/work
[bundleapp] Creating app bundle: Processing
   [delete] Deleting: /Users/fry/Desktop/processing/build/macosx/work/Processing.app/Contents/PlugIns/jdk1.8.0_51.jdk/Contents/MacOS/libjli.dylib
     [copy] Copying 111 files to /Users/fry/Desktop/processing/build/macosx/work/Processing.app/Contents/Java
     [copy] Copying 11 files to /Users/fry/Desktop/processing/build/macosx/work/Processing.app/Contents/PlugIns/jdk1.8.0_51.jdk/Contents/Home/jre/lib/fonts

version-clear:

version-write:

assemble:
     [copy] Copying 66 files to /Users/fry/Desktop/processing/build/macosx/work/Processing.app/Contents/Java/tools
     [copy] Copying 445 files to /Users/fry/Desktop/processing/build/macosx/work/Processing.app/Contents/Java/modes/java
     [copy] Warning: /Users/fry/Desktop/processing-docs/content/examples does not exist.
      [get] Getting: http://download.processing.org/reference.zip
      [get] To: /Users/fry/Desktop/processing/java/reference.zip
    [unzip] Expanding: /Users/fry/Desktop/processing/java/reference.zip into /Users/fry/Desktop/processing/build/macosx/work/Processing.app/Contents/Java/modes/java
     [move] Moving 1 file to /Users/fry/Desktop/processing/build/macosx/work/Processing.app/Contents/Java/modes/java/application/launch4j/bin
     [move] Moving 1 file to /Users/fry/Desktop/processing/build/macosx/work/Processing.app/Contents/Java/modes/java/application/launch4j/bin

macosx-run:

BUILD SUCCESSFUL
Total time: 9 seconds
```

**Comment by hamoid** [comment] 2015-08-15 11:14
Latest version from source works as expected :+1: Background not cleared to black on draw.

**Comment by codeanticode** [comment] 2015-08-15 12:50
so things work after this https://github.com/processing/processing/commit/2082d77d6598c3348644e68171180c192c471090?

**Comment by hamoid** [comment] 2015-08-15 13:22
@codeanticode  I pulled the latest changes, compiled, and then it worked as expected. I did not download that specific revision. Is that good enough?

**Comment by JakubValtar** [comment] 2015-08-15 19:36
@codeanticode I think this was caused & solved by save to pixels hack. We are not going to use it so maybe we can close this since things are back to normal.

@hamoid Thanks for your help!

**Comment by codeanticode** [comment] 2015-09-04 05:30
@hamoid @JakubValtar could you check if this commit https://github.com/processing/processing/commit/5d464d8ce8c647711915ca9e762ef286cae1e667 fixes the background issues, without introducing any side effects?

**Comment by hamoid** [comment] 2015-09-04 08:07
@codeanticode I tried and it worked as expected (background not cleared
to black automatically).

**Comment by benfry** [comment] 2015-09-04 13:30
@codeanticode is this clear to close?

**Comment by JakubValtar** [comment] 2015-09-04 20:06
It is not cleared to black and for the record I never had this issue. Only thing I noticed is that when I resize the window it looks like the texture coords are clamped to previous values. When I call `background()`everything is fine. I think there is a bug when you copy previous frame for accumulation purposes.

![clamp](https://cloud.githubusercontent.com/assets/3177098/9693477/cc01c302-531e-11e5-8233-621514fb880e.png)

**Comment by codeanticode** [comment] 2015-09-08 03:53
fixed with https://github.com/processing/processing/commit/3b8768165645a82ba87fcb15ab569f37f9d6efcc, https://github.com/processing/processing/commit/abe7b52e1ec33c5d86ed5fbf64980ee7f3bc9703 and https://github.com/processing/processing/commit/ea13eda65db426d0f6d47c695825667752627192

**Closed by codeanticode** 2015-09-08 03:53 UTC
Labels: opengl
