### ISSUE TITLE
Apparently new issue - failure to launch

### ISSUE THREAD

**Issue by Aerodrew** [processing/processing#4517] opened 2016-06-01 05:22 UTC
This error message appeared after initial download and extraction of files.

Processing 3.1.1
Windows 7 Enterprise
Intel Core i5-2520M  2,5GHz
4.00 GB RAM
64 bit
![processing_error message 01062016](https://cloud.githubusercontent.com/assets/19680437/15698939/935c2498-280c-11e6-99b1-2014611f1cc2.jpg)

**Comment by benfry** [comment] 2016-06-02 20:26
Duplicate of https://github.com/processing/processing/issues/4476

**Closed by benfry** 2016-06-02 20:26 UTC

**Comment by Aerodrew** [comment] 2016-06-06 01:02
Hi Ben,

Thank you. I read #4476 and realised, on the basis of the other thread,
that Processing was being treated by my system as a "network file". I just
reinstalled in "Programs".

Cheers,
Andrew

On 3 June 2016 at 06:27, Ben Fry <notifications@github.com> wrote:

> Closed #4517 <https://github.com/processing/processing/issues/4517>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/processing/processing/issues/4517#event-680347001>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASxMtaLWMrOO1znXHgingGXLBlPKrdPIks5qHzyWgaJpZM4IrMgc>
> .
>



-- 
Dr Andrew Neil Davies
Lecturer in Physiology
Monash University Peninsula Campus
School of Biomedical Sciences
McMahons Road
Frankston, 3199
Australia

Ph +61 3 9904 4821
M   0435931030.
