### ISSUE TITLE
I can't Open Processing due to  java.lang.exceptionininitializererror !!

### ISSUE THREAD

**Issue by SamerSaber** [processing/processing#3273] opened 2015-05-12 08:39 UTC
Hi 

I am new to processing and I need it urgently, I downloaded 3 versions of Processing and when I open it I find this error.

Any Ideas how can I fix it??

Thanks in advance :)
![capture](https://cloud.githubusercontent.com/assets/7757005/7583075/2db65388-f893-11e4-91ca-4cc2dfb31f60.PNG)

**Comment by benfry** [comment] 2015-05-12 11:34
Try using 3.0a5, which shouldn't give you that message—it should tell you which Library, Mode, or Tool you have installed that is causing that problem and move on.

That error means that something is very wrong with one of the libraries, modes, or tools in your sketchbook. Move the libraries, modes, and tools folders to another location and try re-running Processing. Then add the contents back one by one to figure out which is causing the problem. Then let us know what library (most likely) or mode it is.

**Comment by benfry** [comment] 2015-06-08 19:56
Closing as duplicate of https://github.com/processing/processing/issues/3080

**Closed by benfry** 2015-06-08 19:56 UTC
