### ISSUE TITLE
better error message when creating class w/ same name as the sketch

### ISSUE THREAD

**Issue by ekeneijeoma** [processing/processing#4261] opened 2016-02-01 21:42 UTC
I hadn't used Processing in a while and forgot how it puts all your code into a class with the same name as your sketch... So when I saw this error "The nested type classname cannot hide an enclosing type" it took me a few to figure out what it meant. I think there should be a better error message for this.

**Comment by Akarshit** [comment] 2016-02-02 09:04
Thanks for reporting.
This issue is a duplicate of #4228

**Closed** 2016-02-13 14:57 UTC
Labels: duplicate
