### ISSUE TITLE
Background Transparency not working.

### ISSUE THREAD

**Issue by mathacka** [processing/processing#5299] opened 2017-11-02 09:48 UTC
The code

`background(0,100);`

is supposed to give the background of the canvas alpha transparency of 100. This feature has worked before and  is currently not working in processing 3.3.6. It is working correctly in p5js.

the documentation clearly states in processing website:

"Syntax | background(rgb) background(rgb, alpha) background(gray) background(gray, alpha) background(v1, v2, v3) background(v1, v2, v3, alpha) background(image)
-- | --
rgbint: any value of the color datatypealphafloat: opacity of the background | int: any value of the color datatype | float: opacity of the background
int: any value of the color datatype
float: opacity of the background"

**Comment by jeremydouglass** [comment] 2017-11-02 18:57
Re:

> The code `background(0,100);` is supposed to give the background of the canvas alpha transparency of 100.

For the canvas this is clearly not correct. Read the documentation again:

-  https://processing.org/reference/background_.html

> It is not possible to use the transparency alpha parameter with background colors on the main drawing surface. It can only be used along with a PGraphics object and createGraphics().

**Comment by jeremydouglass** [comment] 2017-11-02 18:59
Ah, I see this is a duplicate of #5293

**Closed** 2017-11-02 20:40 UTC
