### ISSUE TITLE
Application export OSX developer signing

### ISSUE THREAD

**Issue by tomspace** [processing/processing#4965] opened 2017-03-14 13:23 UTC
Apps exported from Processing 3.3 are unable to be opened on OSX with gatekeeper enabled. The app reports as "Damaged" rather than saying it is from an unknown developer. 

There seems to be something wrong with the signature used to sign the app. Disabling gatekeeper allows the app to run, however in latest OSX this requires sudo command line and is not very user friendly. 

![screen shot 2017-03-14 at 13 18 13](https://cloud.githubusercontent.com/assets/1330148/23902491/357ae65a-08b9-11e7-9456-d061a8f8071a.png)

**Comment by benfry** [comment] 2017-04-21 21:45
Duplicate of https://github.com/processing/processing/issues/4705

**Closed by benfry** 2017-04-21 21:45 UTC
