### ISSUE TITLE
editor ide comments

### ISSUE THREAD

**Issue by aarondbaron** [processing/processing#4833] opened 2017-01-16 20:01 UTC
On windows machine,

Sometimes the comments are painted as though they are code (keywords highlighted).  Sometimes also code can be painted as a comment.  I can't figure out yet what conditions this happens, but it might be due to block comments and how much of it is seen in the code editor window.  

Functionally speaking, there is no critical issue.  The compiler throws no errors.  It's just a weird presentation issue that happens occasionally that also fixes itself if you scroll all the way back up to the top of the pde file or at least where the comment is supposed to start or end, and then go back down.  It is just a little annoying.

**Comment by gohai** [comment] 2017-01-17 02:02
Duplicate of #4286

**Closed by gohai** 2017-01-17 02:02 UTC
