### ISSUE TITLE
video package is missing

### ISSUE THREAD

**Issue by amudiel** [processing/processing#5338] opened 2017-12-17 19:04 UTC
Hi, I download the video libray from git-hub and I paste it on the library folder however when I call the PDE and put import processing.video.*; say video package is missing

**Comment by benfry** [comment] 2017-12-17 19:40
Dupe of https://github.com/processing/processing-video/issues/87

**Closed by benfry** 2017-12-17 19:40 UTC

**Comment by amudiel** [comment] 2017-12-17 21:54
sorry for the duplicate issue, is just that I have being presenting this problem for a while, and I am new on this. what shall I do
