### ISSUE TITLE
Processing 3.3.2

### ISSUE THREAD

**Issue by dangerdes** [processing/processing#5034] opened 2017-04-27 15:25 UTC
I just noticed that keyPressed && key == variables no longer work as intended in sketches that were created with 3.2.3. The keys become "sticky", i.e. they no longer toggle on and off automatically while being pressed and released respectively.

**Comment by gohai** [comment] 2017-04-27 15:34
Hi @dangerdes - I believe this was fixed with this commit earlier today: https://github.com/processing/processing/commit/9b5824ef75eeb56a793773314cda2d98228eed84

**Comment by dangerdes** [comment] 2017-04-27 15:38
Thank you @gohai. But I just downloaded 3.3.2 and ran into this issue. I always save previous versions, and because I'm just working with my middle school students on a simple program, it's not super critical, but I imagine that for some of us it could be a big deal!

**Comment by gohai** [comment] 2017-04-27 15:41
Yes, and thanks for reporting - simply wanted to point out that it is a known issue at this point, with a code change in place that will fix it in the next release.

**Closed by gohai** 2017-04-27 15:41 UTC

**Comment by benfry** [comment] 2017-04-27 16:12
Marking as duplicate of https://github.com/processing/processing/issues/5033
