### ISSUE TITLE
PApplet fails to load if JDK's "java.version" lacks any "."

### ISSUE THREAD

**Issue by Phil-DS** [processing/processing#5302] opened 2017-11-06 20:52 UTC
When System.getProperty("java.version") results in a value that has no "." in it, PApplet fails to load.
When I used Processing, I got "1.8.0_144"
When I used IntelliJ, I got "9"

Error is 
java.lang.ExceptionInInitializerError
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at processing.core.PApplet.<clinit>(PApplet.java:122)
Exception in thread "main" 

The line it states in the core.jar (decompressed) is:
javaPlatform = parseInt(split(javaVersionName, '.')[1]);

I downloaded a new jdk, it returned "9.0.1", and worked.

The problem is when it doesn't have a "." it fails. It would want some handling to prevent the error.

**Comment by gohai** [comment] 2017-11-06 22:39
Duplicate of #5275. This is already fixed for the next version after 3.3.6.

**Closed by gohai** 2017-11-06 22:39 UTC
