### ISSUE TITLE
mouseWheel event.getCount() not consistent between FX2D and the default renderer

### ISSUE THREAD

**Issue by tarabishy2020** [processing/processing#5204] opened 2017-08-01 11:32 UTC
```
void setup(){
  size(300,300,FX2D);
  //size(300,300);
}

void draw(){
  
}

void mouseWheel(MouseEvent event){
println(event.getCount());
}
```

activating FX2D and then not activating it produces completely different numbers, specifically, when its activated a lot of zeros are returned as opposed to when its not, rendering it a bit useless when using it as an input to edit anything (i.e zooming for example)

**Comment by Bobby54** [comment] 2019-08-09 19:13
@benfry Has this issue already been fixed?
Either I'm not having this issue or it was fixed.
If not I would like to work on this one.

**Comment by benfry** [comment] 2019-10-04 09:58
Ok, closing since it can't be reproduced.

**Closed by benfry** 2019-10-04 09:58 UTC
Labels: help wanted
