### ISSUE TITLE
Pasting text into PDE results in "Clipboard does not contain a string"

### ISSUE THREAD

**Issue by JakubValtar** [processing/processing#3651] opened 2015-08-17 22:49 UTC
Sometimes when I copy the sketch code from PDE by pressing Ctrl+A and Ctrl+C, then close the PDE, open it again and paste the code back by pressing Ctrl+V, nothing is pasted and I get "Clipboard does not contain a string" error message.

**Comment by benfry** [comment] 2015-08-17 23:58
Added debug messages, see what it prints and report here.

**Comment by JakubValtar** [comment] 2015-08-18 00:09
Can't reproduce right now, but it happens from time to time. Will post here when it happens again.

**Comment by JakubValtar** [comment] 2015-08-18 00:10
Good, got it right now!
```
Clipboard does not contain a string
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:895)
	at java.util.TimSort.mergeAt(TimSort.java:512)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:453)
	at java.util.TimSort.sort(TimSort.java:250)
	at java.util.Arrays.sort(Arrays.java:1438)
	at sun.awt.datatransfer.DataTransferer.setToSortedDataFlavorArray(DataTransferer.java:2410)
	at sun.awt.datatransfer.DataTransferer.getFlavorsForFormatsAsArray(DataTransferer.java:873)
	at sun.awt.datatransfer.SunClipboard.getAvailableDataFlavors(SunClipboard.java:172)
	at processing.app.syntax.JEditTextArea.paste(JEditTextArea.java:1916)
	at processing.app.ui.Editor$PasteAction.actionPerformed(Editor.java:1536)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at processing.app.syntax.JEditTextArea.processKeyEvent(JEditTextArea.java:1981)
	at processing.mode.java.pdex.JavaTextArea.processKeyEvent(JavaTextArea.java:231)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4752)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by JakubValtar** [comment] 2015-08-18 00:28
I guess that's not much helpful. Also got this one, seems unrelated:
```
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Error repainting line range {51,64}:
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at processing.mode.java.pdex.JavaTextAreaPainter.paintErrorLine(JavaTextAreaPainter.java:365)
	at processing.mode.java.pdex.JavaTextAreaPainter.paintLine(JavaTextAreaPainter.java:257)
	at processing.app.syntax.TextAreaPainter.paint(TextAreaPainter.java:490)
	at processing.mode.java.pdex.JavaTextAreaPainter.paint(JavaTextAreaPainter.java:600)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5219)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1572)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1495)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1265)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5167)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4978)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:824)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:807)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731)
	at javax.swing.RepaintManager.access$1300(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by benfry** [comment] 2015-08-18 00:38
Whoa, the first one is a JVM bug (that line in the PDE is querying for available data on the clipboard, and the error is happening inside the VM). 

And the second one is completely unrelated... wow. 

Also wondering if it's just your machine.

**Comment by benfry** [comment] 2015-08-18 00:44
For the second, just made the list synchronized to see if that helps.

**Comment by JakubValtar** [comment] 2015-08-18 02:06
This is so bizarre.

I tried like 200 times before I got some error. Sometimes it happens multiple times in a row. I think the error happens during copy or cut, because once my clipboard gets spoiled, it gives the error every time I paste into the PDE.

I'll post the trace if it happens again.

**Comment by benfry** [comment] 2015-08-18 02:16
You wouldn't make me chase a [no longer existing bug](http://bugs.java.com/view_bug.do?bug_id=7173464) because you're not using the 8u45 Java VM included with Processing, would you?

**Comment by JakubValtar** [comment] 2015-08-18 02:57
I'm using JDK 8u51 x64 downloaded from Oracle. I'm going to try to reproduce the original issue, because I got it randomly several times during recent days. I think the first stack trace is not related, because it crashed before printing the actual error.

**Comment by benfry** [comment] 2015-08-18 12:37
Just double-check if you haven't already. IntelliJ often embeds its own JVM, which it may be using if you're not using `ant run`.

**Comment by JakubValtar** [comment] 2015-08-18 14:34
```
PApplet.println(System.getProperty("java.tuntime.version")); // 1.8.0_51-b16
PApplet.println(System.getProperty("sun.arch.data.model")); // 64
```

My current clipboard content produces the `Comparison method violates its general contract` every ~5 runs with ```ant run```.

When this happens, it produces the error until I close PDE and start it again.

If I open a new window with File->New, it happens also there.

So either everything is okay and pasting works as expected, or it produces the error right from the first paste and I have to restart PDE, it never starts giving the error after it worked for the first time.

**Comment by JakubValtar** [comment] 2015-08-18 16:04
When I'm able to paste the text, I'm getting this:
```
DataFlavor[] flavors = clipboard.getAvailableDataFlavors();
for (DataFlavor f : flavors) {
  try {
    Object o = clipboard.getContents(this).getTransferData(f);
    System.out.println(f + " = " + o);
  } catch (Exception ex) {
    ex.printStackTrace();
  }
}
```

```
java.net.MalformedURLException: no protocol: 
void setup() {
  size(400, 400, P2D);
}

void draw() {
  background(255);
}
	at java.net.URL.<init>(URL.java:586)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at sun.awt.windows.WDataTransferer.translateBytes(WDataTransferer.java:281)
	at sun.awt.datatransfer.ClipboardTransferable$DataFactory.getTransferData(ClipboardTransferable.java:71)
	at sun.awt.datatransfer.ClipboardTransferable.getTransferData(ClipboardTransferable.java:168)
	at processing.app.syntax.JEditTextArea.paste(JEditTextArea.java:1877)
	at processing.app.ui.Editor$PasteAction.actionPerformed(Editor.java:1536)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at processing.app.syntax.JEditTextArea.processKeyEvent(JEditTextArea.java:1994)
	at processing.mode.java.pdex.JavaTextArea.processKeyEvent(JavaTextArea.java:231)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4752)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.Reader] = java.io.InputStreamReader@6e8ed993
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.lang.String] = 
void setup() {
  size(400, 400, P2D);
}

void draw() {
  background(255);
}
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.nio.CharBuffer] = 
void setup() {
  size(400, 400, P2D);
}

void draw() {
  background(255);
}
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=[C] = [C@4eb083fb
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.nio.ByteBuffer;charset=UTF-16] = java.nio.HeapByteBuffer[pos=0 lim=154 cap=154]
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.InputStream;charset=UTF-8] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@44d2b2b6
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.nio.ByteBuffer;charset=UTF-8] = java.nio.HeapByteBuffer[pos=0 lim=76 cap=76]
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=[B;charset=UTF-8] = [B@202e80e7
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.nio.ByteBuffer;charset=UTF-16BE] = java.nio.HeapByteBuffer[pos=0 lim=152 cap=152]
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.InputStream;charset=UTF-16LE] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@38f48730
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=[B;charset=UTF-16LE] = [B@7211648e
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.nio.ByteBuffer;charset=ISO-8859-1] = java.nio.HeapByteBuffer[pos=0 lim=76 cap=76]
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.InputStream;charset=windows-1252] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@23073f78
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.InputStream;charset=windows-1252] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@777aba47
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=[B;charset=windows-1252] = [B@6bab6e9f
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.InputStream;charset=US-ASCII] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@12e75270
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=[B;charset=US-ASCII] = [B@88143ab
java.awt.datatransfer.DataFlavor[mimetype=application/x-java-serialized-object;representationclass=java.lang.String] = 
void setup() {
  size(400, 400, P2D);
}

void draw() {
  background(255);
}
java.awt.datatransfer.DataFlavor[mimetype=application/x-java-text-encoding;representationclass=[B] = [B@2a0b687e
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.InputStream;charset=UTF-16] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@1a642436
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=[B;charset=UTF-16] = [B@32b891d8
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.InputStream;charset=UTF-16BE] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@3026103f
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=[B;charset=UTF-16BE] = [B@411fc6dd
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.nio.ByteBuffer;charset=UTF-16LE] = java.nio.HeapByteBuffer[pos=0 lim=152 cap=152]
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.io.InputStream;charset=ISO-8859-1] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@7ae11f5c
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=[B;charset=ISO-8859-1] = [B@c216789
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.nio.ByteBuffer;charset=windows-1252] = java.nio.HeapByteBuffer[pos=0 lim=76 cap=76]
java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.nio.ByteBuffer;charset=US-ASCII] = java.nio.HeapByteBuffer[pos=0 lim=76 cap=76]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.Reader] = java.io.InputStreamReader@c8629da
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.lang.String] = 
void setup() {
  size(400, 400, P2D);
}

void draw() {
  background(255);
}
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.CharBuffer] = 
void setup() {
  size(400, 400, P2D);
}

void draw() {
  background(255);
}
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[C] = [C@33102fb9
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=unicode] = java.io.StringReader@41f9dd78
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=UTF-16] = java.nio.HeapByteBuffer[pos=0 lim=154 cap=154]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=UTF-16] = [B@46e3e7e1
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=UTF-8] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@7b16de1e
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=UTF-8] = java.nio.HeapByteBuffer[pos=0 lim=76 cap=76]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=UTF-8] = [B@49495b22
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=UTF-16BE] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@46d45d6e
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=UTF-16BE] = java.nio.HeapByteBuffer[pos=0 lim=152 cap=152]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=UTF-16BE] = [B@1f5176ba
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=UTF-16LE] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@527aad60
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=UTF-16LE] = java.nio.HeapByteBuffer[pos=0 lim=152 cap=152]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=UTF-16LE] = [B@51e97c46
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=ISO-8859-1] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@35b26438
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=ISO-8859-1] = java.nio.HeapByteBuffer[pos=0 lim=76 cap=76]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=ISO-8859-1] = [B@21422092
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=windows-1252] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@26d49877
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=windows-1252] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@3cc5cba7
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=windows-1252] = java.nio.HeapByteBuffer[pos=0 lim=76 cap=76]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=windows-1252] = [B@1af0eba3
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=US-ASCII] = sun.awt.datatransfer.DataTransferer$ReencodingInputStream@2a861edf
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=US-ASCII] = java.nio.HeapByteBuffer[pos=0 lim=76 cap=76]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=US-ASCII] = [B@28932cd8

```

**Comment by hamoid** [comment] 2016-05-10 09:58
I get this error every time I copy text from vim and paste it into Processing. Pasting the same text into other programs like Eclipse works fine. On ArchLinux 64bit. Is there a way to analyze the content of the clipboard?

The exception is different from the ones above:

```
Clipboard does not contain a string
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Failed to retrieve atom name.
	at sun.awt.X11.XlibWrapper.XGetAtomName(Native Method)
	at sun.awt.X11.XAtom.getName(XAtom.java:186)
	at sun.awt.X11.XDataTransferer.getTargetNameForAtom(XDataTransferer.java:165)
	at sun.awt.X11.XDataTransferer.getNativeForFormat(XDataTransferer.java:154)
	at sun.awt.datatransfer.DataTransferer.getFlavorsForFormatsAsSet(DataTransferer.java:812)
	at sun.awt.datatransfer.DataTransferer.getFlavorsForFormatsAsArray(DataTransferer.java:873)
	at sun.awt.datatransfer.SunClipboard.getAvailableDataFlavors(SunClipboard.java:171)
	at processing.app.syntax.JEditTextArea.paste(JEditTextArea.java:1919)
	at processing.app.ui.Editor$PasteAction.actionPerformed(Editor.java:1309)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at processing.app.syntax.JEditTextArea.processKeyEvent(JEditTextArea.java:1984)
	at processing.mode.java.pdex.JavaTextArea.processKeyEvent(JavaTextArea.java:221)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by benfry** [comment] 2022-08-06 12:06
Closing this one for now because it's hopefully resolved in more recent Java release. 

If not, please re-open a fresh issue with details on how to reproduce in the Processing 4 repo: https://github.com/processing/processing4/issues/new

**Closed by benfry** 2022-08-06 12:06 UTC
Labels: pde
