### ISSUE TITLE
Example 'Topics/Shader/Convay' crashes

### ISSUE THREAD

**Issue by toniholzer** [processing/processing#3973] opened 2015-10-08 09:32 UTC
The 'Conway' example crashes under processing v3.0 at line 25 'pg.endDraw();'
with the error message 'NullPointerException'.
That's strange because 'pg' is used many times before and it's not crashing with processing 2.x ! 
     
There is another shaky coding in this example:
Call of 'size' uses P3D and 'createGraphics' uses P2D as renderer.
Because it's a 2d example, 'size' should use P2D too.
Nevertheless correcting this inadequacy let crash the example too!

Btw. the example link should be corrected to http://glslsandbox.com/e#207.4

Here's the original code:        
<pre><code>
// GLSL version of Conway's game of life, ported from GLSL sandbox:
// http://glsl.heroku.com/e#207.3
// Exemplifies the use of the ppixels uniform in the shader, that gives
// access to the pixels of the previous frame.
PShader conway;
PGraphics pg;
void setup() {
  size(400, 400, P3D);    
  pg = createGraphics(400, 400, P2D);
  pg.noSmooth();
  conway = loadShader("conway.glsl");
  conway.set("resolution", float(pg.width), float(pg.height));  
}
void draw() {
  conway.set("time", millis()/1000.0);
  float x = map(mouseX, 0, width, 0, 1);
  float y = map(mouseY, 0, height, 1, 0);
  conway.set("mouse", x, y);  
  pg.beginDraw();
  pg.background(0);
  pg.shader(conway);
  pg.rect(0, 0, pg.width, pg.height);
  pg.endDraw();                                        // v3.0 -> NullPointerException
  image(pg, 0, 0, width, height);
}
</code></pre>

**Comment by toniholzer** [comment] 2015-10-08 10:04
In the meantime I found out that it must have something to do with the 'back buffer' of the shader.
if we change the word 'ppixels'  'of shader file data/convay.glsl' to 
the error message change to

**Comment by codeanticode** [comment] 2015-10-08 10:56
This is a duplicate of https://github.com/processing/processing/issues/3947

It has been fixed in the repo, 3.0.1 will incorporate the fix.

**Closed by codeanticode** 2015-10-08 10:56 UTC
Labels: duplicate, opengl
