### ISSUE TITLE
Error upon processing-3.0.2-windows64 install

### ISSUE THREAD

**Issue by laxdudeee** [processing/processing#4424] opened 2016-04-24 04:08 UTC
Hi,
I am receiving the following error message after installing the latest Processing version. Before I unpacked it I deleted a previous Processing version that I had installed. 

http://imgur.com/flc1rQg

Thanks for any help.
Best,
Eric D

**Comment by JakubValtar** [comment] 2016-04-24 23:32
Hi @laxdudeee, can you please post a full path of the folder where you have processing?

Looks like a duplicate of #4417, should be fixed by #4426.

**Comment by laxdudeee** [comment] 2016-04-25 16:09
I am away from that computer but I will say that I simply turned it Off/On and the error went away. It must have had some residual from the previous version that was hanging on.

**Closed** 2016-04-25 16:09 UTC
