### ISSUE TITLE
P2D and P3D not working on Linux (Ubuntu 20.04 with Intel 620 Graphics)

### ISSUE THREAD

**Issue by villares** [processing/processing#6061] opened 2020-06-26 23:59 UTC
## Description

On a fresh Ubuntu 20.04 install on a Lenovo V310, I can run sketches with `size(__, __)`  but not `size(___, ___, P3D) ` nor `P2D` 

## Expected Behavior 
Grey canvas.

## Current Behavior
Black canvas and error:
```
Profile GL4bc is not available on X11GraphicsDevice[type .x11, connection :0.0, unitID 0, handle 0x7fdc7801d9d0, owner true, ResourceToolkitLock[obj 0x449eeca2, isOwner true, <40a170e9, 5a3e699>[count 1, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>]]], but: [GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]
```

## Steps to Reproduce
```java
size(400, 400, P3D);
```

## Your Environment
* Processing version: 3.5.4
* Operating System and OS version: Ubuntu 20.04
* Other information:
```
$ glxinfo -B
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 620 (KBL GT2) (0x5916)
    Version: 20.0.4
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.4
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.4
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by villares** [comment] 2020-06-27 23:20
Related to: https://github.com/processing/processing/issues/5476

workarounds:

Java mode
```java
void settings() { 
  System.setProperty("jogl.disable.openglcore", "false");
  size(400, 400, P3D);
}
```

Python mode, thanks to @goToLoop
```python
from java.lang import System
System.setProperty("jogl.disable.openglcore", "false")

def setup():
    size(200, 200, P3D)
```

**Comment by benfry** [comment] 2020-09-23 23:42
Closing as duplicate of #5476.

**Closed by benfry** 2020-09-23 23:42 UTC
