### ISSUE TITLE
Build from Source fails.   Seems to not acquire oracle java

### ISSUE THREAD

**Issue by TPMoyer** [processing/processing#5868] opened 2019-05-30 12:46 UTC
Fail: Build from Source described in https://github.com/processing/processing/wiki/Build-Instructions.
No error codes, no warnings, just no processing window open at the end.
Did show one indicator of things not going well in the jre-download section:
```
     Header Name:null
     Header value:HTTP/1.1 404 Not Found
```
Suspect the fail is related to the new Oracle requirement of signing in to your oracle account, before being allowed to download java.   The clue which suggests that portion of the prior build.xml procedure is:  after the ant run
the \myGitHubLocation\processing\build\jre\bin\ directory has only one ~7kb file named Downloader.class

My system:
```
Windows 7 pro, SP1
Oracle java downloaded today's most recent versions versions:  jdk1.8.0_211  and jre1.8.0_211
ant downloaded today's most recent version: 1.10.6
ANT_HOME is set, 
JAVA_HOME is set to jdk
path has     %ANT_HOME%\bin;%JAVA_HOME%\bin;  
new command prompt window (post environment variable set) confirms   both 
     ant -version   
     java -version
```
Output from ant run is

```
Buildfile: C:\a_GitHub\processing\build\build.xml

run:

ignore-tools:
     [echo] Ignore the 'Unable to locate tools.jar' message.
     [echo] The tools.jar file is not required to build Processing.

revision-check:

windows-check-os:

jre-check:

downloader-setup:

compile:

dist:

jre-download:
[downloader] Redirecting to https://edelivery.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz
[downloader] Redirecting to http://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz?AuthParam=1559147309_1841c447d1cb984d09e29377057e36fa
[downloader] Redirecting to https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-windows-x64.tar.gz?AuthParam=1559147309_1841c447d1cb984d09e29377057e36fa
[downloader] Header Name:Accept-Ranges
[downloader] Header value:bytes
[downloader] 
[downloader] Header Name:null
[downloader] Header value:HTTP/1.1 404 Not Found
[downloader] 
[downloader] Header Name:Server
[downloader] Header value:AkamaiNetStorage
[downloader] 
[downloader] Header Name:ETag
[downloader] Header value:"477d9862374177c810b0b7d73b4f1e53:1531792454.541174"
[downloader] 
[downloader] Header Name:Connection
[downloader] Header value:keep-alive
[downloader] 
[downloader] Header Name:Last-Modified
[downloader] Header value:Wed, 31 Aug 2011 20:28:54 GMT
[downloader] 
[downloader] Header Name:Content-Length
[downloader] Header value:7073
[downloader] 
[downloader] Header Name:Date
[downloader] Header value:Wed, 29 May 2019 16:26:29 GMT
[downloader] 
[downloader] Header Name:Content-Type
[downloader] Header value:text/html
[downloader] 
```

Workarounds tried/failed.

1) Copied the jre1.8.0_211 directory into the \myGitHubLocation\processing\build\jre directory
and changed the build.xml variable to match:
property name=“jdk.update” value=“211” /
2) Copied the jdk1.8.0_211 directory into \myGitHubLocation\processing\build\jre
3) logged into my Oracle account in Chrome, ran the CLI   ant run
4) downloaded and installed jre1.8.0_202, changed JAVA_HOME and references in path to this version, confirmed build.xml has version pointed to is 202 (property name="jdk.update" value="202"). Confirmed java -version shows 1.8.0_202
ran the CLI ant run

Workaround hope:    Some way to put the desired jre in a location which a revised build.xml could use as it's source.   The build instructions might need to be expanded a bit to describe the path toward obtaining archive JRE's.  The the trail of breadcrumbs from google search to archived java versions has enough steps that some users might not succeed.   Google search on [Oracle Java Downloads](https://www.oracle.com/technetwork/java/javase/downloads/index.html) to the download button next to  [Java Archive](https://www.oracle.com/technetwork/java/javase/archive-139210.html), on thru [Java SE 8](https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html) which finally gives access to the desired version.

**Comment by monkstone** [comment] 2019-05-30 14:23
It seems @benfry is aware of this https://github.com/processing/processing/commit/37108add372272d7b1fc23d2500dce911c4d1098, eventually processing.org is going to have to bite the bullet and use OpenJDK, and preferably OpenJDK11. @sampottinger has done some great work in this direction https://github.com/sampottinger/processing but so far there is no indication of whether processing.org are going to respond to his PR.

**Comment by kfrajer** [comment] 2019-05-31 15:54
Duplicate of #5860

**Comment by benfry** [comment] 2019-06-11 17:41
Due to more unfortunate changes by Oracle, Java 8u202 is the only version that works at the moment. I've updated the [build instructions](https://github.com/processing/processing/wiki/Build-Instructions) to reflect this.

**Closed by benfry** 2019-06-11 17:41 UTC
