### ISSUE TITLE
processing-java can't build anymore (processing-3.1)

### ISSUE THREAD

**Issue by FreewheelinFranklin** [processing/processing#4475] opened 2016-05-14 09:58 UTC
platform : Linux 4.4.0 x86_64 (ubuntu 16.04)

when using _processing-java_ with arguments --run, --build or --export, it crashes on build phase with :
```
err is java.lang.reflect.InvocationTargetException
Exception in thread "main" java.lang.NullPointerException
	at processing.mode.java.Commander.<init>(Commander.java:263)
	at processing.mode.java.Commander.main(Commander.java:86)
```

the same command works perfectly on processing-3.0.2
PDE editor works fine (as far as I've tested it) and can run my sketches

I've tested a very simple helloWorld sketch to make sure it was not library related :
```
void setup(){
}

void draw(){
	println("helloworld");
}
```

**Comment by jarmohurri** [comment] 2016-05-14 12:09
Same here, on platform Linux 4.4.8-200.fc22.x86_64 with sketch

```
size (600, 400);
rect (70, 40, 150, 90);
```

**Comment by benfry** [comment] 2016-05-14 13:14
Duplicate of https://github.com/processing/processing/issues/4452

**Closed by benfry** 2016-05-14 13:14 UTC
