### ISSUE TITLE
Multiline String (\n), +=, concat, print, println, broken on MacOS in 3.3.4 update

### ISSUE THREAD

**Issue by pshubert** [processing/processing#5113] opened 2017-06-05 23:00 UTC
There is something seriously broken with String concatenation, inserting the "newline" (\n), or the print()/println() function in the 3.3.4 update on MacOS.

Simple Example:
`void setup()
{
  String s1 = "Test 1\nTest 2\n";
  s1 += "Test 3\nTest 4\n";
  print(s1);
  println();
  
  println("Next");
  
  String s2 = "Test 1\nTest 2\n";
  String s3 = s2.concat("Test 3\nTest 4\n");
  print(s3);
}

void draw()
{
  exit();
}`

Produces:
Test 3
Test 4

This code works fine in 3.3

**Comment by benfry** [comment] 2017-06-05 23:21
Duplicate of https://github.com/processing/processing/issues/5110

**Closed by benfry** 2017-06-05 23:21 UTC
