### ISSUE TITLE
Problem with the definition of the screen of a tablet 9.7" (2048 x 1536) Windows 10

### ISSUE THREAD

**Issue by didier013** [processing/processing#4077] opened 2015-10-28 17:18 UTC
Hello
With the definition of the screen of my tablet 9.7 "(2048 x 1536 pixels), the displayed characters are too small and I can not click on the names of files (demos / examples). Even if I reduce my definition of screen, I still have the problem. 
Do you have a solution? 
Thanks for your answers

**Comment by aengelke** [comment] 2015-10-29 15:47
Is the display an hi-dpi display? Also, what OS are you using? (If you use Windows and the tablet has a hi-dpi display, this is likely to be #2411.)

**Comment by didier013** [comment] 2015-10-29 17:50
Hello

First of all, thank you for your answer.

The characteristics of my tablet: Graphic card: Intel HD Gen8 • Mémory: 4GB Rom + 64GB Ram • Screen: Screen Size:9.7 with 2048 x 1536 IPS (retina 2048 x 1536 4:3 ratio IPS panel). • Systems: Windows 10 + Android 5.1 Dual Boot.

I reduced the resolution of my screen but the problem persists. 

There is the screenshot (attached file) 

Texrs (examples) are tiny.

I can not click on it!



Dr. Didier Cuménal

PhD University of Paris Sorbonne

Graduate astronomy Observatory Paris

Head of Dynamic Systems, Group AFSCET the French Association of Systems Sciences (http://www.afscet.asso.fr/)

Member System Dynamics Society

Mail : cumenald@wanadoo.fr

Cell phone : 00 33 6 09 10 95 03

**Comment by benfry** [comment] 2015-11-01 19:18
Duplicate of https://github.com/processing/processing/issues/2411

**Closed by benfry** 2015-11-01 19:18 UTC
