### ISSUE TITLE
FloatList.size() not working

### ISSUE THREAD

**Issue by C1klops** [processing/processing#3044] opened 2015-01-15 03:39 UTC
Hi all, 

First post here. I need to get the length of a list for a project but it look like the .size() fonction is not working (always returning 0). Please view the attached screenshot.

Processing version 2.2.1 on OSX Yosemite

FloatList list = new FloatList();
void setup(){
  size(300,300);
  list.add(0,000);
  list.add(1,100);
  list.add(2,200);
  list.add(3,300);
}
void draw(){}
void mouseClicked(){
  for(int i=0; i<3; i++){ println("list index "+i+" is "+list.get(i)); }
  println("list length is "+list.size());
}

![screen shot 2015-01-14 at 10 31 51 pm](https://cloud.githubusercontent.com/assets/10541374/5752180/41c25d60-9c3e-11e4-9881-b6eb14c27a2e.png)

**Comment by GKFX** [comment] 2015-01-15 18:51
On Processing 3 (0233; on Ubuntu x64 en-GB), I get
````java
    println("list index "+i+" is "+list.get(i));
````
throwing an `ArrayIndexOutOfBoundsException`, with array index out of bounds: 0. If I wrap that line in a try-catch block I also see the message `list length is 0`.

On Processing 2.2.1 I can reproduce it exactly.

**Comment by GKFX** [comment] 2015-01-15 18:55
Hold on – you're calling the wrong method. `add` is defined as
````java
/**
* @webref floatlist:method
* @brief Add to a value
*/
public void add(int index, float amount) {
  data[index] += amount;
}
````
It increased an already existing value, but since the value doesn't exist, it won't work.
You want `insert(int index, float value)`.

This issue should not be closed, because exceptions need throwing.

**Comment by C1klops** [comment] 2015-01-15 22:28
Thanks.

Also, insert.() doesn't exist in the ListFloat class, but basically, .append() in processing is the .add() in Java. I replaced and now it seams to be working.

**Comment by GKFX** [comment] 2015-01-16 13:35
`insert` is a recent addition - you may need to use the latest alpha build
to get it, or wait for the first full 3.0 release. `append` is the one to
use here though.

**Comment by benfry** [comment] 2015-01-16 19:29
Wrong method, not a bug, closing.

**Comment by GKFX** [comment] 2015-01-17 13:54
@benfry Method should throw exception as stated above, is a bug, please reopen. Thanks.

**Comment by benfry** [comment] 2015-01-19 20:09
To the title of this report, `FloatList.size()` is working just fine. If there's an exception you'd like added, please file something that explains what's missing.

**Closed by benfry** 2015-01-19 20:09 UTC
Labels: invalid
