### ISSUE TITLE
Processing.org site redirects to donation page when choosing download link

### ISSUE THREAD

**Issue by edo-xebia** [processing/processing#5660] opened 2018-09-25 13:30 UTC
## Description

When choosing the download link from the menu on the processing.org site, I am redirected to the donation page. I found no way to a proper download, and was therefore not able to download the software from the site. It is not logical to have to donate first to be able to download free software. As an aside, there is no guarantee that after donating, the download becomes available.

## Expected Behavior

When choosing the download link for the chosen OS, you should be redirected to the download of the software for that OS.

## Current Behavior

When choosing the download link for the chosen OS, you are redirected to the donation page. It is currently not possible to download the software from the site.

## Steps to Reproduce

1. Go to processing.org
2. Click download from the left side menu bar
3. Click Windows 64bit from the download page

## Your Environment

 

* Processing version:
* Windows 10 64bit
* Chrome browser

**Comment by dzaima** [comment] 2018-09-25 14:02
At least for me (64-bit Mint, Chromium), clicking any link goes to the donation page and opens another tab with the download in the background. I suspect you might have some blocker blocking the extra tab?

a middle-click on the link opens the download on another tab without going to the donation page too.

**Comment by gohai** [comment] 2018-09-25 17:46
Can't reproduce here either. You can also always download the releases from GitHub's releases page.

**Comment by benfry** [comment] 2018-09-30 22:17
Closing; can't reproduce. The download begins while the user is sent to the page where we ask for help, as intended.

**Closed by benfry** 2018-09-30 22:17 UTC
