### ISSUE TITLE
point does not work with strokeCap SQUARE

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#5957] opened 2019-11-22 11:10 UTC
point does not work when strokeCap is set to SQUARE.

```java
strokeWeight(20);
strokeCap(SQUARE);
point(50, 50);
```

Not sure if it is worth adding if statements due to speed? Maybe it should be mentioned in the reference?

**Comment by Prometal328** [comment] 2019-11-24 10:04
Could you please give more information about the **OS** and the **Processing version**?
It works on Processing 3.5.3, windows 10.

**Comment by clankill3r** [comment] 2019-11-24 18:50
Sorry, I meant SQUARE, I must have been really tired.
I guess it happens on windows 10 now as well since it seems non OS specific.
Anyway, I'm on OSX10.12.6, 3.5.3.

**Comment by jeremydouglass** [comment] 2019-12-18 02:36
Interesting. Issue also exists on Processing 3.4 -- the example sketch does not display a point, however removing the `strokeCap(SQUARE);` line causes the point to be displayed.

**Comment by behreajj** [comment] 2019-12-31 18:16
This has been an issue for _years_, but is apparently intentional. See: https://github.com/processing/processing/issues/4871

**Comment by jeremydouglass** [comment] 2020-01-01 16:59
@behreajj -- thanks for pointing out -- perhaps submit to [processing-docs](https://github.com/processing/processing-docs/issues) as added language for the strokeCap page...?

**Comment by behreajj** [comment] 2020-01-02 19:06
I can see why, given performance concerns, documentation would be a preferred approach. For anyone looking for a workaround, I tried the following in a sub-class of `PGraphicsJava2D`:

```
import java.awt.BasicStroke;

public class Bar extends PGraphicsJava2D {
   protected int capNative = BasicStroke.CAP_ROUND;
   protected int joinNative = BasicStroke.JOIN_ROUND;

   @Override
   public void point ( float x, float y ) {
      boolean needSwap = this.capNative == BasicStroke.CAP_BUTT;
      if (needSwap) {
         this.strokeObject = new BasicStroke(
               this.strokeWeight,
               BasicStroke.CAP_SQUARE,
               this.joinNative);
         this.g2.setStroke(this.strokeObject);

         this.line(x, y, x + PConstants.EPSILON, y);

         this.strokeObject = new BasicStroke(
               this.strokeWeight,
               this.capNative,
               this.joinNative);
         this.g2.setStroke(this.strokeObject);
      } else {
         this.line(x, y, x + PConstants.EPSILON, y);
      }
   }
}
```

To do that I had to reorganize how `strokeImpl` worked with `strokeCap` and `strokeJoin`.

```
public class Bar extends PGraphicsJava2D {
   @Override
   public void strokeCap ( int cap ) {
      this.chooseStrokeCap(cap);
      this.strokeImpl();
   }

   @Override
   public void strokeJoin ( int join ) {
      this.chooseStrokeJoin(join);
      this.strokeImpl();
   }

   @Override
   public void strokeWeight ( float weight ) {
      this.strokeWeight = weight;
      this.strokeImpl();
   }

   protected void chooseStrokeCap ( int cap) {
      switch (cap) {
         case PROJECT:
            this.strokeCap = PConstants.PROJECT; /* 4 */
            this.capNative = BasicStroke.CAP_SQUARE; /* 2 */
            break;
         case SQUARE:
            this.strokeCap = PConstants.SQUARE; /* 1 */
            this.capNative = BasicStroke.CAP_BUTT; /* 0 */
            break;
         case ROUND:
         default:
            this.strokeCap = PConstants.ROUND; /* 2 */
            this.capNative = BasicStroke.CAP_ROUND; /* 1 */
      }
   }

   protected void chooseStrokeJoin ( int join ) {
      switch (join) {
         case BEVEL:
            this.strokeJoin = PConstants.BEVEL; /* 32 */
            this.joinNative = BasicStroke.JOIN_BEVEL; /* 2 */
            break;
         case MITER:
            this.strokeJoin = PConstants.MITER; /* 8 */
            this.joinNative = BasicStroke.JOIN_MITER; /* 0 */
            break;
         case ROUND:
         default:
            this.strokeJoin = PConstants.ROUND; /* 2 */
            this.joinNative = BasicStroke.JOIN_ROUND; /* 1 */
      }
   }

   @Override
   protected void strokeImpl () {
      this.strokeObject = new BasicStroke(
            this.strokeWeight,
            this.capNative,
            this.joinNative);
      this.g2.setStroke(this.strokeObject);
   }
}
```

The AWT [line object](https://github.com/processing/processing/blob/d6b30602a703e1d0280392c54794486ee34bca8c/core/src/processing/awt/PGraphicsJava2D.java#L89) used by `line` has `package` level access; otherwise I would've used that directly. Full code file [here](https://github.com/behreajj/CamZup/blob/master/src/camzup/pfriendly/YupJ2.java). I don't know anything about profiling code for efficiency, though, so caveat emptor.

**Comment by benfry** [comment] 2020-01-07 20:21
It's confusing and should be documented better, but it's not a bug. `strokeCap(SQUARE)` is equivalent to “butt” in PostScript or CSS, which means essentialy “no stroke cap at all,” so there's nothing projecting out from the point on screen, thus nothing drawn. 

Most people don't read the documentation, so we could potentially add a warning for folks calling `point()` with `SQUARE` and tell them to use `PROJECT`. 

(While we're at it, we also should note in the docs that 1 pixel line weights with `point()` are also problematic, since that's another one that comes up a lot, but is depending on OS/renderer/graphics card settings/etc.)

Closing as duplicate of https://github.com/processing/processing/issues/4871.

**Closed by benfry** 2020-01-07 20:21 UTC

**Comment by jeremydouglass** [comment] 2020-01-08 23:34
Okay, I will go ahead and submitting a simple strokeCap docs PR for 4871.

> (While we're at it, we also should note in the docs that 1 pixel line weights with `point()` are also problematic, since that's another one that comes up a lot, but is depending on OS/renderer/graphics card settings/etc.)

@benfry It sounds like this should be added to point() and/or strokeWeight(), but I wasn't sure of what the language should be about how exactly it is problematic. Point me at more detail or an open issue and I'm happy to write it up in a docs PR.

**Comment by benfry** [comment] 2020-01-16 21:24
Thanks @jeremydouglass, the issue is that `point()` isn't really a graphics primitive, so with the exception of OpenGL, the renderer has to fake it by either creating a tiny line, or perhaps draw a `rect()` or `ellipse()` instead. For instance, this is `point()` for Java2D:

```java
line(x, y, x + EPSILON, y + EPSILON);
```

The problem, though, is that depending on your OS, Java version, anti-aliasing mode, graphics card settings, phase of the moon, etc, this faux point may not actually happen. Usually it's ok, but it's fairly easy to have it not show anything. 

So something like:

> Using `point()` with small `strokeWeight(1)` or smaller may not draw anything to the screen, depending on the graphics settings on your computer. To fix this, you can 1) use `set()` instead, 2) use a larger `strokeWeight()`, or 3) draw the point using `circle()` or `square()` instead. 

Internally, we don't use those approaches because it would make `point()` *drastically* slower for the 80 or 90% of people for whom `point()` is working just fine.

**Comment by jeremydouglass** [comment] 2020-01-29 21:40
Great @benfry, I made your last suggestion another docs pull request.
