### ISSUE TITLE
Sketch not launching, even without code

### ISSUE THREAD

**Issue by Kerokuy** [processing/processing#4864] opened 2017-01-30 14:02 UTC
First of all I'm on the version 3.2.4 of Processing and I'm using 64-Bit Windows 10. 
As mentioned in the title I tried launching the Sketch without any code and still got the error:

Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

I really can't think of anything else to say. 

Any help is appreciated.

**Comment by itisltw** [comment] 2017-01-30 18:46
Hi, I have got same problem. It is caused by Nvidia Graphic card driver.
Just go to official website to download previous version
https://github.com/processing/processing/issues/4853

**Comment by benfry** [comment] 2017-01-30 19:41
Closing as duplicate of #4853.

**Closed by benfry** 2017-01-30 19:41 UTC
Labels: duplicate
