### ISSUE TITLE
New to forum/GitHub having issue with processing IDE

### ISSUE THREAD

**Issue by CMaC253** [processing/processing#4770] opened 2016-12-12 03:30 UTC
Hi yall,

I've used Processing for a year or so and I took a break to work on C#, HTML, CSS, and Javascript and other classes for school. I'm trying to get back into it so I downloaded it on my Surface Pro 4. I've never encountered this before, when I open it the text editor, console, and sketch itself are only about 2 inches 
[Wamp Wamp Processing.docx](https://github.com/processing/processing/files/645062/Wamp.Wamp.Processing.docx)
by 3 inches and everything is extremely small. I tried to look in preferences and edit the window, but it only changed the window size, not the sketch or the lines. Maybe this has been seen before, and if so please redirect me because I haven't found anything, but I'll leave a picture here for yall.

**Comment by benfry** [comment] 2016-12-12 11:12
Duplicate of https://github.com/processing/processing/issues/2411

**Closed by benfry** 2016-12-12 11:12 UTC
