### ISSUE TITLE
Save startup screen setting when closing the window with X

### ISSUE THREAD

**Issue by neilpanchal** [processing/processing#5296] opened 2017-10-30 05:46 UTC
I uncheck it and the damn thing keeps coming back.
![image](https://user-images.githubusercontent.com/8161031/32156446-aef0cc02-bcfa-11e7-8180-c35161e4f9c2.png)

Honest question - who enjoys startup dialog boxes? In my entire life of 30 years, I've never met a single person that says "Oh yes... I love getting popups for startup tips everytime I launch apps."....

Just saying! Get rid of this thing. 👎

**Comment by VictorGaiva** [comment] 2017-10-30 19:27
I'm having the same issue. It's pretty annoying. 

I solved this by unchecking the box and clicking the "Get Started" button.

Closing the window doesn't seem to save the state of the box.

**Comment by neilpanchal** [comment] 2017-10-30 19:47
@VictorGaiva That worked, thanks.

I think welcome messages, popups, flash pages, intros - all these ideas were cool in 2008. Not anymore. Instead, have a help button on the top-right corner that can bring up tutorials, what's new, etc... This thing impedes UX.

**Comment by VictorGaiva** [comment] 2017-10-31 01:23
I have been trying to fix this problem on the source-code but it seems that, because of the way it is written, it is really hard to change this behavior.

**Comment by benfry** [comment] 2017-10-31 20:02
Duplicate of https://github.com/processing/processing/issues/3912

**Closed by benfry** 2017-10-31 20:02 UTC
