### ISSUE TITLE
This error pops up on startup

### ISSUE THREAD

**Issue by YuyQuan** [processing/processing#4550] opened 2016-06-28 00:31 UTC
http://i.imgur.com/gKaiazl.png

Tried both 3.1.1 and reverting to 3.1
No good.
Thanks

**Comment by GKFX** [comment] 2016-06-28 13:47
@YuyQuan Thank you for reporting this! It's a duplicate of #4476 though, so please close it.

**Comment by gohai** [comment] 2016-06-29 13:30
Thanks for spotting @GKFX

**Closed by gohai** 2016-06-29 13:30 UTC
