### ISSUE TITLE
PShader & PImage issues with Java 8

### ISSUE THREAD

**Issue by FreeArtBureau** [processing/processing#5191] opened 2017-07-22 22:12 UTC
I can no longer compile sketches that use shaders and also having issues with simple PImage. I've found no other issues on this. I'm wondering if it has to do with Java's latest update... ? 

- Processing 3.3.5
- MACOS 10.12.6 | MAC Book Pro Core i5
- Java 8 version 141

Message : 

A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x000000011f837f58, pid=1347, tid=0x000000000001120f
JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode bsd-amd64 compressed oops)

Problematic frame:
C  [AppleIntelHD3000GraphicsGLDriver+0x270f58]  gldBlitFramebufferData+0x3fb

**Comment by JakubValtar** [comment] 2017-07-23 10:11
Duplicate of #4104

Sorry, we don't have a fix yet for this.

**Closed by JakubValtar** 2017-07-23 10:11 UTC

**Comment by FreeArtBureau** [comment] 2017-07-23 11:22
@JakubValtar Thank you for pointing out that thread. I've downgraded to P5 V221 as that seems the best solution for now on this rather old machine. 
Works fine. 

Thanks again.
