### ISSUE TITLE
Unable to setup project locally for contribution

### ISSUE THREAD

**Issue by pallav12** [processing/processing#5942] opened 2019-10-23 07:28 UTC
**ant run**

**error**
"Downloader has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

In documentation to setup project its clearly mentioned that Java 8 is required and that's what I have but the error says that "Downloader.class" has class file version of 54 which requires Java 10 to compile

Java -fullversion
java full version "1.8.0_202-b08"

javac -fullversion
javac full version "1.8.0_202-b08"

I first had a different version of Java 8 but now its java 8u202, Shifting to java 10 might work but that would be against documentation.

**Comment by kfrajer** [comment] 2019-11-01 22:01
What instructions are you following for this?
What branch did you download? 

I had some issues with ant in the past. You might want to check that post and see if it helps: https://github.com/processing/processing/issues/5860

But it is not clear how your get this error so more info is needed.

Kf

**Comment by pallav12** [comment] 2019-11-02 12:50
I have cloned the whole code of 1.6 GB
I used **cd build** **ant run**
I managed to solve the issue by simply deleting Downloader.class in build/jre/bin.
But now new Issue is apparently the same as [`5608`](https://github.com/processing/processing/issues/5608
)
And [solution](https://github.com/processing/processing/issues/5608#issuecomment-410597047) makes perfect sense, but I tried **git pull** and it's _Already up to date_

![github](https://user-images.githubusercontent.com/46514947/68071126-563c5c80-fd9d-11e9-9998-f3d0cf86f1cf.png)

**Comment by Prometal328** [comment] 2019-11-18 12:22
> I have cloned the whole code of 1.6 GB
> I used
> **cd build**
> **ant run**
> I managed to solve the issue by simply deleting Downloader.class in build/jre/bin.
> But now new Issue is apparently the same as [`5608`](https://github.com/processing/processing/issues/5608)
> And [solution](https://github.com/processing/processing/issues/5608#issuecomment-410597047) makes perfect sense, but I tried **git pull** and it's _Already up to date_
> 
> ![github](https://user-images.githubusercontent.com/46514947/68071126-563c5c80-fd9d-11e9-9998-f3d0cf86f1cf.png)

*Did you find any solution to this?* I have got the same problem.
 
I also tried building with ***Eclipse***, and it said that **there were some problems on the lines**:
- ***"310: The following error occurred while executing this line:"*** 
*(antcall target="${platform}-build"/>)* (This is line 310).
- ***"255: org.eclipse.ant.internal.launching.remote.AntSecurityException"***
 *(path="${jre.tgz.path}" />)* (This is line 255).

**Comment by benfry** [comment] 2020-09-15 00:31
Duplicate of #5827, but now working by offering a separate download.

**Closed by benfry** 2020-09-15 00:31 UTC
