### ISSUE TITLE
Processing 3.5.4  fails to start with Java NullpointerException in ContributionManager.java

### ISSUE THREAD

**Issue by michaelshiloh** [processing/processing#6159] opened 2021-02-12 11:35 UTC
![ContributionManager java_startupError](https://user-images.githubusercontent.com/952385/107763446-1443e980-6d48-11eb-9e94-77d836035e43.png)

 

## Expected Behavior

Expected processing application to start

## Current Behavior

Processing banner shows up for a few seconds, followed by a null pointer exception (image attached)

## Steps to Reproduce

1. Invoke Processing (Double-click on Processing icon)
2. Observe failure

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: mac book running MacOS version 11.1 
* Other information:
- I have fixed the previous 2 crashes by deleting sketchy .pde files (or Processing related files/folders), plus redownloading Processing. 
-  I successfully opened Processing two days ago. I have not used it since then. Today when I open Processing it crashes as described here.
- This seems to be very similar to issue #5823 with the following differences:
  - Issue #5823 was repaired in Processing 3.5.4; this problem exists in Processing 3.5.4
  - Issue #5823 occurred on fresh install; this problem is fixed by a fresh install, but appears after Processing is used a very few times
- The contribution manager has not been used or invoked at all

**Comment by frommeyerc** [comment] 2021-02-20 16:17
Hi, I stumbled upon this report as I was looking for the cause to the same issue reported by a student. I had a look into the source and it appears that (exactly) this issue will only occur if the `modes` folder is missing or not readable.
The issue you found basically surfaced the same issue in a different code location.

In order to work around this you need to make sure that Processing can use its preferences store. According to what I found on MacOS that should be located in a folder called `Processing` in the `~/Library` folder.
As you indicate that you are using MacOS 11.1 which is pretty new there might be issues with newly introduced _security_ measures that protect the folder.

First step would be to look for the modes folder and check:
* is it there
* what's the permissions

If all is well, probably s.o. with more insight into the preferences handling could help here. Else I'd try to (backup and) remove the complete `Processing` folder and run Processing again. It should recreate it on startup. After successful startup (let's hope that's what happens) have another look and find what Processing was actually able to create. If the modes folder is there and permissions look ok, try to stop and restart Processing to check it still works. Else report what has been created and have a look inside the still running Processing if there are error messages in the console or error view at the bottom of the window.

**Comment by michaelshiloh** [comment] 2021-02-20 16:24
Hi Christian, thanks for writing. Just yesterday my student fixed her
problem. Her explanation is a little cryptic but I think the main problem
is that she was running from the Downloads folder. If the Downloads folder
prevents the preferences store from being created, that would be consistent
with what you described.

I thank you for your detailed and clear explanation, and if she runs into
the problem again I will do as you suggest. Right now I'm reluctant to ask
her to make any changes or to run any experiments.

Thanks again,
Michael

**Comment by frommeyerc** [comment] 2021-02-20 16:39
UPDATE:
Looks like there is an additional indirection that I didn't catch at first glance. The modes folder is not located in the Processing folder in the ~/Library folder. That is just the location of the preferences file that contains the path to the sketchbook location which needs to contain the modes folder. A brief search indicates that on a Mac (I'm running Linux) that could possibly be located inside the Documents folder.

*The explanation with running from the Downloads folder sounds pretty reasonable as stuff downloaded from the Internet nowadays is treated with a lot more restrictions than it used to be the case...*

**Comment by michaelshiloh** [comment] 2021-02-20 16:44
Thanks again Christian. I too am on Linux and thus can't reproduce the issue.

**Comment by benfry** [comment] 2021-02-20 20:58
Duplicate of #6034. There's a fix in the 4.x releases but it's broken in 3.5.4.

**Closed by benfry** 2021-02-20 20:58 UTC
