### ISSUE TITLE
hit return on autocomplete adds a linebreak to editor

### ISSUE THREAD

**Issue by lukesturgeon** [processing/processing#3796] opened 2015-09-14 18:34 UTC
this is a frustraiting little issue. if I use the autocomplete feature and tap enter to select the variable, then the editor also adds a linebreak as if I'd hit return. so my code breaks and I have to reformat.

so autocomplete now makes my coding slower, not faster.

in Mac version. 3.0b5

**Comment by benfry** [comment] 2015-09-14 21:50
Duplicate of https://github.com/processing/processing/issues/3741

**Closed by benfry** 2015-09-14 21:50 UTC
