### ISSUE TITLE
Adding convenience methods for processing types

### ISSUE THREAD

**Issue by zats** [processing/processing#6134] opened 2020-12-13 00:57 UTC
Hey, long time listener, first time caller! 👋 

## Description

I noticed that I keep adding helpers introducing standard functions for the missing types, for example:

```
static public final double map(double value,
  double start1, double stop1,
  double start2, double stop2) {
...
```

or 

```
static public void translate(PVector p) {
...
```

etc

I am sure this question came up before, but I couldn't find it, is it worth adding these method to the standard library? I can put together a pull request if it's not against philosophy.

Thanks

**Comment by spencerstith** [comment] 2021-02-16 01:30
You might be able to just [create your own library](https://github.com/processing/processing/wiki/Library-Basics) for your personal use - I have done it for myself as well.
It isn't too hard.

**Comment by zats** [comment] 2021-02-16 14:03
Yup custom library is easy to make, I agree. I was curious if there's a value in just merging those upstream in the core since I finds myself using it every time and was curious if that's a common case or just me

**Comment by dzaima** [comment] 2021-02-16 14:24
`translate(PVector)` is quite common: https://github.com/processing/processing/issues/1897 (see all the references); https://github.com/processing/processing/pull/5926. Functions for doubles have also been requested every now and then, but are intentionally not added: https://github.com/processing/processing/issues/3244

**Comment by zats** [comment] 2021-02-16 15:15
Nice, thank you for the additional context. I knew I can't be the first one to come across this, just failed at search 🙂

**Comment by benfry** [comment] 2021-06-14 21:04
Closing as duplicate of https://github.com/processing/processing/issues/1897 which also has a longer answer.

**Closed by benfry** 2021-06-14 21:04 UTC
