### ISSUE TITLE
key == var and keyPressed don't work with long press

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#5175] opened 2017-07-14 15:48 UTC
The keyPressed problem seem back
Processing 3.3.5 / OS sierra 10.12.5

```
void draw() {
 println(count);
}
int count ;
void keyPressed() { 
  if(key == 'a') count++;; // stop work with then after long press 
  // count++;; // work fine 
  // if(key == CODED) if (keyCode == UP) count++; // work fine
}
```

**Comment by StanLepunK** [comment] 2017-07-14 16:03
with `boolean`variable that's work fine

```
void draw() {
 println(count);
 println(bool);
}
int count ;
boolean bool ;
void keyPressed() { 
  if(key == 'a') count++;; // stop work with then after long press 
  // count++;; // work fine 
  // if(key == CODED) if (keyCode == UP) count++; // work fine
  
  
  // if(key == 'z') bool = !bool; // work fine 
  // bool = !bool; // work fine 
  //if(key == CODED) if (keyCode == UP) bool = !bool; // work fine
}
```

**Comment by JakubValtar** [comment] 2017-07-15 14:15
I'm sorry, I don't understand the problem. What do you mean by "stop work with then after long press"?

It works well on Windows. Does this help? https://github.com/processing/processing/wiki/Troubleshooting#key-repeat-on-macos-sierra

**Comment by StanLepunK** [comment] 2017-07-16 11:14
Perfect, that's fix the bug. Thx.
I mean by "stop work with then after long press", the bug come when there is long press key, and after that the single press key don't work anymore. Sorry for my poor and very english...very frenglish :)

**Comment by JakubValtar** [comment] 2017-07-17 17:44
Great, I'm going to close this :)

**Closed by JakubValtar** 2017-07-17 17:44 UTC

**Comment by JakubValtar** [comment] 2017-07-17 17:46
Duplicate of #4952
