### ISSUE TITLE
Visual glitches in the editor with Windows 10

### ISSUE THREAD

**Issue by apdonim** [processing/processing#4178] opened 2015-11-30 18:43 UTC
Ever since I switched to a windows 10 computer, the editor keeps glitching.
The text keeps overlapping each other, and i see multiple task bars throughout the screen.
You might have not have updated the editor for windows 10. I just want to know if the computer is at fault or the program itself is not there yet.

**Comment by dhester62** [comment] 2016-01-05 21:13
My system is windows 10 64bit home and I have the same problem. I have tried using the troubleshooting wizard but problem persisits

**Comment by JakubValtar** [comment] 2016-02-29 01:42
Could it be caused by the JIT bug #4079 (and thus already fixed/worked around)?

**Comment by ry00000** [comment] 2016-12-11 16:35
I have this problem too, and no, it hasn't been fixed @JakubValtar

**Comment by atnbueno** [comment] 2017-01-15 19:12
In case it helps:
I just downloaded Processing 3.2.3 and in my Windows 10 I had **glitches in the editor**. Not frozen, but it was impossible to keep working. A windows redraw (for example, a minimize-restore cycle) fixed it only for a second. For a longer fix (seconds, never minutes) I had to restart Processing. 

I managed to make it work by running **processing.exe** in "Windows 8 mode" (_processing.exe -> Properties -> Compatibility -> Compatibility mode_). Zero problems since then 😀

**Comment by glasscanvas** [comment] 2017-04-15 09:25
Same issue. here are some examples using the Microsoft Surface Studio screen capture, 
Window 10 Pros 10.0.15063 build 15063
Processing 3.3

I am seeing that the examples and the show usage panels have overlapping text lines making them hard to read. Adjusting the font does not help on these panels. Interface scale defaulted to 200%. Setting it to 100% and restarting processing does not solve the issue with the two panels. The main IDE window does scale accordingly. Display density reports a 1. I definitely willing to test a solution or try to fix code if I can get some help in the right direction. 

![processing crunched lines annotated](https://cloud.githubusercontent.com/assets/12136395/25062541/ea54ac0a-219b-11e7-8275-ec8453d40a0a.png)

**Comment by benfry** [comment] 2017-04-21 22:04
This should be fixed in Processing 3.3. If not, please file a new bug.

**Closed by benfry** 2017-04-21 22:04 UTC
Labels: windows
