### ISSUE TITLE
Scaling the Processing Editor window for HiDPI displays

### ISSUE THREAD

**Issue by steve2718** [processing/processing#4420] opened 2016-04-21 04:23 UTC
One of Windows 8/8.1 Achilles' heels is (in)appropriately scaling windows on high resolution displays. The Arduino IDE has a preference called "Interface scale", but I can't seem to find a way to scale the editor in Processing.

![processing_editor_scaling](https://cloud.githubusercontent.com/assets/18587573/14697940/db508bd0-073d-11e6-9216-bc75a721fb7d.JPG)

**Comment by steve2718** [comment] 2016-04-21 16:54
I tried to see if there might be undocumented properties in "preferences.txt", such as editor.scaling=xxx, editor.scale=xxx, etc. But that didn't work.
Here are some images of the Aduino IDE. The scaling property in preferences is really handy.
![arduinoide_w_scaling](https://cloud.githubusercontent.com/assets/18587573/14717511/cb05adbe-07a6-11e6-83e3-70ea98d2ef73.JPG)
![arduino_prefs_scaling](https://cloud.githubusercontent.com/assets/18587573/14717526/d94c16a6-07a6-11e6-80c7-df761012d281.JPG)

**Comment by benfry** [comment] 2016-05-08 16:58
Duplicate of https://github.com/processing/processing/issues/2411

The Arduino folks have made no effort to help us implement this, and nobody's taken the time to fix it themselves, so it's not fixed in Processing.

**Closed by benfry** 2016-05-08 16:58 UTC
