### ISSUE TITLE
implement support for SVG gradients from Inkscape

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1180] opened 2013-02-10 17:22 UTC
_Original author: paolo.pe...@gmail.com (July 23, 2012 15:25:02)_

Hello,
Processing 2.0a6 does very well with gradient fills in SVG files made in Illustrator but it doesn't seem to handle gradients from Inkscape.

Attached a small sketch with SVG files in different formats. Thanks and keep on the good work,
P.

_Original issue: http://code.google.com/p/processing/issues/detail?id=1142_

**Comment by JakubValtar** [comment] 2015-08-06 20:37
This may be difficult, I don't think we can implement this in full. Gradients would have to be tessellated separately to place vertices at key locations to define the gradients, but still we can get only linear interpolation between vertices. Maybe we could implement at least some approximate version?

**Comment by benfry** [comment] 2015-08-11 18:47
Duplicate of #373.

**Closed by benfry** 2015-08-11 18:47 UTC
Labels: enhancement, imported, low, pshape, revised
