### ISSUE TITLE
Auto Format adds extra indent

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1041] opened 2013-02-10 17:13 UTC
_Original author: mkmori...@gmail.com (February 25, 2012 05:47:28)_

Another MINOR (but weird) Auto Format thing--even more trivial than my &quot;} else {&quot; thing, Issue 325....

Copy &amp; paste the bit of code below--including curly brackets--into the IDE and Auto Format: The &quot;camera.beginHUD();&quot; line will have an extra indent! (1.5.1 &amp; 2.0a4)

FWIW!

{ //Must be at least one indent already....
  box(a); //intervening comment--comments could all be on same line with code....
  //blah blah
  //blah blah a

    box(b); //Autoformat: Code with &quot;a&quot; near the end--&quot;);&quot; doesn't matter--followed by comments ending in &quot;a&quot; plus one or more blank lines force an extra indent here!
  box(c);
  //Any matching alphanumeric character seems to do it....
}

_Original issue: http://code.google.com/p/processing/issues/detail?id=1003_

**Comment by datguy** [comment] 2015-01-09 17:55
This appears to be fixed in 2.2.1

**Comment by GKFX** [comment] 2015-01-09 18:19
OK, let me take a look.

**Comment by GKFX** [comment] 2015-01-09 18:23
@datguy I disagree. The bug still appears on my system.

**Comment by datguy** [comment] 2015-01-09 18:42
@GKFX What OS are you using? Can you give me steps to reproduce it?

I tried the minimal case that you provided - using 2.2.1 on Windows 7 - and it looked fine to me.  But maybe I'm doing it differently or not looking at the right thing.

**Comment by GKFX** [comment] 2015-01-09 18:55
I'm on Ubuntu 14.04, but surely this is OS-independent: it's just manipulating a string. The problem is that the `b;` should move back two spaces, to be in line with the `q;`, but it doesn't. I trigger the bug by the simple method of pasting it in and pressing `Ctrl`+`T`.

**Comment by joelmoniz** [comment] 2015-01-09 19:13
This problem still occurs for me as well, on Windows 8.1. 

NB: Both the new line and the comment in the minimal case are essential for this bug to show, as otherwise, the auto-format works fine.

**Comment by GKFX** [comment] 2015-01-09 19:15
I have fixed this bug -- #3002 contained a regression, but I was able to fix it.

**Comment by datguy** [comment] 2015-01-09 19:38
Now I understand why I didn't see it.  I was expecting something to move when I used autoformat (as the issue title suggests), but the minimal case already had the extra indentation.

**Closed** 2015-01-19 20:27 UTC
Labels: help, imported
