### ISSUE TITLE
Disable texture linear/bilinear interpolation in the GL renderers

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing#1272] opened 2013-02-10 17:29 UTC
_Original author: andres.c...@gmail.com (September 11, 2012 21:35:51)_

Sometimes people want to disable linear/bilinear sampling in order to avoid blurriness associated to upscaling an image:

https://forum.processing.org/topic/disable-antialiasing-on-images-p3d-processing-2-0a6

2.0b includes the hint to disable mipmaps, but even then, the textures will still be linearly interpolated. In some cases, it might make sense to disable interpolation at all and just use point (nearest) sampling. 

_Original issue: http://code.google.com/p/processing/issues/detail?id=1234_

**Comment by codeanticode** [comment] 2015-06-01 03:38
Added a section in the wiki on [Advanced OpenGL](https://github.com/processing/processing/wiki/Advanced-OpenGL) chapter of the wiki on how to change the filtering mode. Unless we decide to add a new function to PApplet to set the filtering mode, I think we should close this issue, since not having such function means that we don't "officially" support the feature.

**Comment by benfry** [comment] 2015-06-01 12:18
When `noSmooth()` is called, does it switch image smoothing to nearest neighbor?

**Comment by codeanticode** [comment] 2015-06-01 13:00
no, but we could do that.

**Comment by benfry** [comment] 2015-06-01 21:50
@reas I think this is how you want it behaving, right? That `noSmooth()` makes scaled images pixelated?

**Comment by codeanticode** [comment] 2015-06-01 22:50
In the OpenGL renderer, scene antialiasing (smooth/noSmooth) and texture filtering/mipmapping are really independent things (although antialiasing probably affects image smoothing). To have noSmooth() setting nearest sampling, besides disabling antialiasing, connects these two in a way that an advanced user might find surprising, but I think makes sense in the context of the Processing API, and also for consistency with the java renderers. 

I implemented this behavior with https://github.com/processing/processing/commit/1b1651105cc76832bc069cbba4dd333ed90c9e25. We can close this issue if you all agree this is the right way to handle texture sampling.

**Comment by benfry** [comment] 2015-06-03 17:41
@REAS this is the discussion we've had in the past about a separate `imageSmooth()` function. I can't remember where we wound up on this... I think we discussed it, didn't have a perfect solution, didn't want to add API, and wound up forgetting about it.

**Comment by REAS** [comment] 2015-06-04 07:35
I think maintaining the behavior of noSmooth() applying to images to keep the pixels crisp is a good solution -- mostly because it is how it has been working and I'm usually not in favor of adding new functions. I'm open to an argument counter to this.

**Comment by benfry** [comment] 2015-06-04 15:59
The issue is that `smooth()` and `noSmooth()` can't be called mid-draw with OpenGL (and probably JavaFX). The smoothing is a property of the rendering surface so it can only be set once in the sketch. So the concern is that you may want to enable/disable image smoothing separately from that (and it's a runtime thing, not a property of the surface). 

But I think this is why we punted—maybe just too much of an edge case and not worth a new function to support it across renderers.

**Comment by REAS** [comment] 2015-06-04 16:12
With that info, I do prefer to add a new function, do we need to follow the model of imageSmooth(), noImageSmooth()? Or is this something that could/should be covered with an example instead?

**Comment by benfry** [comment] 2015-06-04 16:43
`smoothMode()`! 

`hint(DISABLE_IMAGE_SMOOTHING)` in line with it being an edge case?

**Comment by JakubValtar** [comment] 2015-06-04 16:44
Hi all, in my opinion changing the functionality of smooth() is a terrible idea (sorry).

Smooth() had always been about anti-aliasing, where more is better (if you have the performance). NoSmooth() often serves as an emergency performance boost which sacrifices the visual quality on the edges, but enables you to run the sketch at reasonable frame rate. Texture interpolation is a completely different thing, used mostly for artistic purposes or very specific shader techniques. They are orthogonal, so they need separate functions.

Personally I would use nearest neighbor interpolation and anti-aliasing together most of the time. Conversely, please don't force people who need demanding real-time rendering to have pixelated textures.

**Comment by benfry** [comment] 2015-06-04 18:22
Changing how `smooth()` behaves is off the table—we're just trying to sort out whether we support this image-specific scenario.

**Comment by REAS** [comment] 2015-06-05 01:27
This is sorted out now. We decided to return to the original functionality of smooth(), to set the "smoothing" of geometry and images together. If people want a different behavior, they can use syntax like this: 

```
hint(DISABLE_TEXTURE_MIPMAPS);
((PGraphicsOpenGL)g).textureSampling(2);
```

**Closed by REAS** 2015-06-05 01:27 UTC
Labels: enhancement, imported, opengl
