### ISSUE TITLE
variables window mess

### ISSUE THREAD

**Issue by lpdunwell** [processing/processing#4285] opened 2016-02-10 11:58 UTC
the variables window in debugging mode seems to try and sort the variables when clicking on the headers, but it ends up in a non-alphabetic mess anyway

**Comment by PARAG00991** [comment] 2016-02-26 18:00
@ipdunwell, I'm unable to reproduce the bug. Could you provide some other info like the code with which such behavior is coming?

**Comment by Akarshit** [comment] 2016-02-28 06:39
@lpdunwell The current order for sorting is capital  letter < small letter.
Like in the example below `Processing` < `Radius` < `arrowImage` < `choseFunction`  ...

![screenshot from 2016-02-28 11 59 14](https://cloud.githubusercontent.com/assets/7762605/13377856/6e0d0984-de13-11e5-865b-20bd5e2c7412.png)
![screenshot from 2016-02-28 11 58 47](https://cloud.githubusercontent.com/assets/7762605/13377857/704a6282-de13-11e5-9e10-a7ab7ff0e150.png)

If you are seeing a different order from the above, then it would be great if you could provide us the code that is causing such behavior.

**Comment by benfry** [comment] 2016-05-08 17:06
Closing; no follow-up.

**Closed by benfry** 2016-05-08 17:06 UTC
