### ISSUE TITLE
crashing on bootup 

### ISSUE THREAD

**Issue by jason-tung** [processing/processing#5544] opened 2018-06-17 05:36 UTC
## Description

When I open processing (whether it be from the installation directory or elsewhere) it crashes and gives me an error message.

![image](https://user-images.githubusercontent.com/33106747/41505079-8636a226-71ce-11e8-9178-3bd878172720.png)

## Expected Behavior

Processing to launch.

Processing launches.

## Current Behavior

Processing does not open and instead throws this error message.

## Steps to Reproduce

1. launch processing
2. get crash message
3. close crash message
4. uninstall processing
5. reinstall processing
6. repeat 1-5

1.
2.
3.

## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: Windows 8.1
* Other information:

**Comment by julianrusso92** [comment] 2018-06-17 15:33
I have the same problem

**Comment by benfry** [comment] 2018-07-19 22:38
Closing as duplicate of https://github.com/processing/processing/issues/5537

**Closed by benfry** 2018-07-19 22:38 UTC
