### ISSUE TITLE
PGraphics translate method should accept PVector

### ISSUE THREAD

**Issue by cansik** [processing/processing#5220] opened 2017-08-16 10:18 UTC
I propose to add a new method overload to `PGraphics.translate()` which accepts a PVector. It is very cumbersome to write the following line of code:

```java
PVector myVector = new PVector();

g.beginDraw();
g.translate(myVector.x, myVector.y, myVector.z);
g.endDraw();
```

And it would be so much simpler with following code:

```java
PVector myVector = new PVector();

g.beginDraw();
g.translate(myVector);
g.endDraw();
```

The method body could look like the following (very simple):

```java
void translate(PVector vector)
{
    translate(vector.x, vector.y, vector.z);
}
```

I know it is a very small change, but this is always something I really find annoying. Currently I am writing a lot of processing with Kotlin and use extension methods to add such overloads, but that is not possible in pain old java.

```kotlin
fun PGraphics.translate(vector: PVector) {
    this.translate(vector.x, vector.y, vector.z)
}
```

Is there a reason why this has not been added to the core yet?

**Comment by jeremydouglass** [comment] 2017-08-18 16:30
I am not a core developer, but I have also encountered several times when I wanted to use a vector directly instead of unpacking it. I think this suggestion has been discussed in other issues before.

If I recall correctly, one issue for the code base might be that this is a large set of overloads in order to be consistent -- so for example if PGraphics.translate(vector) why not scale(vector), rect(vector, vector), ... line(), vertex() etc. etc.

I'm not arguing against it -- I would like the feature -- I'm just pointing out that it should probably be done consistently and not piece-wise.

**Comment by cansik** [comment] 2017-08-19 07:58
@jeremydouglass Yes you are right, if we change the `translate` method, we also have to change the others. But I do not see something against it. It would really help and I could not find an issue about that (open or closed).

The only reason I could imagine is, that PVector is 3D, but often used as 2D vector. So it is not specifically defined, if only `X` and `Y` are taken as parameter, or`X`, `Y`, `Z`.

So it would be nice to here a comment from a core developer.

**Comment by StanLepunK** [comment] 2017-08-19 08:48
@cansik I had a same idea like you and a same opinion than @jeremydouglass it's a huge work for gap not really good, so I make the job by myself and write my Vector class and make methods like you want :) https://github.com/StanLepunK/Rope/blob/master/Guide/Vector_method_from_P5_to_P5.md it's easy to add in your sketch if you want use !

**Comment by cansik** [comment] 2017-08-20 14:57
@StanLepunK I think it is not a good idea to write your own vector class (as discussed in https://github.com/processing/processing/issues/1779) due compatibility reasons. I currently have a solution for my "problem" with the extension methods in Kotlin. But I think this should be something for everyone.

**Comment by jeremydouglass** [comment] 2017-08-20 17:06
As I recalled, this is a duplicate of past closed issue https://github.com/processing/processing/issues/1897

This won't be supported, but one suggestion in that thread is to create a library.

**Comment by cansik** [comment] 2017-08-20 21:50
@jeremydouglass Ok, but writing a library is not the same, because then we have to call `translate` on another object, which is not really helpful. Would it be a help, if I would create a pull request and add those methods?

I wrote a small script to find all methods which take three `float` arguments. You can run it in the root directory of the processing repository.

```bash
i=0
for f in $(find . -name '*.java'); 
do
	while read -r line ; do
	    echo "$f: $line"
	    ((i++))
	done < <(cat $f | grep -o '[a-zA-Z0-9]\+ [a-zA-Z0-9]\+(float [a-zA-Z0-9]\+, float [a-zA-Z0-9]\+, float [a-zA-Z0-9]\+)')
done
echo "Found: $i"
```

My script found **170** methods which could be overloaded with a `PVector` argument. So it would also be possible to write a script to create those 170 new methods (or even more). If you think it could work, I would also try to find methods like `line`, which accepts multiple `X` & `Y` arguments.

Here is the full list: https://gist.github.com/cansik/8744ca0fcde27a664d4c735931d11d8d

**Comment by jeremydouglass** [comment] 2017-08-21 03:11
It sounds like you are motivated to develop a systematic pull request for PVectors!

But -- before developing a pull request I really recommend asking one of the core developers (from previous threads) whether they would accept such a pull.

If they don't want the complexity added to the code base then there is no reason to write it (unless you want your own fork of Processing).

**Comment by benfry** [comment] 2021-06-14 15:16
Closing as duplicate of #1897 where I've added a few more notes.

**Closed** 2021-06-14 21:19 UTC
Labels: duplicate
