### ISSUE TITLE
"Undo" shortcut has unintended formatting effects when held down

### ISSUE THREAD

**Issue by serebit** [processing/processing#3984] opened 2015-10-10 18:51 UTC
These formatting effects range from including everything on one line to fracturing certain functions.

**Comment by GKFX** [comment] 2015-10-11 19:01
I can't reproduce it. What exactly did you do? I:
* Made a bunch of random changes, over many lines, in an existing file, changing some lines multiple times.
* Held `Ctrl`+`Z`, then `Ctrl`+`Shift`+`Z`,  then `Ctrl`+`Z`. Everything was undone, redone, and undone again in the normal way.
* Double-checked with a diff. Undo did no harm whatsoever to the file.

So what did you do differently, if anything? And do you find it happens every time? Also, what is your version number (and/or commit if you got Processing from git) and operating system?

**Comment by gingerdeadshot** [comment] 2015-10-11 19:03
Version 3.0 alpha, Mac OS X. I'll try to reproduce it and see what happens.

**Comment by GKFX** [comment] 2015-10-12 17:01
I'm on Linux. I tried alphas 1 & 11, and got nothing. Sorry!

**Comment by jeremydouglass** [comment] 2019-12-20 17:10
I believe this can be closed as referring to the same problem documented in #4775

**Closed** 2019-12-20 20:31 UTC
