### ISSUE TITLE
Trouble with Processing new beta version

### ISSUE THREAD

**Issue by khbyoyo** [processing/processing#3616] opened 2015-08-15 06:30 UTC
I'm running newest beta version of Processing on Windows 10 machine, and new version is bothering me too MUCH! Cursor is not on the right position to write code. I think every time the cursor move 2 spaces right from the appropriate position. And I'm not sure when did size() function become mandatory to have integer number."Use only numbers (not variables) for the size() command. Read the size() reference for more details." WTH Having variables as parameters is so useful though..

**Comment by aengelke** [comment] 2015-08-15 09:09
You can use size in the new `void settings()` method, where you can use variables. Internally, the size statement is copied into the settings method. 

https://processing.org/reference/settings_.html
https://github.com/processing/processing/wiki/Changes-in-3.0#new

**Comment by benfry** [comment] 2015-08-15 12:54
Closing... This is an unhelpful rant, not a bug report. 

How to troubleshoot: https://github.com/processing/processing/wiki/Troubleshooting

**Closed by benfry** 2015-08-15 12:54 UTC
