### ISSUE TITLE
method launch() does not work with my processing .exe

### ISSUE THREAD

**Issue by ClaraBellinMMI** [processing/processing#4937] opened 2017-02-28 08:52 UTC
I'm using the method launch() to open an exe I exported from processing but it does not work, whereas it works with google.exe etc..   I'm sure that I use the good path and I don't know what to do.. 

Here is my code:

```
//click detection
void mousePressed() {
 
  if(mouseX > 10 && mouseX < 360 && mouseY > 10 && mouseY < 110){
     launch("C:/Program Files (x86)/Google/Chrome/Application/chrome.exe");
  //   println("open chrome");
    }
   
   if(mouseX > 10 && mouseX < 360 && mouseY > 160 && mouseY < 260){
     // launch(sketchPath("data/FinalV6BigScreen.exe"));
      launch(sketchPath("data/FinalV6BigScreen.exe"));
     // fill(200,200,152); 
     // println("my processing exe");
   }
   
   if(mouseX > 10 && mouseX < 360 && mouseY > 310 && mouseY < 410){
   exec("notepad.exe");
  // fill(200,100,200); 
}
}
```

**Comment by gohai** [comment] 2017-02-28 09:11
Duplicate of #4869

**Closed by gohai** 2017-02-28 09:11 UTC
