### ISSUE TITLE
Low resolution icon on Linux

### ISSUE THREAD

**Issue by macarena** [processing/processing#5618] opened 2018-08-11 17:21 UTC
## Description
A low resolution icon is displayed instead of the high quality one available on dock (using Plank, but I believe it's unrelated to it). I don't know about the icon on common task bars, but maybe they have the same problem though imperceptive...

## Current Behavior
When starting processing, the launcher/splash screen has a nice icon on dock. But as soon as the main window comes up with an empty sketch, it loads a new icon on dock with low resolution.

## Steps to Reproduce
Just run PDE using a dock

## Your Environment
* Processing version: 3.4
* Operating System and OS version: Linux Mint 19
* Dock used: Plank 0.11.4

![splash icon](https://user-images.githubusercontent.com/79822/43994341-b01adaf2-9d71-11e8-9032-66c6ee29a332.png)

![splah vs sketch 1](https://user-images.githubusercontent.com/79822/43994339-afdd94bc-9d71-11e8-81bf-c45f1a8ecdfe.png)

![splah vs sketch 2](https://user-images.githubusercontent.com/79822/43994340-affca726-9d71-11e8-9d16-a6d71372c9ce.png)

![sketch icon](https://user-images.githubusercontent.com/79822/43994338-afbb735a-9d71-11e8-8703-a86cdd050750.png)

**Comment by liquid600pgm** [comment] 2018-09-29 17:44
I can't reproduce this on Ubuntu Dock, the icon appears normal.
![image](https://user-images.githubusercontent.com/16415678/46248884-fd72f580-c41f-11e8-8807-51b3e4aeebfc.png)

**Comment by calebccff** [comment] 2018-12-06 08:14
This is an issue with your installation, go to /use/share/applications and edit Processing.desktop.

Replace the icon path with a path to a higher resolution icon (there's a few somewhere in the Processing directory)

**Comment by GRsni** [comment] 2019-05-31 19:36
@macarena Did you manage to solve the issue? If so, please, close this thread to avoid clutter in the issues page. Thank you.

**Closed** 2019-10-16 11:14 UTC
