### ISSUE TITLE
lots of red error text in the console when closing P3D skech

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3520] opened 2015-07-30 14:49 UTC
3.0a11 Mac OS X

Normally I close with command + q but today I noticed when closing with the red icon it spits a lot off uglyness:

finishLifecycleAction(com.jogamp.opengl.util.FPSAnimator$4): ++++++ timeout reached ++++++ AWT-AppKit
finishLifecycleAction(com.jogamp.opengl.util.FPSAnimator$4): OK false- pollPeriod 17, blocking true -> res false, waited 1001/1000 - AWT-AppKit
 - com.jogamp.opengl.util.FPSAnimator[started true, animating true, paused true, drawable 1, totals[dt 0, frames 69, fps 0.0], modeBits 1, init'ed true, animThread Thread[main-FPSAWTAnimator#00-Timer0,5,main], exclCtxThread false(null)]
    [2]: com.jogamp.opengl.util.AnimatorBase.finishLifecycleAction(AnimatorBase.java:630)
    [3]: com.jogamp.opengl.util.FPSAnimator.pause(FPSAnimator.java:363)
    [4]: jogamp.opengl.GLAutoDrawableBase.destroyAvoidAwareOfLocking(GLAutoDrawableBase.java:320)
    [5]: jogamp.opengl.GLAutoDrawableBase.defaultWindowDestroyNotifyOp(GLAutoDrawableBase.java:284)
    [6]: com.jogamp.newt.opengl.GLWindow.access$000(GLWindow.java:119)
    [7]: com.jogamp.newt.opengl.GLWindow$1.run(GLWindow.java:131)
    [8]: jogamp.newt.WindowImpl.windowDestroyNotify(WindowImpl.java:3932)
Caught ignored RuntimeException: java.lang.RuntimeException: Waited 5000ms for: <1113a447, 110f9ed>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.macosx_nil-1-EDT-1> on thread AWT-AppKit
    [0]: jogamp.newt.DefaultEDTUtil.invokeImpl(DefaultEDTUtil.java:249)
    [1]: jogamp.newt.DefaultEDTUtil.invoke(DefaultEDTUtil.java:163)
    [2]: jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:427)
    [3]: jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2133)
    [4]: jogamp.newt.WindowImpl.destroy(WindowImpl.java:1217)
    [5]: com.jogamp.newt.opengl.GLWindow.destroy(GLWindow.java:489)
    [6]: jogamp.opengl.GLAutoDrawableBase.destroyAvoidAwareOfLocking(GLAutoDrawableBase.java:321)
    [7]: jogamp.opengl.GLAutoDrawableBase.defaultWindowDestroyNotifyOp(GLAutoDrawableBase.java:284)
    [8]: com.jogamp.newt.opengl.GLWindow.access$000(GLWindow.java:119)
    [9]: com.jogamp.newt.opengl.GLWindow$1.run(GLWindow.java:131)
    [10]: jogamp.newt.WindowImpl.windowDestroyNotify(WindowImpl.java:3932)
Caused[1] by RuntimeException: Waited 5000ms for: <1113a447, 110f9ed>[count 2, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.macosx_nil-1-EDT-1> on thread AWT-AppKit
    [0]: jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
    [1]: jogamp.newt.WindowImpl$1.run(WindowImpl.java:1111)
    [2]: com.jogamp.common.util.RunnableTask.run(RunnableTask.java:150)
    [3]: jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:372)

**Comment by codeanticode** [comment] 2015-08-04 22:41
I tested 3.0 alpha11 on OS X 10.9.5 and the latest revision from the repo and did not observe any error messages when closing the sketch, either with cmd+q or the stop button.

What OS X version are you on?

**Comment by clankill3r** [comment] 2015-08-05 12:25
OS X 10.10.4

Strange, the error is gone for me. I will let you know once I have it again.

**Comment by codeanticode** [comment] 2015-08-05 13:32
ok, I will close it since cannot reproduce. We can re-open later.

**Closed by codeanticode** 2015-08-05 13:32 UTC
Labels: macosx, opengl

**Comment by JakubValtar** [comment] 2015-08-18 18:18
Got this one today on Windows 8.1 in Examples/Basics/Color/ColorVariables with P2D renderer. I was closing the window with X close button in the window title bar. Did not manage to reproduce it.
```
finishLifecycleAction(com.jogamp.opengl.util.FPSAnimator$4): ++++++ timeout reached ++++++ main-Display-.windows_nil-1-EDT-1
finishLifecycleAction(com.jogamp.opengl.util.FPSAnimator$4): OK false- pollPeriod 31, blocking true -> res false, waited 1000/1000 - main-Display-.windows_nil-1-EDT-1
 - com.jogamp.opengl.util.FPSAnimator[started true, animating true, paused true, drawable 1, totals[dt 0, frames 1, fps 0.0], modeBits 1, init'ed true, animThread Thread[main-FPSAWTAnimator#00-Timer0,5,main], exclCtxThread false(null)]
    [2]: com.jogamp.opengl.util.AnimatorBase.finishLifecycleAction(AnimatorBase.java:630)
    [3]: com.jogamp.opengl.util.FPSAnimator.pause(FPSAnimator.java:363)
    [4]: jogamp.opengl.GLAutoDrawableBase.destroyAvoidAwareOfLocking(GLAutoDrawableBase.java:320)
    [5]: jogamp.opengl.GLAutoDrawableBase.defaultWindowDestroyNotifyOp(GLAutoDrawableBase.java:284)
    [6]: com.jogamp.newt.opengl.GLWindow.access$000(GLWindow.java:119)
    [7]: com.jogamp.newt.opengl.GLWindow$1.run(GLWindow.java:131)
    [8]: jogamp.newt.WindowImpl.windowDestroyNotify(WindowImpl.java:3932)
    [9]: jogamp.newt.driver.windows.DisplayDriver.DispatchMessages0(Native Method)
    [10]: jogamp.newt.driver.windows.DisplayDriver.dispatchMessagesNative(DisplayDriver.java:120)
    [11]: jogamp.newt.DisplayImpl.dispatchMessages(DisplayImpl.java:734)
    [12]: jogamp.newt.DisplayImpl$7.run(DisplayImpl.java:657)
    [13]: jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:344)

```

**Comment by clankill3r** [comment] 2015-08-26 13:19
Ok, I was able to reproduce. After a shitload of work I could get it to the following bare minimum:
It happens for me like 80% of the times.

Mac OS X latest
Processing 3.b5

````java
import processing.core.PApplet;
import java.awt.*;


public class RedTextOnClose extends PApplet {

    public static void main(String[] args) {
        PApplet.main("util.datastructure.RedTextOnClose", args);
    }

    @Override
    public void settings() {
        size(512, 512, P3D);
    }

    public void setup() {
        registerMethod("pre", this);
    }

    public void pre() {
        Point mouse = MouseInfo.getPointerInfo().getLocation();
    }
}
````

**Comment by benfry** [comment] 2015-08-26 13:30
That's calling an AWT method (MouseInfo) inside the rendering loop, which is a terrible idea because you'll have AWT kick off its own thread and fight with the OpenGL rendering thread. Try using `post()` instead of `pre()`. 

The issue you're having is about unhappiness in the rendering thread, but the example you're providing causes it 80% of the time because it's a good way to guarantee that something will go wrong, not an indication of something we can/should fix.

**Comment by clankill3r** [comment] 2015-08-26 13:36
@benfry thanks!

It seems OpenGL is becoming a teenager with the fighting cause I never had this before :)
I still wonder what the cause for JakubValtar is but I'm glad this one is tackled.

thanks

**Comment by clankill3r** [comment] 2015-08-26 13:49
@benfry @codeanticode 

Little update:

Pre or post did not matter.
I can also have it in draw, it still gives the problem when closing.

Did there something change in closing the OpenGL thread for Processing 3? I just tried the same code for like 25 times in Processing 221 and it didn't give a problem once.


````
import java.awt.*;

public void settings() {
  size(512, 512, P3D);
}

public void setup() {
}

public void draw() {
   Point mouse = MouseInfo.getPointerInfo().getLocation();
}
````

**Comment by benfry** [comment] 2015-08-26 15:04
Yes, just about everything has changed with the GL thread between 2 and 3. [Here's some background.](https://github.com/processing/processing/blob/master/core/README.md)
