### ISSUE TITLE
Virus detected in Win 32/64 versions. After cleaning, can't launch application

### ISSUE THREAD

**Issue by BuckStarchaser** [processing/processing#5374] opened 2018-01-17 21:58 UTC
## Description

processing-3.3.6-windows64.zip and processing-3.3.6-windows32.zip fail virus scan on extraction, and processing.exe crashes with error message on start.

## Expected Behavior

Expected it to pass the virus check, install, run

same as above
## Current Behavior

http://download.processing.org/processing-3.3.6-windows64.zip and http://download.processing.org/processing-3.3.6-windows32.zip result in .ZIP files that contain what is described by Malwarebytes and Microsoft Security Essentials as "TrojanDownloader:Java/Vigorf.A"
## Steps to Reproduce

1. download windows version of Processing
2. extract to folder
3. virus scanner finds and removes "TrojanDownloader:Java/Vigorf.A" from "...\AppData\Local\Temp\Rar$DRa0.176\processing-3.3.6\core\library\core.jar"
4. attempt to launch processing application
5. large error box with "OK" button. Many lines of error information and "17 more" but information is not interactive (can't copy/paste, can't see the "17 more" items). Error box is titled "It was not meant to be". First couple lines are "java.lang.NoClassDefFoundError: processing/core/PApplet" "at processing.app.Base.createAndShowGUI(Base.java:133)" "at processing.app.Base.access$0(Base.java:129)" ...and so on.
6. hitting "OK" button exits the program

1. I am a beginner novice and have no helpful code recommendations 
2.
3.

## Your Environment

I really don't know how to answer this, other than Windows7 64bit
 

* Processing version: 3.3.6 (32 and 64 bit versions)
* Operating System and OS version: Windows7 Home Premium 64bit
* Other information:

## Possible Causes / Solutions

Possible cause: Virus signature detected in file necessary for operation. File is removed by virus scanner. Program doesn't fully launch without that file. Program terminates with error.

![image](https://user-images.githubusercontent.com/29181458/35069212-89fbc096-fba7-11e7-97c7-474957e0ee83.png)

**Comment by BuckStarchaser** [comment] 2018-01-17 22:04
![image](https://user-images.githubusercontent.com/29181458/35069476-42b680d0-fba8-11e7-948b-26e5bcd85d6c.png)

**Comment by tolkanabroski** [comment] 2018-01-17 22:42
Hello 

I'm using Windows too, no Problems here.

Please clean up all of the previous Installation data 

##### C:\Users\[user_name]\AppData\Roaming\Processing
+ hit WinKey +R 
+ copy paste **shell:AppData\Processing** +hit Enter
+ delete folder content
download Processing
+ hit WinKey +R 
+ copy paste **shell:UsersFilesFolder** +hit Enter
+ and extract Processing-X-X-X.zip 

When it still dont work, 
make sure you right click to open the Contex Menü > Security Tab > Make sure you have given full rights to the user. 

Workaround 2:
Just create a new Folder and add exceptions for files or folders in your AntiVirus program. 

The Problem here is that JOGL needs to extract a simpel Window creation .exe befor launch to see if the folder is writable. And unfortunately the WinMain entry point in this program is exactly how many Viruses works. Since Windows 7 the especially [Windows]\ProgramFiles Folders has limited read write access.

related: 
https://github.com/processing/processing/issues/5329  
https://github.com/processing/processing/issues/4783  

Workaround 3:
recompile JOGL without this behavior.

**Comment by benfry** [comment] 2018-01-17 23:18
Closing as duplicate of https://github.com/processing/processing/issues/5329

**Closed by benfry** 2018-01-17 23:18 UTC
