### ISSUE TITLE
strokes in P3D

### ISSUE THREAD

**Issue by markusand** [processing/processing#4686] opened 2016-10-01 22:53 UTC
When using P3D, all strokes overlaps other shapes, even if these are drawn after. If I change to P2D it works OK.

I found a solution it was supposed to work in this post, but it seems not to work in Processing 3:
https://forum.processing.org/one/topic/shapes-and-strokes-on-a-plane-in-p3d-opengl.html

Is there any solution for Processing 3?

**Comment by gohai** [comment] 2016-10-02 09:18
@markusand Could you attach screenshots and perhaps a small sketch that exhibits the issue?

**Comment by quarks** [comment] 2016-10-02 16:33
I believe the problem is that P3D mode draws all strokes after the fills so lines appear on top. I think this will solve the problem but with reduced performance

```
hint(DISABLE_OPTIMIZED_STROKE);
```

**Comment by markusand** [comment] 2016-10-02 17:28
@gohai this a sample simple code to illustrate what I'm talking about.

``
int[] data = new int[] { 3,6,9,2,7 };
int total = 27;
PVector center;
float R;

void setup() {
    size(500,500, P3D);
    center = new PVector(width/2, height/2);
    R = 100;
}

void draw() {
    background(#FFFFFF);
    float prevAngle = 0;
    for(int i = 0; i < data.length; i++) {
        float angle = map(data[i], 0, total, 0, TWO_PI);
        fill(#3399FF); stroke(#FFFFFF); strokeWeight(2);
        arc(center.x, center.y, 2*R, 2*R, prevAngle, prevAngle + angle, PIE);
        prevAngle += angle;
    }   
    fill(#FF0000); rectMode(CENTER);
    rect(mouseX, mouseY, 30, 30);
}``

Solution I've been using until now is to draw all shapes that contain stroke in a PGraphic and draw it before other shapes, but it's not very convenient only for solving this issue.

@quarks do you mean ALL strokes are drawn at the end? Solution you proposed works perfectly; I'm wondering how important is that performance issue you're talking about?

**Comment by quarks** [comment] 2016-10-02 18:57
Although you are using P3D your example code is being drawn using 2D stuff only. Try this code with and without the hint (you can simple comment it out).

The line starts behind the circle at the top left and in front bottom right , passing through its centre. Without the hint the line is drawn in front (over) the circle which is wrong. If the hint is allowed then the line will go behind the upper left quadrant of the circle, pierce the centre and go in front (over) the bottom right of the circle which is correct but it will take longer to render.

For small numbers of lines this is not a problem but with a large number of lines the increase in render time can be severe.

```java
void setup() {
  size(300, 300, P3D);
  hint(DISABLE_OPTIMIZED_STROKE);
}

void draw() {
  background(#FFFFFF);
  // Draw circle in XY plane
  fill(#3399FF); 
  stroke(#000000); 
  strokeWeight(2);
  ellipse(width/2, height/2, 100, 100);

  // Draw line using 
  stroke(#000088); 
  line(0, 0, -1, width, height, 1);
}
```
BTW this is not a problem in 2D because everything is drawn with z = 0

In graphics intensive applications such as 3D games lines are not used, everything is a surface made from triangles and/or quads.

So this is not a bug in Processing just an optimisation which can be disabled so you might want to close this issue. :)

**Comment by markusand** [comment] 2016-10-02 22:25
My code was just an example. I have created some classes to draw charts in any context (mainly P2D) but I was using them to show a chart in a P3D sketch and noticed this effect.

Is it posible (and recommendable) to enable and disable the hint inside chart draw function?

**Comment by quarks** [comment] 2016-10-03 15:10
With regard to having a hint inside a single function I suggest that you try it. These hints are used to set settings in OpenGL so if it works it is almost certainly acceptable.

**Closed** 2016-10-05 03:44 UTC

**Comment by benfry** [comment] 2016-10-07 14:50
This is why we have both `P2D` and `P3D`. In 3D rendering (all 3D, not just Processing), when a new pixel is drawn at the same depth as an existing pixel, the original pixel is not replaced, the way that it is with 2D drawing. If we did that, 3D shapes would have lots of quirks when they intersect. But when doing straight 2D drawing, you need the replacement to happen, so we include the `P2D` drawing mode for users who want that.

**Comment by hamoid** [comment] 2018-04-24 11:46
>  In 3D rendering when a new pixel is drawn at the same depth as an existing pixel, the original pixel is not replaced

Being picky, in OpenGL how the depth comparison is done is set by the user with this function https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDepthFunc.xhtml 
Just to point out that it may be the default, but not a hard coded rule. Sometimes it's useful to use `glDepthFunc(GL_LEQUAL);` instead of `glDepthFunc(GL_LESS);`.
