### ISSUE TITLE
linuxarm export application with serial communication not working

### ISSUE THREAD

**Issue by joepekoe** [processing/processing#4331] opened 2016-02-26 16:35 UTC
Serial communication from exported applications using processing-3.0.2-linux-armv6hf on Raspberry Pi 2 does not work, however the same sketch works as expected when run from within the IDE.  The exported application fails regardless of whether java is embedded in the application or not.

HOW TO REPRODUCE:
1) Install Processing 3.0.2 on a Raspberry Pi 2 running either Raspian JESSIE or Ubuntu MATE 15.10.
2) Write a processing program that utilizes USB ports between Raspberry Pi 2 and Arduino MEGA for serial communication at 115200 baud.
3) Ensure the program runs as expected within the Processing IDE software tool.
4) Use "Export Application" to create a linux application and try running it on the Raspberry Pi 2.

HARDWARE TESTED:
Raspberry Pi 2
Arduino

SOFTWARE TESTED:
Processing 3.0.2 on Raspian JESSIE w/ jdk-8-oracle-arm32-vfp-hflt
Processing 3.0.2 on Ubuntu MATE 15.10 w/ jdk-8-oracle-arm32-vfp-hflt

NOTE:  The same exact sketch does work as a Linux32 application when exported from Processing 2.2.1 and run on the Raspberry PI against jdk-7-oracle-arm-vfp-hflt

**Comment by jarkman** [comment] 2016-04-17 14:53
I'm seeing exactly the same problem, Processing 3.0.2 on Pi. I'd love to hear of any possible fix or workaround.

**Comment by jarkman** [comment] 2016-04-19 13:59
I have a workaround for my use case, using processing-java to make the processing IDE load and run a sketch, as described here:
http://www.dsfcode.com/using-processing-via-the-command-line/

**Comment by joepekoe** [comment] 2016-04-20 01:54
Interesting, there is not option to install processing-java in my IDE under any of the menus.  What version IDE are you using.  Also, are you developing on the PI, windows, or something else?  Can you develop on windows, export to arm, copy to the PI and execute that code with processing-java?

**Comment by jarkman** [comment] 2016-04-20 07:21
Sorry, I left out most of the useful details there... :-)
I didn't have to install processing-java, it seems to come with Processing.
I'm using Processing 3.0.2.
I'm developing on the Pi.
processing-java doesn't use the exported app, it fires up the IDE with your chosen sketch, then compiles and (if you use the --run flag) runs it
I'm just doing
$ processing-java --sketch=FootFallField --run
I'm not making an output directory, and that doesn't seem to be a problem.
When using --run, the IDE doesn't appear on screen either before or after the sketch runs, so the overall experience is very like running an exported app. There is a delay of a few seconds between issuing the command line and seeing the sketch, which I assume is the IDE starting up and doing the compiling in the background.

Any help ?

**Comment by gohai** [comment] 2016-05-08 17:36
@joepekoe @jarkman 

I am having troubles reproducing the issue here with 3.0.2. The following steps work for me - can tell me what you're doing different, so that I can look into it? Thanks!

- Downloaded and installed http://download.processing.org/processing-3.0.2-linux-armv6hf.tgz
- Connected Arduino to Pi via USB
- Launched Processing IDE
- Opened SimpleWrite example from Serial library
- Changed `portName` to be `Serial.list()[1]`, since the first one is the Pi's built-in TTY
- Saved to my sketchbook
- _File_, _Export Application..._
- Added checkbox for Linux, removed checkbox pertaining to embedding Java for 32-bit
- Pressed export
- Closed Processing
- Navigated to application.linux-armv6hf subdirectory inside of the sketch folder in a terminal window
- Ran `./SimpleWrite`

**Comment by jarkman** [comment] 2016-05-08 19:40
@gohai - did you get successful communication ?

**Comment by gohai** [comment] 2016-05-08 19:43
The RX light on the Arduino was flashing, didn't look closer. What are the exact symptoms you're seeing w/ exported applications?

**Comment by jarkman** [comment] 2016-05-08 20:01
Hm. That is a good question, obviously. Sorry I didn't make a better record of it. 

I think it was a giant crash on startup when running https://github.com/jarkman/FootFallField/tree/master/processing/FootFallField - would you like to give that a quick go ?

**Comment by gohai** [comment] 2016-05-08 20:04
I will tomorrow. You could try to replicate my steps too, and see if they work for you?

**Comment by jarkman** [comment] 2016-05-08 20:30
Yes, I'll give it a go tomorrow evening.

**Comment by gohai** [comment] 2016-05-09 05:21
@jarkman FootFallField starts up for me when exported, but it does so regardless if I have an Arduino connected to ARM or not. Please send a minimal test case if you can. (also @joepekoe) Thanks!

**Comment by joepekoe** [comment] 2016-05-09 12:42
@gohai 

Thanks for looking into this.  It looks like your process of development and execution matches mine exactly.  However, did you run a program on the Arduino that also transmitted data back to the PI?

In my case, my application was run on the PI, made a request for data to the Arduino, and the Arduino would then return information to the PI.  This was the problem I saw...Tx PI -> Arduino was fine and the Arduino Rx lit just as you saw in your test.  However, Tx Ardunio -> PI did not work.  Note, communication back and forth between the two devices worked fine when the same program was run within the IDE.  It only failed when the exported application was run on the PI. 

Make sure the Arduino in your testing is also returning data to the PI.  This seems like it might be why you can't reproduce the problem.

**Comment by gohai** [comment] 2016-05-15 16:45
@joepekoe I tried with [this testcase](https://github.com/processing/processing/tree/master/java/libraries/serial/test/serial_latency) using a USB-attached Arduino Duemilanova, and it worked equally well from the IDE as well as from exported applications.

Closing.

**Closed by gohai** 2016-05-15 16:45 UTC
Labels: arm, serial
