### ISSUE TITLE
Processing won't start

### ISSUE THREAD

**Issue by koningboy18** [processing/processing#5859] opened 2019-05-12 08:52 UTC
Description
When launching Processing shows the loading screen and then displays this error
![Screen Shot 2019-05-12 at 10 41 29 AM](https://user-images.githubusercontent.com/42653226/57579908-76045f00-74a3-11e9-990a-9b105d8477a2.png)

Expected Behavior
Processing to launch normally

Current Behavior
It doesn't launch at all and displays the error given in the description

Steps to Reproduce

1.  Download Processing
2. Extract the zip
3. launch Processing

My Environment

* Processing version: processing-3.5.3
* Operating System and OS version: Mac OS Mojave 10.14.4

Steps i have taken to try and fix it
* download the zip file again
* Open Processing from different locations
* Launch Processing as root from terminal
* Try a different version

**Comment by WesleyM77** [comment] 2019-05-13 14:45
Duplicate of #5851 & #5857.

**Comment by benfry** [comment] 2019-06-11 18:03
Closing as duplicate.

**Closed by benfry** 2019-06-11 18:03 UTC
Labels: duplicate
