### ISSUE TITLE
KeyPressed stops triggering on Mac if Key Repeat is on

### ISSUE THREAD

**Issue by taloras** [processing/processing#5078] opened 2017-05-20 17:09 UTC
In my Processing Sketch, I use the keyPressed() and keyReleased() functions in order to move a rectangle. In the keyPressed method if I use the arrow keys and keyCode to move, then the program works fine. However, if I ever use the "key" variable to check for WASD, then the program stops calling triggering the keyPressed() method after ~30 seconds, seemingly randomly. I was able to fix this issue by going to System Preferences -> Keyboard, and changing the Key Repeat slider to the off position. After doing so, the keyPressed method no longer freezes and the program works fine. However, this is not a good fix because the Key Repeat slider is what makes the backspace key delete many letters in one press as well as is necessary for everyday computer use.

**Comment by benfry** [comment] 2017-05-20 17:51
Duplicate of https://github.com/processing/processing/issues/4952

**Closed by benfry** 2017-05-20 17:51 UTC
