### ISSUE TITLE
the new version 3.2 can't start in the folder  'Program File(s)'

### ISSUE THREAD

**Issue by n0wave** [processing/processing#4629] opened 2016-08-18 16:34 UTC
i have tried many times on windows 10, no matter in which disk, when Processing 3.2 in the folder named 'program files' or 'program',  it will not start

**Comment by Phlosioneer** [comment] 2016-08-19 16:38
Same issue here, also doesn't work in a folder named "Program Files (x86)".

**Comment by benfry** [comment] 2016-08-19 18:13
Duplicate of https://github.com/processing/processing/issues/4623

**Closed by benfry** 2016-08-19 18:13 UTC
