### ISSUE TITLE
Trouble with turning Android Mode

### ISSUE THREAD

**Issue by YUKUDA** [processing/processing#3704] opened 2015-08-23 21:44 UTC
![image](https://cloud.githubusercontent.com/assets/4420498/9430314/ab52719a-4a1a-11e5-810b-c104cb111194.png)

Android SDK installed.

What's wrong?

**Comment by codeanticode** [comment] 2015-08-24 12:35
Hello, thanks for reporting the issue. However, this should be in the [processing-android repo](https://github.com/processing/processing-android/issues). As a matter of fact, sounds like a duplicate of https://github.com/processing/processing-android/issues/139. Let's continue the discussion over there.

**Comment by benfry** [comment] 2015-08-24 16:08
Fixed for 3.0 beta 5, thanks for the report.

**Closed by benfry** 2015-08-24 16:08 UTC
Labels: android, duplicate
