### ISSUE TITLE
NullPointerException in LanguageBundle.read() on startup

### ISSUE THREAD

**Issue by audaybasheer** [processing/processing#4476] opened 2016-05-14 11:04 UTC
java.lang.NullPointerException
at processing.app.Language$LanguageBundle.read(Language.java:320)
..................
.................

**Comment by benfry** [comment] 2016-05-14 13:15
This was fixed in 3.1. Are you using that release?

**Comment by aidenatt** [comment] 2016-05-17 12:53
I'm also having this problem, using 3.1.1 on Windows 10.

**Comment by benfry** [comment] 2016-05-17 15:18
cc @JakubValtar thought we had this licked in https://github.com/processing/processing/issues/4417 https://github.com/processing/processing/pull/4426

**Comment by JakubValtar** [comment] 2016-05-17 15:25
@audaybasheer @aidenatt Could you please post the full path to processing.exe? Like this: `C:\Users\Bobbo\Desktop\apps\processing\processing.exe`

**Comment by ric-bianchi** [comment] 2016-05-19 12:40
Hi,

Maybe this can give you an hint about the cause of the issue.

I had the same problem here, with Processing 3.1.1 on Windows 10 (64bits), when I extracted the Processing zip into my home folder, which is a network folder (DFS).

Then I extracted it into a local folder, and everything now works just fine.

Cheers,

    Ric.

**Comment by benfry** [comment] 2016-07-28 22:51
@JakubValtar is this fixed with #4582?

**Comment by JakubValtar** [comment] 2016-07-28 23:05
@benfry Should be. However, I was able to test only a simple scenario with my resources.

**Comment by benfry** [comment] 2016-07-28 23:24
Ok, I'll assume it's a dupe https://github.com/processing/processing/issues/4417

**Closed by benfry** 2016-07-28 23:24 UTC
Labels: duplicate
