### ISSUE TITLE
Zero length string passed to TextLayout constructor

### ISSUE THREAD

**Issue by Corrado972** [processing/processing#3487] opened 2015-07-20 07:26 UTC
Hello,
I have just run my sketch with Processing v3.0a11 under Windows 7 64 bit.

This row called in draw(): 
text(testo, myX, myY, myW, myH);

Fail with the error "Zero length string passed to TextLayout constructor" but "testo" isn't empty, it's equal to "Assprz from G5 67509: 5 min ".

With the previous release the execution is without errors.

Bye

**Comment by benfry** [comment] 2015-07-20 12:12
Works fine here. Please share some code that actually shows the problem.

<img width="820" alt="screen shot 2015-07-20 at 8 11 24 am" src="https://cloud.githubusercontent.com/assets/1623101/8775514/005623f0-2eb7-11e5-9a9d-5da14cea79c9.png">

**Comment by Corrado972** [comment] 2015-07-20 16:22
I have a very complex sketch that I cannot post here because it's not public.

The setup() method opens many JDBC connections then, in the end, start a thread that execute many query over the connections.

The draw() method create this string:
  String testo = normalizzaTipoJob(info.tipoJob) + ": " + getTempo(info.esecDaMin) + " ";

The two methods normalizzaTipoJob and getTempo returns a string.

In the end of draw() there is the line that cause the error:
  text(testo, myX, myY, myW, myH);

The previous line:
  String testo = normalizzaTipoJob(info.tipoJob) + ": " + getTempo(info.esecDaMin) + " ";
causes the error, buf if I write instead:
  String testo = normalizzaTipoJob(info.tipoJob) + ": " + getTempo(info.esecDaMin);
The execution is ok, so the presence of at least a space in the end of the string cause the error.

I try to semplify the code in a example sketch for you, but I can't reproduce the same error in a more simple sketch.

Very strange!

**Comment by alignedleft** [comment] 2015-07-20 17:44
If you can't reproduce the problem in a simpler sketch, then perhaps the problem is not occurring where you expect. If you can isolate the issue, we can look into it and address it.

**Comment by benfry** [comment] 2015-07-27 15:05
Closing since I can't reproduce it even after writing a test case myself, and there's nothing we can go on here.

**Closed by benfry** 2015-07-27 15:05 UTC
Labels: cantfix

**Comment by benfry** [comment] 2015-08-13 16:24
Ran across a version of this and added a fix for 3.0 beta 4.

**Comment by ZachSundberg** [comment] 2015-08-16 17:29
I don't know if it's a bug or not, but a variation of this problem still exits in the newest beta.  It occurs anytime the first character of a string, or the first character after a line break is blank. So:

" the first space is blank"
or
"the space after this break \n is blank" 

using trim when passing String variables works in the case of the former, but not the later.
