### ISSUE TITLE
Processing 3.1.1 with P2D/P3D on raspberry pi: mouseButton is "0"

### ISSUE THREAD

**Issue by tibfox** [processing/processing#4499] opened 2016-05-21 22:30 UTC
under raspberry pi with the current version of processing (3.1.1) and enabled P2D (no experimental open gl) 

Now I have an issue with mouseButton and its value. All I get is "0" :(  

```
void setup(){
  //size(200,200);
size(200,200,P2D);
}

void draw(){
}

void mousePressed(){
   println(mouseButton);
}
```

prints out "0". Without "P2D" in size() i got the correct value "37".

After activating the experimental open gl driver via raspi-config -> "37" as mouseButton LEFT

thanks in advance

**Comment by gohai** [comment] 2016-05-22 03:18
Thanks for the helpful bug report @tibfox. I'll look into it.

**Comment by gohai** [comment] 2016-05-22 16:51
Confirmed. Looks like a problem either in the Pi-specific backend in JOGL, or in the Broadcom GLES2 driver itself. I will report to the JOGL team.

All mouse mouse events lack the button information, like this one:

````MouseEvent[EVENT_MOUSE_CLICKED, [117]/[64], button 0, count 1, rotation [0.0, 0.0, 0.0] * 1.0, pointer<1>[0/Mouse: 117/64, p[0.0/1.0=0.0]], InputEvent[modifiers: [], NEWTEvent[source:jogamp.newt.driver.bcm.vc.iv.WindowDriver, consumed false, when:1463935695926 d 1ms]]]````

**Comment by gohai** [comment] 2016-05-22 16:57
https://jogamp.org/bugzilla/show_bug.cgi?id=1309

**Comment by gohai** [comment] 2017-02-17 13:50
@tibfox This will finally be fixed in the upcoming release of Processing. Thanks for the report!

**Closed by gohai** 2017-02-17 13:50 UTC
Labels: arm, opengl

**Comment by tibfox** [comment] 2017-02-17 14:13
Super thanks a lot !

**Comment by benfry** [comment] 2017-02-17 22:28
@gohai which release are you referring to? Is this part of #4911?

**Comment by gohai** [comment] 2017-02-18 04:22
@benfry Yes! (meant: an upcoming release)

@tibfox You could download an updated [jogl-all.jar](https://github.com/gohai/processing/raw/094f95e0537cac8fdd91f91351c618272acb761c/core/library/jogl-all.jar) already and replace the existing one in `core/libraries`, if you wanted.
