### ISSUE TITLE
systematic libEGL errors on Linux with P3D

### ISSUE THREAD

**Issue by teo1978** [processing/processing#2775] opened 2014-08-11 15:05 UTC
Steps to reproduce
- open any example sketch
- change the renderer to P3D. e.g. size(640, 360,P3D); 
- run the sketch
- stop the sketch

This warning shows up in the console when starting the sketch:
>    libEGL warning: DRI2: failed to authenticate

And these errors (or at least they show up in red, so if they are not errors something is wrong) show up when stopping the sketch:
>    X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 1/1, reusable (open,   marked uncloseable): 0, pending (open in creation order): 1)
>    X11Util: Open X11 Display Connections: 1
>    X11Util: Open[0]: NamedX11Display[:0, 0x7f94f4895830, refCount 1, unCloseable false]

This is Processing 2.2.1 on Ubuntu 14.04

**Comment by benfry** [comment] 2015-04-21 06:06
@codeanticode Can this be closed with the LWJGL shift?

**Comment by codeanticode** [comment] 2015-07-16 16:04
I would say so. @teo1978 @monkstone do you still see these issues in 3.0a10?

**Comment by monkstone** [comment] 2015-07-16 16:12
Still seen o Archlinux with 3.0a10:-
```bash
Listening for transport dt_socket at address: 8856
Display 1 does not exist, using the default display instead.
X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 2/2, reusable (open, marked uncloseable): 0, pending (open in creation order): 2)
X11Util: Open X11 Display Connections: 2
X11Util: Open[0]: NamedX11Display[:0.0, 0x7efed0341f70, refCount 1, unCloseable false]
X11Util: Open[1]: NamedX11Display[:0.0, 0x7efed0414730, refCount 1, unCloseable false]
```

**Comment by codeanticode** [comment] 2015-08-05 15:25
A particular warning messages shown in the latest 3.0 alphas ("Display x does not exist, using the default display instead") was due to a bug in the device parsing, which is now fixed with https://github.com/processing/processing/commit/844501686ce509c21b9856d1accae7f41e729060 and https://github.com/processing/processing/commit/9399ba5bf092e5a8484a16a81c0ef8b319e33274.

Besides that, this issue is essentially a duplicate of https://github.com/processing/processing/issues/1651

I think these error messages are out of our and JOGL's control, see this discussion on the [JOGL forum](http://forum.jogamp.org/JOGL-libEGL-warning-Linux-td4031604.html).

**Closed by codeanticode** 2015-08-05 15:25 UTC
Labels: duplicate, linux, opengl
