### ISSUE TITLE
Can't use 'Esc' to close sketch unless window clicked

### ISSUE THREAD

**Issue by paul59** [processing/processing#3415] opened 2015-06-21 11:55 UTC
Processing 3 alpha 10, Linux Mint 17 xfce, Java 1.8.0_45:

Sketch windows don't respond to 'Esc' (to close) unless I click in the client area first, even though the window appears to have focus.

No such problem on versions 2.x

**Comment by aengelke** [comment] 2015-06-21 12:36
Duplicate of #3389, which is fixed.

**Closed** 2015-06-21 17:39 UTC
Labels: duplicate
