### ISSUE TITLE
processing-java: Commander raises java.lang.reflect.InvocationTargetException / NullPointerException

### ISSUE THREAD

**Issue by ybakos** [processing/processing#4455] opened 2016-05-09 13:19 UTC
On OSX, Processing 3.1
Ref: https://github.com/b-g/processing-sublime/issues/111

Command:
processing-java --force --sketch=/foo/bar/DeleteMe --output=/foo/bar/DeleteMe/build-tmp --run

Result:
err is java.lang.reflect.InvocationTargetException
Exception in thread "main" java.lang.NullPointerException
	at processing.mode.java.Commander.<init>(Commander.java:263)
	at processing.mode.java.Commander.main(Commander.java:86)

**Comment by ybakos** [comment] 2016-05-09 13:20
I'm looking at the commit history to see what has changed, but if it's obvious and you can point me to the specific commit, please let me know. I'll send a PR.

**Comment by ybakos** [comment] 2016-05-09 13:32
Also reproduced on Linux (Fedora 23).

**Comment by ybakos** [comment] 2016-05-09 13:58
Confirmed that it's not a Java version issue (installed version is 8u92).

**Comment by ybakos** [comment] 2016-05-09 14:15
I was suspicious of commit 90213d4b6f8e5416a7a5b1879018e03705154c1e but this doesn't seem to be the issue. A local build from source, followed by an installation of _processing-java_, works just fine.

**Comment by JakubValtar** [comment] 2016-05-09 14:31
Hi @ybakos, sorry for inconvenience. It's already fixed, will be released soon in 3.1.1. Duplicate of https://github.com/processing/processing/issues/4452

**Closed by JakubValtar** 2016-05-09 14:31 UTC

**Comment by jackson-sandland** [comment] 2016-05-15 20:05
Is this issue resolved? I'm seeing this issue with the latest download of Processing, while using Sublime Text to run .pde files.

**Comment by JakubValtar** [comment] 2016-05-17 05:40
3.1.1 with this fix is finally out, try now
