### ISSUE TITLE
size() not working on Windows 10, spans full monitor space

### ISSUE THREAD

**Issue by emilyj0y** [processing/processing#6046] opened 2020-05-20 21:23 UTC
## Description

Processing runs sketches across both of my monitors (I have two, extending display) in an apparent windowed full-screen mode, that also seems like it runs off the bottom of the screens, despite having size() set. 

## Expected Behavior

I would expect size() would open a sketch window at the specified parameters. 

## Current Behavior

size() is ignored, and the sketch expands to fill both of my screens. 

## Steps to Reproduce

1. Open literally any provided example sketch and run it. 
2. Sketch runs, expanded across and off (on bottom) of both monitors.

## Your Environment

 

* Processing version: Reproduced this error on 3.5.4, 3.5.3, and the 4 alpha 1. 
* Operating System and OS version: Windows 10 Version 1903 for x64-based Systems
* Other information: GPU is NVIDIA GeForce GTX 960 (since I've got two monitors hooked up through it, extending my desktop)

**Comment by ThxSkeleton** [comment] 2020-06-25 23:23
I have the same issue

**Comment by Josh-kosar** [comment] 2020-07-13 03:12
I am also experiencing the same issue and its causing havoc on all of the sketches I have that use height or width as a reference for placing things.

**Comment by benfry** [comment] 2020-09-24 00:23
Under what circumstances? Does `size(100, 100)` do it, or `size(100, 100, P3D)` or what? The issue template asks for more details; just saying “it's broken” doesn't help anyone fix it.

**Comment by olivierNOX** [comment] 2020-10-25 10:59
I had no problem till yesterday when this size( ) problem happenned to me. 
**I am using Processing 3.5.4 on a win10** lenovo computer i have bought in september. Everything was ok. I use processing all the time as a teacher. Yesterday and the day before yesterday i did lot's of test trying to interface a kinect with processing. But it's not clear if this is the origine of the problem. My computer also have made updates, could also be the origine. I also have installed previous versions of processing (3.5.3 and 2.2.1) yesterday. I realized the problem at this moment. Maybe linked? I moved 2.2.1 and 3.5.3 in another directory just in case but no change.
 
@benfry **none of this do it with processing 3.5.4 or 3.5.3: `size(100,100);` or `size(100,100, P2D);` or `size(100,100, P3D);` 
But the problem does not appear for me with processing 2.2.1.**

I tried to remove and download again processing 3.5.4: still the same problem.
I tried to remove all updates and installed programs from the past 2 days: still the same problem (but windows automatically re-install a new update after i delete one, so... and i prefer not to change update parameters by now)

**Comment by olivierNOX** [comment] 2020-10-25 11:25
Problem solved for me, but i don't understand why!! Am i wrong by thinking that under windows installing Processing is just unpacking a zip file so that should not impact any parameter of the computer?
Because i have just installed pre-release 4.0 and try it: i run an empty code: same full window problem. I close the window and go to File\preferences, do nothing, close it, don't know why i run again the empty code and now i have a 100x100 exptected window result !?!
@benfry **I run processing 3.5.4 to see if that miracle fixed everything and yes, it's all back in order...** 

**Even if it works fine for me now, i'm very interested in any explanation to avoid making wrong steps another time. Can anybody tell what's happened?**

Just for information: during this "Processing 3.5.4 not working as expected" time, i also had pb to install minim library with the sketch tool. I thought it was not linked to the other problem but this also works fine now.

**Comment by emilyj0y** [comment] 2020-11-30 16:22
For me, it also ignored size(100,100); or size(100,100, P2D); or size(100,100, P3D); and went full screen, in 3.5.4 and 3.5.3

I saw @olivierNOX comment about opening File>Preferences, doing nothing and closing it, and tried it - this fixed the problem. size() is once again obeying the values I give it.

**Comment by benfry** [comment] 2021-07-05 17:35
I still haven't been able to reproduce this, but it may be fixed with some changes that were in 4.0 alpha 4.

If you run into this problem, try with a 4.x release: https://github.com/processing/processing4/releases

And if you have a problem with one of those, file a new issue here: https://github.com/processing/processing4/issues/new

**Closed by benfry** 2021-07-05 17:35 UTC
