### ISSUE TITLE
Feature request: Import archived sketch from File menu

### ISSUE THREAD

**Issue by quarks** [processing/processing#3987] opened 2015-10-11 19:46 UTC
For a long time we have been able to archive sketches which makes it easier for sharing. It would be nice to have the option to import an archived sketch in a similar manner to Eclipse.

The archive would be unzipped and saved into the Processing sketch folder with the option to overwrite an existing sketch with the same name.

**Comment by benfry** [comment] 2015-10-13 08:24
Duplicate of https://github.com/processing/processing/issues/73

**Closed by benfry** 2015-10-13 08:24 UTC
