### ISSUE TITLE
Processing creates a huge amount of temp files 

### ISSUE THREAD

**Issue by HenriAugusto** [processing/processing#5132] opened 2017-06-15 05:03 UTC
Everytime a sketch is run a temp folder is created in **AppData\Local\Temp**. I just noticed there are literally thousands of files created by processing IDE. Windows is taking 25 minutes to delete some groups of folders related to repeatedly use of a single sketch. (and i have a nice cpu)

![explorer_2017-06-15_01-36-54](https://user-images.githubusercontent.com/11790621/27165824-04c2c274-516d-11e7-940e-1f14ee192d16.png)

While regular cleanup of this folder is something that some users do, some doesn't even know it exists or don't know the system doesn't clean it up regularly (my case). Is there someway of processing deleting those files? Or maybe creating them in **AppData\Local\Temp\processing** instead of **AppData\Local\Temp** for easier clean up?

I'm not that experienced in java but maybe changing [this line of code](https://github.com/processing/processing/blob/95d396fd8b86857b9bd3ebd9a61855ed40a1c6c4/app/src/processing/app/platform/WindowsPlatform.java#L323) to

`return Shell32Util.getSpecialFolderPath(ShlObj.CSIDL_APPDATA, true)+"\processing";`

would be good? I'm not sure if it would break anything. Or maybe find a way in which java would delete the files.

I've only found an [old post](https://forum.processing.org/one/topic/processing-temporary-files-are-they-really-temporary.html
) about this.

Thanks for your attention :)

**Comment by benfry** [comment] 2017-06-15 13:38
Duplicate of https://github.com/processing/processing/issues/1896

**Closed by benfry** 2017-06-15 13:38 UTC
