### ISSUE TITLE
Missing "@" message when using println() outside setup()

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3824] opened 2015-09-18 14:31 UTC
When I try to use some methods before settings() Processing return this weirg error message, see picture below. I understand few methods must be disable before settings() but this error message is very bizarre !
Maybe is better to write "You can use this method before settings()" or something like that.
![capture d ecran 2015-09-18 a 16 28 25](https://cloud.githubusercontent.com/assets/3332269/9961724/5ad04b9a-5e22-11e5-8144-af5e91a92cd4.png)

**Comment by philoniare** [comment] 2015-10-13 17:42
Sorry, I am new to Processing trying to make my first pull request. My understanding is that the error is due to the statement being outside either setup() and draw() or any other function definition. Would an error message such as "Please include the statement in function definition" suffice?

**Comment by GKFX** [comment] 2017-05-24 18:37
I can't reproduce this; the code as given tells me `It looks like you're mixing "active" and "static" modes`, and refuses to compile.
If I write a println wrapper method with a dummy return in my sketch and assign its result to a variable, the code runs fine. The first call to `sketchPath("")` gives the wrong path, but that's expected.
_Debian Linux, Processing 0261. Sketch:_
```java
int a = printlnAndReturn(sketchPath(""));

void settings() {
  size(150,150) ;
}

void setup() {
  println(sketchPath(""));
}

int printlnAndReturn(String s) {
  println(s);
  return 0;
}
```
Outputs my Processing `build/linux/work` directory, followed by the correct `sketchPath`.

**Comment by benfry** [comment] 2017-06-01 13:50
Here's what I get for the current ~3.3.4 build… I think we can close this.

<img width="328" alt="screen shot 2017-06-01 at 9 49 26 am" src="https://cloud.githubusercontent.com/assets/1623101/26682775/a3a618f0-46af-11e7-83e5-cd42860206f7.png">

**Closed by benfry** 2017-06-01 13:50 UTC
Labels: help, low
