### ISSUE TITLE
Windows not running code

### ISSUE THREAD

**Issue by Cosmaniac** [processing/processing#5259] opened 2017-09-14 01:37 UTC
## Description
The Windows Processing application is trying to run the code, freezing up, and refusing to close when asked.
I would like the software developers to take a look at the code and see if there could be any reason that it is not working.

## Expected Behavior
I was expecting my code, which I have run before, to run normally, but it is freezing up and making me use task manager to shut the application down.
I'd like the program to work like it normally does on my Mac. It's a great app, and really useful to use and learn from.

## Current Behavior
The difference from the PREVIOUS behavior (3.3.5) is that the program doesn't execute the code at all. I might have had some errors with my code (which I resolved, and the program ran fine) in the 3.3.5 version, but here I don't even get a result from the program.

## Steps to Reproduce
Download 3.3.6 Windows 64. Run the code below.

1.
```processing
int x;
int X1, Y1, X2, Y2;
int X, Y;

void setup () 
{
  fullScreen();

  background(18);

  stroke(255, 70, 180);

  frameRate(66);

  x = 0;
  X1 = 0;
  X2 = 0;
  Y1 = 0;
  Y2 = 0;
}

void Sphere() 
{
  float X1 = random(0, 50);
  fill(random(255), random(255), random(255));
  ellipse(random(width), random(height), X1, X1);
}


void Star() 
{
    float X1 = random(width);
    float X2 = X1 += 2.5;
    float X3 = X2 += 12.5;
    float X4 = X3 -= 12.5;
    float X5 = X4 -= 2.5;
    float X6 = X5 -= 2.5;
    float X7 = X6 -= 12.5;
    float X8 = X7 += 12.5;
    float X9 = X8 += 2.5;
    float Y1 = random(height);
    float Y2 = Y1 -= 12.5;
    float Y3 = Y2 -= 2.5;
    float Y4 = Y3 -= 2.5;
    float Y5 = Y4 -= 12.5;
    float Y6 = Y5 += 12.5;
    float Y7 = Y6 += 2.5;
    float Y8 = Y7 += 2.5;
    float Y9 = Y8 += 12.5;

    beginShape();
    fill(random(255), random(255), random(255));
    vertex(X1, Y1);
    vertex(X2, Y2);
    vertex(X3, Y3);
    vertex(X4, Y4);
    vertex(X5, Y5);
    vertex(X6, Y6);
    vertex(X7, Y7);
    vertex(X8, Y8);
    vertex(X9, Y9);
    endShape();
    noLoop();
}

  void Spaceship() 
  {
      beginShape();

      stroke(255);
      line(1395, 300, 1445, 255);
      line(1400, 305, 1445, 255);
      line(1400, 300, 1325, 375);
      line(1200, 525, 1181.5, 519.5);
      line(1175, 500, 1181.5, 519.5);
      line(1325, 375, 1181.5, 519.5);

      fill(#767676);

      bezier(1175, 500, 1300, 300, 1300, 300, 1400, 300);
      bezier(1200, 525, 1440, 380, 1390, 350, 1400, 300);

      beginShape();
      fill(#E01600);
      vertex(1175, 500);
      bezierVertex(1140, 500, 1140, 500, 1080, 620);
      bezierVertex(1200, 560, 1200, 560, 1200, 525);
      endShape();

      beginShape();
      fill(#FFF531);
      vertex(1175, 503);
      bezierVertex(1155, 500, 1155, 500, 1110, 590);
      bezierVertex(1200, 545, 1200, 545, 1197, 525);
      endShape();

      beginShape();
      fill(#0023FA);
      vertex(1176, 502);
      bezierVertex(1160, 510, 1160, 510, 1140, 560);
      bezierVertex(1190, 540, 1190, 540, 1198, 524);
      endShape();

      endShape();
  }
  
  void draw () 
{
  background(18);

  rect(x, 0, x, 0);
  /*
   stroke(66, 66, 66);
   int X3 = X1 += 100;
   int X4 = X2 += 100;
   int Y1 = 0;
   line(X3, Y1, X4, height);
   }
   {
   stroke(66, 66, 66);
   int Y3 = Y1 += 100;
   int Y4 = Y2 += 100;
   int X1 = 0;
   line(X1, Y3, width, Y4);
   }*/

  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();
  Sphere();

  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  Star();
  
  Spaceship();

  fill (#AF7332); 
    ellipse(width*.5, height*.7, 300, 300);
  
}
```
2.
3.

## Your Environment
I am using a Windows 10 hp 64-bit processing unit.
64-bit graphics card, Windows 10 Pro
Windows Firewall is enabled on my computer and may be blocking part of the application that is new.
* Processing version: 3.3.6
* Operating System and OS version: Windows 10 Pro
* Other information:

**Comment by Dr-Zoidberg-de** [comment] 2017-09-18 06:37
Got the same problem. reinstalled several times. i cant even get example sketches to work

**Comment by x13420x** [comment] 2017-10-14 23:15
I am not a developer but had a similar problem.....check that you dont have the memory expanded in the pref menu......I was guessing it was a java problem but maybe there is a memory leak????....I really have no clue :)

**Comment by efrinumeric** [comment] 2017-11-18 10:54
It seems that we all have the same problem. It's really annoying.

**Comment by AlvaroHermida** [comment] 2017-11-18 18:17
Not a Processing bug. The last line of the method `Star()` is 
`noLoop();`
whose [specification ](https://processing.org/reference/noLoop_.html)says:
> noLoop()
Stops Processing from continuously executing the code within draw(). 

...and Processing is doing just what is specified (both in 3.3.5 and 3.3.6). Just delete the `noLoop()` call, and the animation will run fine.

@Cosmaniac, if your intent was to run the script frame by frame, add
`void mousePressed() {
  loop();
}`
at the end of your script and Processing will draw a new frame everytime you click the mouse.

Also, maybe you want to rewrite the lines inside `Star()`:
`  float X2 = X1 += 2.5;`
in this way:
`  float X2 = X1 + 2.5;`

**Comment by benfry** [comment] 2017-12-08 20:31
Sounds like it's not a bug; closing.

**Closed by benfry** 2017-12-08 20:31 UTC
