### ISSUE TITLE
saveFrame trips ClassCastException on Raspberry Pi

### ISSUE THREAD

**Issue by markstock** [processing/processing#2010] opened 2013-08-06 18:35 UTC
This is an issue I raised on the Processing forum recently: http://forum.processing.org/topic/saveframe-trips-classcastexception-on-raspberry-pi

I am running Processing 2.0b8 under raspbian on a Raspberry Pi. The bad codes all use the Java runtime, and Java2D graphics. I taught a workshop to some middle-schoolers on using Processing to learn math and programming via algorithmic art.

Problem summary: All calls to loadPixels() bomb on a ClassCastException error:

Exception in thread "Animation Thread" java.lang.ClassCastException: [I cannot be cast to [S
        at sun.awt.image.ShortInterleavedRaster.getDataElements(ShortInterleavedRaster.java:293)
        at processing.core.PGraphicsJava2D.loadPixels(PGraphicsJava2D.java:2308)
        at processing.core.PImage.save(PImage.java:3209)
        at processing.core.PApplet.saveFrame(PApplet.java:4063)
        at vortex_advanced.keyPressed(vortex_advanced.java:95)
        at processing.core.PApplet.keyPressed(PApplet.java:3339)
        at processing.core.PApplet.handleKeyEvent(PApplet.java:3157)
        at processing.core.PApplet.dequeueEvents(PApplet.java:2606)
        at processing.core.PApplet.handleDraw(PApplet.java:2277)
        at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:243)
        at processing.core.PApplet.run(PApplet.java:2140)
        at java.lang.Thread.run(Thread.java:722)

**Comment by benfry** [comment] 2015-08-02 17:27
@gohai reports that he cannot reproduce this with stock rpi and the current source.

Can others please confirm?

**Comment by benfry** [comment] 2015-08-12 23:58
Seems like this is no longer an issue; closing.

**Closed by benfry** 2015-08-12 23:58 UTC
