### ISSUE TITLE
Incompatible with Java 1.8.0.111?

### ISSUE THREAD

**Issue by folterj** [processing/processing#4717] opened 2016-10-26 15:43 UTC
Using Processing 3.2.1, I have installed Java JRE 1.8.0.111 (both 32 and 64 bit). When exporting to a Windows executable (without Java inclusion), an error dialog shows "This application requires a Java Runtime Environment 1.8.0_74". I understood that later versions (certainly sub-versions) should run java compiled with older version fine, so there appears to be an issue. Note that the JRE that comes with Processing is actually version 1.8.0_102, which although different from the dialog message, does appear suitable.

PS: Independently from this issue, the error dialog also opens a browser attempting to download Java for the browser - not a stand-alone JRE.

**Comment by benfry** [comment] 2016-10-26 16:03
Duplicate of https://github.com/processing/processing/issues/4682

**Closed by benfry** 2016-10-26 16:03 UTC

**Comment by folterj** [comment] 2016-10-26 20:00
Hi,


Thanks for following up, I did do a search on JRE but didn't find it.

Anyway hope it gets resolved soon.


Thank you,


Joost.


________________________________
