### ISSUE TITLE
processing won't open

### ISSUE THREAD

**Issue by rluetters** [processing/processing#4850] opened 2017-01-23 18:59 UTC
Every time I try to run Processing, it says "Required files could not be found. If running from a folder with non-ASCII characters, try moving the file to another location. 1.8.0_60" What does this mean and what do I do to get Processing to open?

**Comment by GKFX** [comment] 2017-01-28 14:41
This is probably bug #3543. There is a bug in Launch4J (used to start Processing on Windows) which means that if you install Processing so that the path to `processing.exe` contains certain non-ASCII characters, it won't open. So try to make sure that the path to `processing.exe` only contains the normal English letters and numbers (not á or à, for example). If that solves it then this is the same bug.

**Comment by benfry** [comment] 2017-01-29 15:26
Closing as a duplicate of https://github.com/processing/processing/issues/3543

**Closed by benfry** 2017-01-29 15:26 UTC
