### ISSUE TITLE
3.0.2 - 3.1.1 Weird behavior of console window size if editor.window.height.default is > 713

### ISSUE THREAD

**Issue by gdsentropy** [processing/processing#4515] opened 2016-05-29 06:43 UTC
Hello,

This took me a while to track down to the exact setting and threshold, and it drove me nuts.
Happens on both Mac OSX and Windows...if you go into preferences.txt and set
editor.window.height.default=713 nothing happens, but if you set it to 714, the console window now takes up most of the page.

I have attached two images, the only difference between the two instances is as described.

Ian

![713](https://cloud.githubusercontent.com/assets/4730234/15631744/d970c772-2546-11e6-85bd-331869435b07.png)
![714](https://cloud.githubusercontent.com/assets/4730234/15631743/d970132c-2546-11e6-89c6-3f5fa0b7ef9e.png)

**Comment by earthbound19** [comment] 2019-10-28 15:37
Related to #3385?

**Comment by benfry** [comment] 2020-01-18 00:56
Closing as duplicate of #3385.

**Closed by benfry** 2020-01-18 00:56 UTC
Labels: help wanted, low
