### ISSUE TITLE
It was not meant to be

### ISSUE THREAD

**Issue by gedapeleda** [processing/processing#5276] opened 2017-09-28 19:17 UTC
## Description

When I start the program I get the blue loading and then a fatal error saying it was not meant to be
![scann](https://user-images.githubusercontent.com/32372233/30985887-07537d8a-a492-11e7-87b0-37e0e762740c.PNG)

## Your Environment
Windows 10 x64
Processing 3.3.6
I tried  to redownload , admin, compatability
Same results

**Comment by benfry** [comment] 2017-09-29 15:31
Duplicate of https://github.com/processing/processing/issues/4929

**Closed** 2017-10-19 02:51 UTC
Labels: duplicate
