### ISSUE TITLE
Step on the edge of cube

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#3229] opened 2015-04-29 16:39 UTC
When the light is active, we can see a step on the edge of polygon, when it's without light and we just display the edge, there no problem but not sure.
Maybe it's an OPENGL problem ?
With P307 on mac OSX 10.9 iMac 2012
``````
void setup() {
  size(500,500,P3D) ;
}

float angleY;
float angleZ;
void draw() {
  background(0) ;
  /*
  may be little step on the edge of cube, but not sure
  noFill() ;
  strokeWeight(1) ;
  stroke(255) ;
  */
  /*
  sometime big step on the edge of cube, we need light to see.
  fill(255) ;
  noStroke() ;
  ambientLight(0,100, 0) ;
  directionalLight(255, 0, 0, -1, 0, 0);
  */
  angleY += 0.025;
  angleZ += 0.02;
  pushMatrix() ;
  translate(width/2, height/2,-width);
 rotateY(angleY);  
  rotateZ(angleZ); 
  box(500, 500,500) ;
  popMatrix() ;
}
````````

**Comment by JakubValtar** [comment] 2015-05-05 22:19
Could you please post a screenshot or a video of the issue? I don't see anything unexpected...

**Comment by StanLepunK** [comment] 2015-05-06 07:36
It's hard to catch the default because is not often and short few milliseconde. I change the code now it's more easy to see. May be it's something with my speed screen (Hz) ??? But that's not happen with Processing 305, just with 307
It's like the picture is refresh from bottom to the top, and left to right.
Make sens ?
````````
void setup() {
  size(500,500,P3D) ;
}

float angleY;
float angleZ;
void draw() {
  background(0) ;

  
  // sometime big step on the edge of cube, we need light to see.
  fill(255) ;
  noStroke() ;
  ambientLight(0,100, 0) ;
  directionalLight(255, 0, 0, -1, 0, 0);
  
  angleY = map(mouseX,0,width,0,TAU);
  angleZ = map(mouseY,0,height,0,TAU);
  pushMatrix() ;
  translate(width/2, height/2,-width);
 rotateY(angleY);  
  rotateZ(angleZ); 
  box(500, 500,500) ;
  popMatrix() ;
}
```````````````

**Comment by JakubValtar** [comment] 2015-05-06 08:26
I'm going to guess, do you see tearing, something like this?

![vsync04](https://cloud.githubusercontent.com/assets/3177098/7489719/2795f138-f3da-11e4-940e-89dd01c198f0.jpg)

**Comment by StanLepunK** [comment] 2015-05-06 09:19
It's exactly what I see, It's appear like a step stair, because it's on the
edge of the cube, maybe.

2015-05-06 10:26 GMT+02:00 Jakub Valtar <notifications@github.com>:

> I'm going to guess, do you see tearing, something like this?
>
> [image: vsync04]
> <https://cloud.githubusercontent.com/assets/3177098/7489719/2795f138-f3da-11e4-940e-89dd01c198f0.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/processing/issues/3229#issuecomment-99377268>
> .
>



-- 

Stanislas Marçais
::::::::::::::::::::::::::::::
Graphiste Codeur
:::::::::::::::::::::::::::::::
Portfolio
stanislas-marcais.blogspot.com
Projet
romanesco.xyz
:::::::::::::::::::::::::::::::::::::::::::::::::::::::
Tel +33 (0)6 03 67 60 78
LinkedIn <https://www.linkedin.com/pub/stanislas-mar%C3%A7ais/64/964/811> /
Twitter <https://twitter.com/#%21/StanLEpunK> / Github
<http://github.com/StanLepunK> / Flickr
<https://www.flickr.com/photos/94071412@N03/>




<http://stanislas-marcais.blogspot.com/>

**Comment by JakubValtar** [comment] 2015-05-06 14:16
I don't have problems with tearing on my machine, but maybe Macs are more
susceptible?

@codeanticode I'm not very familiar with the new LWJGL code, are we using
double buffering? I see that v-sync is turned off for the sketches.

**Comment by JakubValtar** [comment] 2015-07-20 21:17
I can't reproduce this issue, tried 3.0a7 and 3.0a11. I think we can close this. Processing 3.0a7 was based on LWJGL and we already switched from that, so this is probably no longer valid.

If this is still an issue for you, please let us know in a comment.

**Comment by benfry** [comment] 2015-07-27 15:00
Closing since it's been a week.

**Closed by benfry** 2015-07-27 15:00 UTC
Labels: opengl
