### ISSUE TITLE
'fullScreen' and 'createGraphics' conflict

### ISSUE THREAD

**Issue by hellowewe** [processing/processing#4832] opened 2017-01-16 15:52 UTC
I'm writing the code

> fullScreen(SPAN);
> size(4096, 768, P3D);
> pg1 = createGraphics(768, 768, P3D);

I want to use four projection screen out different four 3D space, and full screen.
But the ` fullScreen(SPAN);` Can't use with `size(4096, 768, P3D);`,and `pg1 = createGraphics(768, 768, P3D);`must run with `size(4096, 768, P3D);`.

So what should I do?

**Comment by gohai** [comment] 2017-01-16 16:11
What happens if you specify the renderer to use as argument to the `fullScreen` function. I.e.:

    fullScreen(SPAN, P3D);
    pg1 = createGraphics(768, 768, P3D);

**Comment by hellowewe** [comment] 2017-01-17 05:22
thanks, it is work.

**Comment by benfry** [comment] 2017-01-17 20:11
(Closing, not a bug…)

**Closed** 2017-01-17 20:11 UTC
