### ISSUE TITLE
Comment/uncomment garbles improperly nested indenting

### ISSUE THREAD

**Issue by gdsentropy** [processing/processing#4251] opened 2016-01-27 14:43 UTC
Version 3.0.1, running on Mac Mini El Capitan.
I have not tried to reproduce this on any other platform.

Given the following example: 
(note it doesn't show up correctly in Github forum view mode, but the inner if is 4 spaces to the left of the outer)
    if (true)
    {
if (true)
{

}
    }

Commenting produces the following result:
    //if (true)
    //{
if (//true)
{
  ////
}
  ////  }

Selecting uncomment will multiply the number of slashes shown above by two.

I will submit my theme and preference files if needed.

**Comment by BorisKourt** [comment] 2016-01-29 10:33
In your issues and comments on GitHub you can use [this syntax](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to provide properly indented code.

**Comment by benfry** [comment] 2016-02-13 15:05
Duplicate of https://github.com/processing/processing/issues/4249

**Closed by benfry** 2016-02-13 15:05 UTC

**Comment by gdsentropy** [comment] 2016-02-13 20:45
I haven't looked at the source, so I suppose it is possible it has the same root cause, but to the user this and the one asserted to be a duplicate are separate behaviors.

Ian McDonald
----------------------------------------
Senior Software Engineer Lead,
Architect and Security Analyst
ASP.NET | MVC | MVVM | WCF
.NET 4.5+, Mono, C#, F#, C++
Web, Win, iOS, Linux, Android
Cell: (919)-830-4606 M-F 365d
------------------------------------------
Please consider this email before printing the environment.
(ノಠ益ಠ)ノ彡┻━┻
