### ISSUE TITLE
Cannot download processing 

### ISSUE THREAD

**Issue by user1108** [processing/processing#5783] opened 2019-02-04 00:20 UTC
## Expected Behavior

I'm having trouble downloading the windows 64 bit version of processing. I click download but then I get a "file not found" message.

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version: 3.5.3
* Operating System and OS version: Windows 64bit
* Other information:

**Comment by Cozop** [comment] 2019-02-04 01:52
I also have this issue.

**Comment by AlvaroHermida** [comment] 2019-02-04 01:54
This is a duplicate of #5782

Yes, the redirection is slightly broken (it links to 
`".../processing-0266-3.5/processing-3.5.3-*"` instead of 
`".../processing-0269-3.5.3/processing-3.5.3-*"`)

As a workaround, the five packages plus the source code can be downloaded using this alternative link:
[https://github.com/processing/processing/releases/tag/processing-0269-3.5.3](https://github.com/processing/processing/releases/tag/processing-0269-3.5.3)

**Comment by MyRaspberry** [comment] 2019-02-04 05:51
is it possible to change the structure in that way that
after a new new revision 
ONLY ONE internal LINK has to be updated
( same as for the 
`curl https://processing.org/download/install-arm.sh | sudo sh`
and all external links and web pages look just for 
* LATEST ( so not need to be changed anymore )

**Comment by benfry** [comment] 2019-02-04 14:58
Download links fixed, sorry for the trouble.

**Closed by benfry** 2019-02-04 14:58 UTC
