### ISSUE TITLE
Debugger in Processing 3.0 _ Step using Ctrl J instead of button

### ISSUE THREAD

**Issue by ertorque** [processing/processing#4003] opened 2015-10-15 15:18 UTC
When I Step using Ctrl J, the software adds an additional (blank) line to the code every time Ctrl J is pressed. I can see that the 'selected' line is correct i.e the line in the next sequence is highlighted  when I step but not before an additional blank line is inserted into the code. 
I am using WIndows 7 64 bit running Chrome. Anyone has encountered similar problems?
Thanks.

Edit-- When the Step button (the one that looks like the Play button) is used, all is ok

**Comment by dnlopez** [comment] 2015-11-08 17:24
I'm encountering the same problem. I'm using Processing 3.0.1 on Arch Linux, 64-bit.

Also happens with Ctrl-Shift-J (step into) and Ctrl-Alt-J (step out).

Duplicate bugs I found in search: 3830, 1803

Related bug to do with the toolbar button: 4116

**Comment by JakubValtar** [comment] 2015-11-08 19:43
Duplicate of #3830

**Closed by JakubValtar** 2015-11-08 19:43 UTC
