### ISSUE TITLE
Cannot open preferences window (OS X 10.10.3)

### ISSUE THREAD

**Issue by winduptoy** [processing/processing#3221] opened 2015-04-26 19:54 UTC
Clicking Processing / Preferences returns this in OS X 10.10.3, Processing 3.0a6.

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Component must be non-null
	at javax.swing.GroupLayout$ComponentSpring.<init>(GroupLayout.java:2953)
	at javax.swing.GroupLayout$ComponentSpring.<init>(GroupLayout.java:2933)
	at javax.swing.GroupLayout$Group.addComponent(GroupLayout.java:1524)
	at javax.swing.GroupLayout$ParallelGroup.addComponent(GroupLayout.java:2484)
	at javax.swing.GroupLayout$ParallelGroup.addComponent(GroupLayout.java:2454)
	at javax.swing.GroupLayout$Group.addComponent(GroupLayout.java:1505)
	at javax.swing.GroupLayout$ParallelGroup.addComponent(GroupLayout.java:2476)
	at processing.app.PreferencesFrame.<init>(PreferencesFrame.java:622)
	at processing.app.Base.handlePrefs(Base.java:1375)
	at processing.app.platform.ThinkDifferent$2.handlePreferences(ThinkDifferent.java:75)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:263)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:254)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: javax.swing.JTextField[,0,0,0x0,invalid,layout=javax.swing.plaf.basic.BasicTextUI$UpdateHandler,alignmentX=0.0,alignmentY=0.0,border=com.apple.laf.AquaTextFieldBorder@6e292827,flags=288,maximumSize=,minimumSize=,preferredSize=,caretColor=javax.swing.plaf.ColorUIResource[r=0,g=0,b=0],disabledTextColor=javax.swing.plaf.ColorUIResource[r=128,g=128,b=128],editable=true,margin=javax.swing.plaf.InsetsUIResource[top=0,left=0,bottom=0,right=0],selectedTextColor=com.apple.laf.AquaImageFactory$SystemColorProxy[r=0,g=0,b=0],selectionColor=com.apple.laf.AquaImageFactory$SystemColorProxy[r=164,g=205,b=255],columns=6,columnWidth=0,command=,horizontalAlignment=LEADING] is not attached to a horizontal group
	at javax.swing.GroupLayout.checkComponents(GroupLayout.java:1086)
	at javax.swing.GroupLayout.prepare(GroupLayout.java:1040)
	at javax.swing.GroupLayout.layoutContainer(GroupLayout.java:910)
	at java.awt.Container.layout(Container.java:1508)
	at java.awt.Container.doLayout(Container.java:1497)
	at java.awt.Container.validateTree(Container.java:1693)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validate(Container.java:1628)
	at java.awt.Window.dispatchEventImpl(Window.java:2748)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by spasmsaps** [comment] 2015-04-26 20:13
duplicate of #3215

**Comment by benfry** [comment] 2015-04-26 21:44
Duplicate, already fixed.

**Closed by benfry** 2015-04-26 21:44 UTC
Labels: duplicate
