### ISSUE TITLE
Autocomplete doesn't work on macOS Sierra

### ISSUE THREAD

**Issue by 4PixelsDev** [processing/processing#5154] opened 2017-06-24 16:31 UTC
I installed Processing 3.3.4 on macOS Sierra v10.12.5(16F73), but autocomplete doesn't work. 
That was the first time installation, so I didn't update from the previous version.
I enabled the code completion with Ctrl+space in preferences, but it didn't helped.

**Comment by stojanovicigi** [comment] 2017-06-25 22:05
The problem is present in 3.3.5 as well.

**Comment by hazmatsuitor** [comment] 2018-01-27 21:57
It works for me using Processing 3.3.5 and 3.3.6 on High Sierra 10.13.2 (17C205). Is this still broken for you?

**Comment by benfry** [comment] 2022-06-19 20:10
Closing this because for Processing 4, this is being tracked here: https://github.com/processing/processing4/issues/491

And it was worked in the final version of Processing 3, which was 3.5.4.

**Closed by benfry** 2022-06-19 20:10 UTC
Labels: macosx, help wanted
