### ISSUE TITLE
Set double in glsl shader

### ISSUE THREAD

**Issue by GanerCodes** [processing/processing#6165] opened 2021-03-08 03:04 UTC
Doubles were added to GLSL a bit ago, however they are not included in the types that can be passed with .set()

**Comment by dzaima** [comment] 2021-03-08 06:40
[previous issue](https://github.com/processing/processing/issues/6084) - the library Processing uses to interface with GLSL just doesn't have any way to set doubles.

**Comment by benfry** [comment] 2021-06-15 00:45
Closing as duplicate of https://github.com/processing/processing/issues/6084

**Closed by benfry** 2021-06-15 00:45 UTC
