### ISSUE TITLE
Dificulty navigating Projects with Large Nubmers of files

### ISSUE THREAD

**Issue by Jesse-McDonald** [processing/processing#5734] opened 2018-12-23 01:57 UTC
## Description
If you have a project with a large number of files (more than about 43) the file tab bar will not display all of them on 1920x1080 monitors (this is at 30 files or so) and the overflow tile list will not display all of the files.  This makes it quite difficult to find and edit files.  Additional, opening a file from explorer will open the root project file, not the file clicked.

## Expected Behavior
Expected one or more of the following
1. Scrolling tab list similar to how Firefox handles many tabs
2. scrolling drop down for tabs
3. opening a file from explorer particularly for a project already open should open the file.
4. Internal file browser similar to that found in Visual Studios
5. The ability to create sub folders inside a project for organization of code files (i.e an src folder where any contained folder are recursively added to the build process), this would allow the overflow menu to list expandable folders rather than file mitigating the problem. (p.s. this would be amazing)
## Current Behavior
none of the above are in effect, and some files are rendered in accessible 

## Steps to Reproduce
1. get a 1920x1080 monitor
2. download and open https://github.com/Jesse-McDonald/CASTER on said monitor
3. try to access file buildUI.pde

## Your Environment
* Processing version: 34.
* Operating System and OS version: Windows 10 pro
* Other information: 1920x1080 monitor

## Possible Causes / Solutions
Implement 1 or more solution found in Expected Behavior

**Comment by MLanghof** [comment] 2018-12-26 23:13
This is a duplicate of #1968. Ancient as that thread may be, I don't think Processing has gained any ambitions to be a fully-fledged IDE since then.

Maybe the tab manager mentioned in #5273 can be of some help?

**Comment by benfry** [comment] 2019-01-11 22:19
Yeah, you're better off with an IDE: https://github.com/processing/processing/issues/1968#issuecomment-96377621

**Closed by benfry** 2019-01-11 22:19 UTC
