### ISSUE TITLE
Would a library for the Servo-PWM Hat be available in Processing ?

### ISSUE THREAD

**Issue by Ragooman** [processing/processing#4549] opened 2016-06-27 22:29 UTC
Hello,

I bought the Servo/PWM Pi Hat for my RPi last year. And it works great. I had originally practiced with programming in Python and made some good progress. I spent some time then learning more about python and wrote some more code using their gtk+ libraries to build a gui window using the spin buttons to control the pwm value to drive the Servo-PWM Hat.

![](https://forum.processing.org/two/uploads/imageupload/916/N5QQA7DFMTPJ.png)

I see a tremendous amount of libraries within Processing to let me do the same thing. So I'm looking forward to practice with this and code some more examples. I started using some of the libraries already contained in the examples for Processing to build something similar to this.

But I'm not sure how yet to go about converting the python test code they use into Processing code. There are several lines of code in there which I'm not familiar how it can be done using Processing https://github.com/adafruit/Adafruit_Python_PCA9685/blob/master/examples/simpletest.py

I guess it's safe to say that a library has to be created first. Just as I see with the python library that is used by Adafruit. So this would have to be ported as well over to Processing. https://github.com/adafruit/Adafruit_Python_PCA9685/blob/master/Adafruit_PCA9685/PCA9685.py

Has somebody tried programming this using Processing already ?

**Comment by gohai** [comment] 2016-06-28 09:16
Hi @Ragooman,

I haven't used the Servo/PWM Pi hat myself, but after a cursory look at the Python source you linked to, it appears to be controlled via the I2C bus - which is available through Processing's IO library, so you should be able to control it from within a Processing sketch.

Have a look at the I2CDigitalAnalog example, as well as I2CDigitalAnalogOOP for how this can be done. (Both sketches have the same functionality, the latter just shows how to do this nicely in an object-oriented way, by extending the I2C class.)

In your case, you'd be using the address [0x40](https://github.com/adafruit/Adafruit_Python_PCA9685/blob/master/examples/simpletest.py#L16). And you'd have to implement [these calls](https://github.com/adafruit/Adafruit_Python_PCA9685/blob/master/Adafruit_PCA9685/PCA9685.py#L96) basically in such a a way (same structure as on Arduino):

    beginTransmission(0x40);
    write(0x00);  // MODE1
    write(newmode);
    endTransmission();

Of course, it might be handy to create a (local) equivalent (= helper function) for `self._device.write8` for this..

Let me know if you hit any obstacles, and if you manage to get it to work let us know, since this could be really handy for other users as well!

**Comment by Ragooman** [comment] 2016-06-30 03:11
I see.
Yes, I started looking through your github files to get an overview of how it can be programmed with Processing[java]. I guess the Processing extension of java doesn't apply here since it's strictly bare metal programming. It's just that Java is still new to me. My background is mostly hardware, but I like to code in C too. My daughter is in college and took some Java classes, so I could probably pick up some pointers from her too. The OOP features of java is something I have to get a handle on still. But I think this work on the RPi will be worth it. I keep reading how Processing is much faster than Python when coding with a lot of math, which I foresee in my next robot project. Since Java is using a bytecode compiler versus the python interpreter.,

**Comment by gohai** [comment] 2016-07-29 11:08
Closing, since it's not a bug, or something we'd carry in Processing itself. @Ragooman if you get around implementing this, please ping me!

**Closed by gohai** 2016-07-29 11:08 UTC
Labels: arm, enhancement
