### ISSUE TITLE
Welcome Message checkbox don't work

### ISSUE THREAD

**Issue by tolkanabroski** [processing/processing#5128] opened 2017-06-14 10:36 UTC
I'm on Windows 10 using Processing Version <=3.3.3 x64bit and the checkbox for Show Welcome Message does nothing.

![alt text](https://gifyu.com/images/pref_processing.gif)

**Comment by benfry** [comment] 2017-06-14 13:11
Duplicate of https://github.com/processing/processing/issues/3911

**Closed by benfry** 2017-06-14 13:11 UTC
