### ISSUE TITLE
Super small UI texts on high DPI Windows devices

### ISSUE THREAD

**Issue by unparadise** [processing/processing#4759] opened 2016-12-02 19:40 UTC
I am assuming that I am not the only one that uses Processing IDE on a high DPI Windows 10 devices (Surface Pro 4). The UI texts in the IDE are so small that they are really hard to read. It essentially makes it not usable on my Surface Pro. I tried to change the text size in the Windows setting. I normally set it to 200% and that setting works with most of the other apps. I increased that setting to 300% for Processing IDE, the UI texts are still really small.

![3ur4uqhnbv2k](https://cloud.githubusercontent.com/assets/6435661/20847708/16497a06-b884-11e6-89e0-efaebbe752d6.PNG)

**Comment by benfry** [comment] 2016-12-03 21:23
Duplicate of https://github.com/processing/processing/issues/2411

**Closed by benfry** 2016-12-03 21:23 UTC
