### ISSUE TITLE
SVG loadshape error

### ISSUE THREAD

**Issue by charly4710** [processing/processing#5814] opened 2019-03-12 09:29 UTC
SVG loadshape error

## Description
loadshape() gives error for certain SVG files.

Error message:
parsed: m,51.4,41.9,c,0,.1,-.1.2,-.2.1,s,-.2,-.2,-.2,-.4.1,-.2.2,-.1,c
unparsed: .1.2.2.3.2.4,z
RuntimeException: shape command not handled: .1.2.2.3.2.4

The svg's in question are created with icograms.com, and are perfectly readable with browsers and with Inkscape.

It appears that processing gets hung up on certain elements in the svg, as the error appears when I add these elements.

* Processing version: 3.5.3
* Operating System and OS version: windows 10

attached processing code and svg file

[citysvg.zip](https://github.com/processing/processing/files/2956062/citysvg.zip)

**Comment by Prometal328** [comment] 2019-11-18 16:57
*I've checked this ISSUE, it's behavior is quite interesting:*
- I *removed* all the lines that were giving the **"parsing error"**, and I got an **ArrayIndexOutOfBoundsException: 32** error. 
- This might be related to the ISSUE #5935.
- You can temporarily solve this ISSUE by converting with **inkscape** the *".svg"* file in to a *".png"* file *(or directly download it as .png from icograms.com)*, and change object's type from **PShape** to **PImage** *(but you need to resize the image in setup to prevent lag)*

**Comment by jeremydouglass** [comment] 2019-12-18 03:26
Yes, this is almost certainly related to 4935 and SVG support being "incomplete by design." The SVG spec is absolutely huge; many SVG files with advanced features will not be parse-able by `loadShape()`

**Comment by benfry** [comment] 2020-01-18 00:51
Closing as duplicate of https://github.com/processing/processing/issues/5935… Unless someone wants to make a patch to handle leading `.` characters in numbers. I thought that was covered, but perhaps not.

**Closed by benfry** 2020-01-18 00:51 UTC
