### ISSUE TITLE
Above certain P2D PGraphics size, glitches start happening

### ISSUE THREAD

**Issue by bojanbjelic** [processing/processing#2836] opened 2014-08-31 19:35 UTC
Above certain P2D PGraphics size, glitches start happening.
If the PGraphics is 3000 times 5000 it'll be OK, but above glitches start.

Here's an example:

```
void setup() {
  String file = "t" + random(1000);
  size(100, 100, P2D);
  background(0);
  noLoop();
  PGraphics g = createGraphics(5000, 5000, P2D, "temp");
  g.beginDraw();
  g.background(#eeeeee);
  g.endDraw();
  g.save(file);
  println(file);
  exit();
}
```

The file attached is scaled down, but you can see that even when the background is set and nothing is drawn, the image comes up as a glitch.

![t994 83795](https://cloud.githubusercontent.com/assets/1333579/4102965/401bfc0a-3145-11e4-9aee-8c7d56d6cc3a.png)

**Comment by codeanticode** [comment] 2015-08-03 15:04
@bojanbjelic much has changed in the opengl renderer since 2.2.1. Have you had the chance to run your code on 3.0 alpha 11 to see if you still get the same result? We tried on a few different machines using alpha 11 and were not able to reproduce the issue.

**Comment by codeanticode** [comment] 2015-08-04 22:42
closing this issue as I cannot reproduce it, and original poster hasn't updated it.

**Closed by codeanticode** 2015-08-04 22:42 UTC
Labels: opengl
