### ISSUE TITLE
 Error message with noLoop() and P2D renderer.

### ISSUE THREAD

**Issue by radeise** [processing/processing#3558] opened 2015-08-09 09:33 UTC
Error message when closing the sketch.
Processing 3.0b1 under OS X 10.10.4.

```processing
void setup() {

	size(500,500,P2D);
}

void draw() {

	noLoop();
}
```

Thank ! :rooster::metal:

**Comment by benfry** [comment] 2015-08-09 11:43
How are you closing the sketch? I can't get an error with the close box, hitting escape, or hitting stop on OS X and b1.

**Comment by radeise** [comment] 2015-08-09 13:26
You are right, the error appears just with cmd+Q method.

message : 
>
> A fatal error has been detected by the Java Runtime Environment:
>
> SIGSEGV (0xb) at pc=0x00007fff8eaac4bd, pid=9288, tid=63503
>
>JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
>Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode bsd-amd64 compressed oops)
>Problematic frame:
>C  [libGL.dylib+0x14bd]  glDeleteTextures+0x12
>
>Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c >unlimited" before starting Java again
>
>An error report file with more information is saved as:
>/Users/olivier/hs_err_pid9288.log
>
>If you would like to submit a bug report, please visit:
>  http://bugreport.java.com/bugreport/crash.jsp
>The crash happened outside the Java Virtual Machine in native code.
>See problematic frame for where to report the bug.
>
>Could not run the sketch (Target VM failed to initialize).
>Make sure that you haven't set the maximum available memory too high.
>For more information, read revisions.txt and Help → Troubleshooting.

**Comment by codeanticode** [comment] 2015-09-04 06:53
I cannot reproduce with latest revision (on 10.9.5) @radeise do you still see this issue in beta 5?

**Comment by radeise** [comment] 2015-09-04 07:53
I have no more problems with this version. It had to be repaired with fixes on P2D.

**Comment by codeanticode** [comment] 2015-09-04 11:28
Cool, thanks for checking!

**Closed by codeanticode** 2015-09-04 11:28 UTC
Labels: opengl
