### ISSUE TITLE
Menu mnemonics (alt-f, etc) getting typed into the editor

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3057] opened 2015-01-24 16:20 UTC
When pressing shotcuts for the menubar , the key also gets typed into the editor.
Steps to reproduce :  
1. Open processing
2. Press Alt + F
The file menu opens but "f" gets typed into the editor.

**Comment by hamoid** [comment] 2015-01-28 10:42
I don't remember ever having such shortcuts in Processing under Linux. Are those shortcuts OS dependent?
What I have seen lately is that sometimes I press CTRL+X and the console prints "cut".

**Comment by Akarshit** [comment] 2015-01-28 13:13
They were added recently and i also saw the that cut is getting printed in the console.  
But i am not able to build processing right now so i cant do anything about it.

**Comment by GKFX** [comment] 2015-01-28 18:27
@hamoid I have fixed the "cut" error. I haven't committed yet because the latest code won't build on my machine so I can't do good tests.

**Comment by hamoid** [comment] 2015-01-28 18:55
@GKFX great! I know there are many changes going on at the moment.
BTW. While fixing this, did you notice why it could happen that CTRL+C and CTRL+X suddenly would stop working? I can not reproduce it, but lately it has happened two or three times. I can solve it by closing and opening Processing. I suspected that the println("cut") was there to debug this issue I'm having at times.

**Comment by GKFX** [comment] 2015-01-28 19:03
No, I didn't. The `println("cut");` was added to debug moving from a cut ActionListener to a full CutAction, which allows menu dimming. When you say stop working, do you mean they went dim/inactive when they should have remained active? They are supposed to only gray out when there is no text selected.

**Comment by hamoid** [comment] 2015-01-28 20:37
It didn't occur to me to look at the menues to see if they were dimmed/inactive. I would just press CTRL+X for instance, but nothing would happen. The text would remain there, and the clipboard would keep it's old value. If it happens again I'll look at the menues.

**Comment by hamoid** [comment] 2015-01-28 20:50
I think I found it. I click on the Edit menu to open it, click again to close it without choosing anything. CTRL+X does not work. Click twice again on Edit, CTRL+X is back.

**Comment by GKFX** [comment] 2015-01-28 21:30
OK, I think I understand how to fix it. It sounds a little fiddly though so I'll wait until the cofde is more stable before I do any work.

**Comment by benfry** [comment] 2015-04-01 20:01
Fixed for 3.0a6.

**Closed by benfry** 2015-04-01 20:01 UTC
