### ISSUE TITLE
Use of lambda expressions in Processing 3

### ISSUE THREAD

**Issue by markusand** [processing/processing#3963] opened 2015-10-06 07:56 UTC
As far as I know Processing 3 is using Java 8, and this version of Java included lambda expressions to use in predicate. However, when trying to use them the compiler returns an error all the time.

`ArrayList<Measure> subset = dataSet.filter(m -> { m.getTemp() == 20 && t.getHumid()<=80 });`
Error: unexpected token:>

Is this function implemented in Processing 3 or am I doing something wrong?

**Comment by benfry** [comment] 2015-10-06 12:36
Duplicate of https://github.com/processing/processing/issues/3054

**Closed by benfry** 2015-10-06 12:36 UTC
