### ISSUE TITLE
Unclutter /tmp

### ISSUE THREAD

**Issue by ascherer** [processing/processing#5149] opened 2017-06-23 09:04 UTC
Processing leaves tons of temporary stuff in `/tmp`, i.e., subdirectories with names like
* `untitled980258163230906404sketches`
* `sketch_170616a835292803113790550temp`
* `Synthesis38309592966653010129temp` (`Synthesis` being a sketch name)

**Comment by GKFX** [comment] 2017-06-23 09:58
Duplicate of #1896.

**Closed** 2017-06-23 10:00 UTC
