### ISSUE TITLE
OpenGL Drawing to large

### ISSUE THREAD

**Issue by clankill3r** [processing/processing#3327] opened 2015-05-27 13:26 UTC
3.09a

````java
void setup() {
  size(150, 150, OPENGL);
}

void draw() {
  
  width = 75;
  height = 75;
  
  background(255, 0, 0);
  stroke(255);
  line(0, 0, width, height);
  strokeWeight(5);
  line(0, height, width, 0);
}
````

You can see a little from the line in the right top and left corner.

![screen shot 2015-05-27 at 3 25 33 pm](https://cloud.githubusercontent.com/assets/738650/7836988/b4c669d8-0484-11e5-86bd-8f2612cf8c7d.png)

**Comment by codeanticode** [comment] 2015-05-29 17:22
are you on a retina machine?

**Comment by clankill3r** [comment] 2015-05-29 20:41
yes, sorry I didn't mention.
OSX 10.10.3

I also tried with "processing.core.PGraphicsRetina2D" but that doesn't seem to work (not that I want retina pixels).

p.s. I love what you are doing :)

**Comment by clankill3r** [comment] 2015-05-29 20:51
I did not now about P3D_2X untill today but this is the result with that:

![screen shot 2015-05-29 at 10 50 22 pm](https://cloud.githubusercontent.com/assets/738650/7892494/25c46b04-0655-11e5-8c21-92fdab6509b0.png)

**Comment by codeanticode** [comment] 2015-05-29 20:58
Thanks! 

This seems a duplicate of https://github.com/processing/processing/issues/3332, so I'm going to close it.

Just noticed that you are assigning values to width/height in draw(), you shouldn't be doing that since those variables are set internally by Processing.

**Closed by codeanticode** 2015-05-29 20:58 UTC
Labels: macosx

**Comment by clankill3r** [comment] 2015-05-29 21:10
I assigned values to width and height to see if it fixed anything and I forgot to remove it before posting here. Anyway, I think this is animation is really cool :D
````java
void setup() {
  size(150, 150, P3D_2X);
}

void draw() {
  
  width = (int) (noise(frameCount)*155);
  height = (int) (noise(frameCount)*155);
  
  background(124);
  ellipse(75, 75, width, height);
}
````
