### ISSUE TITLE
Processing Java + Sublime Text 3 

### ISSUE THREAD

**Issue by PronoZombro** [processing/processing#4477] opened 2016-05-15 23:14 UTC
Hello guys!! 
I have this problem with processing java and sublime text 3 on mac El Capitan 10.11.4. I cannot build anything in sublime text 3 because the processing java path is different from what it used to be. It is in usr/local/bin and not in usr/bin. I read about this issue in this forum and one way to fix this is to install the package "fix mac path". but it didn't work at all. It is still the same problem. I have to say that I am actually a total newbie to all this so most of the solutions I don't understand. I installed the latest processing version and the latest sublime text version. 
This is what I always get. 

[Errno 13] Permission denied
[cmd:  [u'processing-java', u'--force', u'--sketch=/Users/Prono/Desktop/sketch_160516a/build', u'--output=/Users/Prono/Desktop/sketch_160516a/build/build-tmp', u'--run']]
[dir:  /Users/Prono/Desktop/sketch_160516a/build]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Prono]
[Finished]

**Comment by StanLepunK** [comment] 2016-05-16 07:12
Just copy Processing-Java in in the good folder, but anyway the Processing-Java from Processing 3.1doesn't work with Sublim 3 you must wait the next release of Processinf 3.1.1
https://github.com/processing/processing/issues/4461
and 
https://github.com/processing/processing/issues/3740
I think you can close this issue.

**Comment by benfry** [comment] 2016-05-16 11:08
Duplicate of https://github.com/processing/processing/issues/4452

**Closed by benfry** 2016-05-16 11:08 UTC
