### ISSUE TITLE
Demos/Graphics/Wiggling regressed from 17 fps to 8.3 fps between a11 and b1

### ISSUE THREAD

**Issue by gohai** [processing/processing#3561] opened 2015-08-09 15:12 UTC
Please close if this is a known.. FPS in the demo halved for me on the Raspberry Pi using the new Mesa driver. @JakubValtar?

**Comment by JakubValtar** [comment] 2015-08-09 17:09
Hi @gohai,

do all faces in the Wiggling example you've been running have circular holes in them or only three of them? I'm trying to figure out if you are using the old version or the new version, because I updated this example recently.

Could you please copy and paste [this version](https://gist.github.com/JakubValtar/aea1645a8c36ca2de7a6) into both 3.0a11 and 3.0b1 and tell me how fast it is?

**Comment by gohai** [comment] 2015-08-09 18:40
Hi @JakubValtar, greetings from Vídeň!

I tried with the version you linked: it's 8 fps on 3.0b1 and 22 fps on 3.0a11. Looks similarly visually.

**Comment by JakubValtar** [comment] 2015-08-10 01:14
Thanks @gohai :)

(Un)fortunately, both releases run the same on my machine. If you have some time, I'd like to ask you for help.

I identified some changes which could cause the framerate drop and I need you to test which one it was. Could you please build the repo at these commits and report the framerate?
9550918099745acf34f4f362dcb1b909ea692f9a
15f4f42119e1b13132eba84a7ad31991b3559447
f0691c08abdc760e0cec5b043b3f1de31bd2368d

It's okay if you don't have time for this, but I can't solve it without identifying the commit which caused it (and you seem to be only one running on Pi).

**Comment by gohai** [comment] 2015-08-10 09:14
71c688d5585c23ae3b521178b41349d6f98c3253 already has the low fps with the updated sketch you linked, skipping the other commits.

Since I had to manually make a few changes to the commit to get it to run on the Pi (updated build.xml, new JOGL, two shader hacks), I am now also trying plain a11 with the same modifications on top, to be sure.

**Comment by gohai** [comment] 2015-08-10 09:33
I quickly disabled SAVE_SURFACE_TO_PIXELS_HACK in 71c688d5585c23ae3b521178b41349d6f98c3253, and yes, it's that very commit (got 21+ fps).

Is there a way to establish whether this hack is needed on a particular platform? If not, could we potentially disable it on the underpowered Pi? (@codeanticode)

Thanks!

**Comment by benfry** [comment] 2015-08-11 20:48
From the looks of https://github.com/processing/processing/issues/3559 it seems like `SAVE_SURFACE_TO_PIXELS_HACK` may not even be working as intended. But I think @codeanticode has some ideas about how to fix this. Who's taking this one?

**Comment by JakubValtar** [comment] 2015-08-11 20:55
We are working together with @codeanticode on it.

**Comment by gohai** [comment] 2015-08-12 22:41
@JakubValtar @codeanticode It'd be fantastic if any new scheme would also have a path for [GLES2](https://github.com/processing/processing/blob/master/core/src/processing/opengl/PJOGL.java#L2637)!

**Comment by codeanticode** [comment] 2015-08-13 15:19
Hey guys, [this commit](https://github.com/processing/processing/commit/eeb9deccb2601793fd3e19b015f956d9da14954f) should solve most of the problems. 

@gohai could you test if things work as expected and without framerate drop?

@JakubValtar could you test static sketches on integrated intel?

**Comment by gohai** [comment] 2015-08-13 17:14
Getting 21 fps with https://github.com/processing/processing/commit/eeb9deccb2601793fd3e19b015f956d9da14954f. Thanks @codeanticode! I'll test tomorrow with the binary driver.

**Comment by codeanticode** [comment] 2015-08-13 17:38
Excellent! Do you see any unintended side effects? Can you run static sketches (no draw() function, or noLoop()) without artifacts (particularly, window turning black after the first frame)?

**Comment by gohai** [comment] 2015-08-13 17:40
Will try tomorrow!

**Comment by JakubValtar** [comment] 2015-08-13 22:21
@codeanticode does not work :(((

Just white screen
```processing
public void settings() {
  size(200, 200, P2D);
}

public void setup() {
  background(255);
  fill(255);
  rect(10, 10, 80, 80);
}

public void draw() { }
```

Swaps the image and black
```processing
public void settings() {
  size(200, 200, P2D);
}

public void setup() {
  background(255);
  fill(255);
  rect(10, 10, 80, 80);
  noLoop();
}

public void draw() { }
```

Displays the image, no flickering
```processing
public void settings() {
  size(200, 200, P2D);
}

public void setup() {
  background(255);
  fill(255);
  rect(10, 10, 80, 80);
}

public void draw() {
  background(255);
  fill(255);
  rect(10, 10, 80, 80);
}
```

Swaps the image and default background gray
```processing
public void settings() {
  size(200, 200, P2D);
}

public void setup() {
  background(255);
  fill(255);
  rect(10, 10, 80, 80);
}

public void draw() {
  background(255);
  fill(255);
  rect(10, 10, 80, 80);
  noLoop();
}
```

**Comment by gohai** [comment] 2015-08-15 18:15
Still want me to test anything?

**Comment by JakubValtar** [comment] 2015-08-15 19:31
Thanks for the offer!

We don't have anything right now. I'll let you know once we solve the flickering without the hack.

**Comment by codeanticode** [comment] 2015-09-08 03:53
fixed with https://github.com/processing/processing/commit/3b8768165645a82ba87fcb15ab569f37f9d6efcc, https://github.com/processing/processing/commit/abe7b52e1ec33c5d86ed5fbf64980ee7f3bc9703 and https://github.com/processing/processing/commit/ea13eda65db426d0f6d47c695825667752627192

**Closed by codeanticode** 2015-09-08 03:53 UTC
Labels: opengl
