### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jsundram** [processing/processing#4375] opened 2016-03-28 03:44 UTC
I repeatedly get exceptions while editing (not running) my sketch (using Python mode, if that makes a difference): `Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException`

This seems to make the editor behave kind of oddly (some keystrokes to move the cursor around don't work, Cmd-A to select all doesn't work). This is on 3.02a

**Comment by GKFX** [comment] 2016-04-13 16:48
Wasn't there a stack trace? It looks like a duplicate of https://github.com/processing/processing/issues/1940#issuecomment-201439573 but it's hard to  be sure without one.

**Comment by benfry** [comment] 2016-05-08 18:17
Maybe a Python Mode bug? Without a longer stack trace there's nothing we can do to begin looking into this.

**Closed by benfry** 2016-05-08 18:17 UTC
