### ISSUE TITLE
Cross Platform support

### ISSUE THREAD

**Issue by ajavamind** [processing/processing#6186] opened 2021-06-16 14:35 UTC
Feature Request: 
Processing does a good job of running a sketch across multiple platforms: Windows, Android, MacOS, and Linux.
However I often run into problems with minor code issues in Android that prevent my sketch from compiling. I am forced to comment out some Java code and replace it with Android code and vice versa depending on the platform. Usually this is a very small part of a sketch. These sketch incompatibilities may eventually be fixed in subsequent updates, but often I can't wait. A library may only exist on one platform so include statements fail.

Often I will develop a sketch first on a Windows PC in Java mode, and then adapt it to Android. I also want to run the sketch on MacOS and Linux. 

**Would you please consider adding a meta comment in the source code of the first line of a PDE file indicating to include that file in a build only when it matches the mode being compiled.**

Something like:
//@Java
//@Android
//@MacOS
//@Linux

This feature request would allow sketch writers to isolate their platform dependent code in a single PDE file without needing to change or replace any lines to get it to compile.

**Comment by benfry** [comment] 2021-06-16 15:44
Duplicate of https://github.com/processing/processing/issues/1637

**Closed by benfry** 2021-06-16 15:44 UTC

**Comment by ajavamind** [comment] 2021-06-16 17:37
Sorry, somehow my searches missed issue [ #1637  posted in 2013 ](https://github.com/processing/processing/issues/1637)
