### ISSUE TITLE
Print (in file menu) prints empty pages.

### ISSUE THREAD

**Issue by kasperkamperman** [processing/processing#3881] opened 2015-09-26 20:58 UTC
OSX 10.10.5, Processing 3.0b7

I tried to print my code in the IDE, however I just get 5 blank pages (also tried print to PDF). 

My code length is 207 lines and I have multiple tabs with code (I suppose the active tab is printed normally?).

**Comment by benfry** [comment] 2015-09-28 14:03
Duplicate of https://github.com/processing/processing/issues/213

**Closed by benfry** 2015-09-28 14:03 UTC
