### ISSUE TITLE
example code does not do what it says it does in the sketch description

### ISSUE THREAD

**Issue by FrankOcean11** [processing/processing#4342] opened 2016-02-29 17:04 UTC
im not sure if there is a bigger problem to what i can see or if this was a simple mistake by the one who made this available to anyone downloading the libraries from the install manager ?

both of this examples aren't working at all though i must say they do compile, they just dont do what it says it should plus one was missing a library.

would love to hear back from someone about this getting attention please i really can learn alot from this code and i spent 6 hours starring down at this code wondering what can be wrong and i could not figure it out. "fresh eyes needed" thanks in advance team!

this came from v2.2.1
![f7468de2-dc79-11e5-9c08-a507b8eff732](https://cloud.githubusercontent.com/assets/10504709/13402012/6beb05e2-dedc-11e5-99c2-9c7d2ae2ecc5.PNG)
 please check out the processing sketch

**Comment by alignedleft** [comment] 2016-03-02 13:47
Duplicate of https://github.com/processing/processing-docs/issues/399

**Closed by alignedleft** 2016-03-02 13:47 UTC
