### ISSUE TITLE
Processing 3.3.4 Linux Won't Load

### ISSUE THREAD

**Issue by toliaferrode** [processing/processing#5148] opened 2017-06-23 05:08 UTC
I try to load processing:
"./processing"

The error I get:
"java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory"

I'm on Ubuntu Linux, 64-bit.

**Comment by GKFX** [comment] 2017-06-23 10:00
Duplicate of #5111.

**Closed** 2017-07-22 07:37 UTC
Labels: duplicate
