### ISSUE TITLE
keyPressed() problems with keys that have special press-and-hold behavior macOS Sierra

### ISSUE THREAD

**Issue by eric-souther** [processing/processing#4952] opened 2017-03-08 14:58 UTC
void keyPressed() is not reading key presses or only intermittently. Tried exact same code on OS X El Capitan and on Windows 10 and it worked perfectly.

**Comment by a11ce** [comment] 2017-04-26 14:11
For me, it works for about 30 seconds, freezes for 10, then repeats

**Comment by benfry** [comment] 2017-04-26 18:21
Is it just the key repeating? (When typing, if you click and hold a letter, most apps will start printing more of that letter. This is done by the OS.) Try doing a `println()` inside a `keyPressed()` and a `keyReleased()` function and see if they're called repeatedly.

**Comment by benfry** [comment] 2017-04-26 18:22
And what's the code to reproduce the problem? What renderer are you using?

**Comment by benfry** [comment] 2017-05-04 18:37
Hm… I can't reproduce this on a macOS Sierra machine. Can anyone help here?

**Comment by vormplus** [comment] 2017-05-05 13:28
I also can't reproduce this bug on macOS Sierra. Tested with all renderers and everything seems to work as expected.

**Comment by benfry** [comment] 2017-05-05 20:44
Ok, thanks; gonna close this for now. We can re-open if anyone can confirm.

**Comment by HolgerGottChriestensen** [comment] 2017-05-12 23:32
I am having the exact same problem with OS X sierra.
It seems to have something to do with the holding down of buttons making you able to type ß ś š from the s key. 
I was able to replicate the issue using a few lines of code:
```
void draw(){

}

void keyPressed(){
  println("pressed: " + key);
}

void keyReleased(){
  println("released: " + key);
}
```

By holding down a key with the other letter options like 's' for 3-5 sekunds and the releasing it does not call the keyPressed() event. From that point it only detect releases. If you then hold down a button that does not have those alternative letters like 'q' for 3-5 seconds it will start to detect the events again. I hope this was helpfull and can be fixed soon :) .

Holger

**Comment by jeremydouglass** [comment] 2017-05-13 08:14
Sounds like #5033 (and #5048 and #4952 etc.) again?

**Comment by HolgerGottChriestensen** [comment] 2017-05-13 13:30
I don't see the connection but maybe.

**Comment by a11ce** [comment] 2017-05-13 17:17
@HolgerGottChriestensen you're absolutely right, I changed my program to use non-accentable keys and it works fine.

**Comment by HolgerGottChriestensen** [comment] 2017-05-13 20:58
@a11ce you can only change that manually through the terminal right? 
`defaults write -g ApplePressAndHoldEnabled -bool false`
Wonder if there is a better way

**Comment by benfry** [comment] 2017-05-14 11:02
Re-opening and changing the title based on the actual issue. 

Not sure what's happening here since it's new Apple behavior—i.e. whether we'll be able to avoid it or not. Help wanted…

In the meantime, you can use the `defaults write -g ApplePressAndHoldEnabled -bool false` command or change the setting in System Preferences.

**Comment by StanLepunK** [comment] 2017-06-01 11:32
I write this little code to test the keyPressed behavior on OS sierra / P 3.3.3.
That's work with `SPACE` `RETURN` `TAB` `UP` `DOWN` `RIGHT` `LEFT` `DELETE`at each 5 frames, but not with `SHIFT` `ALT` `CMD` and obvioulsy not with the other key touch.


```
void draw() {
  println(frameCount, "draw") ;
}

int count_k ;
void keyPressed() {
  count_k++ ;
  println(count_k, "void keyPressed") ; 
}
```

**Comment by benfry** [comment] 2017-06-03 13:36
Added to the troubleshooting page, and I'll make a note in the reference as well: https://github.com/processing/processing/wiki/Troubleshooting#key-repeat-on-macos-sierra

Appears that it's all we can do, so I'll close this.

**Closed by benfry** 2017-06-03 13:36 UTC
Labels: help, macosx

**Comment by JaiWyn** [comment] 2018-08-18 11:05
Probably not the best way, but if you convert the` void keyPressed() {} `into an `if (keyPressed) {}` inside the `void draw()` then it will change whatever value you're changing consistently as long as your framerate is healthy.

**Comment by benfry** [comment] 2018-08-30 16:12
I wouldn't recommend that for most scenarios—it'll just fire events along with the frame rate.
