### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by FrankOcean11** [processing/processing#4212] opened 2015-12-21 05:43 UTC
i was trying to test the sound example after downloading its library to my pc, then this error 

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (0x20474343), pid=2784, tid=7256
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [KERNELBASE.dll+0x871c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Franks\AppData\Local\Temp\\hs_err_pid2784.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.
```

**Comment by JakubValtar** [comment] 2015-12-29 11:16
Hi @FrankOcean11, thanks for your report. Which example it was?

Could you please upload the `C:\Users\Franks\AppData\Local\Temp\\hs_err_pid2784.log` file as an attachment? Just remane it as .txt for GitHub to accept it. We need it to figure out what happened.

**Comment by FrankOcean11** [comment] 2015-12-29 19:10
theres no such hs_err_pid2784 in my temp folders

**Comment by JakubValtar** [comment] 2016-01-01 21:11
Ah, the log file was probably deleted already. If this hapens again, could you please look for the log file and post it here? It would help us a lot, otherwise we don't know where the crash happens.

**Comment by JakubValtar** [comment] 2016-01-01 21:14
Looks like a duplicate of https://github.com/processing/processing-sound/issues/57, please follow up there.

**Closed by JakubValtar** 2016-01-01 21:14 UTC

**Comment by vipaksha** [comment] 2016-12-31 06:50
[java_error_in_STUDIO_2447.txt](https://github.com/processing/processing/files/679506/java_error_in_STUDIO_2447.txt)



plz...help me slov this error
