### ISSUE TITLE
text not rendering in P3D mode

### ISSUE THREAD

**Issue by nalcus** [processing/processing#2482] opened 2014-04-28 13:30 UTC
Text displays perfectly in default rendering mode. Does not display in P3D mode...

I am running windows 7 64bit.

I have tried Processing versions 2.1.1 as well as 2.1.2, both 32-bit and 64bit versions (still within a 64 bit operating system context), and I get the same issue as in this screenshot:

![3dtextissue](https://cloud.githubusercontent.com/assets/7197872/2817306/b8764a32-ced7-11e3-9ac0-12a1f82aaef7.png)

http://oi58.tinypic.com/riwv11.jpg

```Processing
// this code displays text
void setup () {
 size (200, 200);
}

void draw() {
  background(0);
  fill(255);
  textSize(20);
  text("text",30,30);
}
```

```Processing
// this code does not display text
void setup () {
 size (200, 200, P3D);
}

void draw() {
  background(0);
  fill(255);
  textSize(20);
  text("text",30,30);
}
```

**Comment by codeanticode** [comment] 2015-06-02 18:57
@nalcus can you confirm if this still happens in 3.0a9? Thanks!

**Comment by codeanticode** [comment] 2015-06-03 12:49
No updates from original poster and cannot reproduce, closing.

**Closed by codeanticode** 2015-06-03 12:49 UTC
Labels: opengl
