### ISSUE TITLE
Crash when using fullScreen(P3D,2) when monitor configuration changed.

### ISSUE THREAD

**Issue by jbum** [processing/processing#3788] opened 2015-09-11 18:01 UTC
I had a sketch that I was using the following to run fullscreen on a second monitor.

fullScreen(P3D, 2);

I switched to an environment where there was a single monitor (mirrored to a projector, probably at a different resolution than I normally use), ran the scratch and java crashed.  Then I commented out the line and replaced it with

fullScreen(P3D, 1);

and when that crashed, I tried,

size(1600,900, P3D);

And the sketch continued to crash (Preferences were set to use Display 1, but for a potentially different monitor size).  Restarting processing did not  help.  After I went back to my normal 2-screen environment, the sketch works again.

**Comment by jbum** [comment] 2015-09-11 18:01
This was on a Macintosh.

**Comment by benfry** [comment] 2015-09-11 18:40
What do you mean "it crashed"? The sketch stopped running? Processing quit? Your machine turned off?

**Comment by jbum** [comment] 2015-09-11 18:54
The sketch stopped running and the system pop-up dialog showing a crash log
appeared.  I'll reproduce shortly and send the stack trace from the
crash-log.

**Comment by benfry** [comment] 2015-09-11 19:31
A crash here shouldn't really be possible, but it's possible that P2D/P3D aren't checking to make sure that the display is available.

**Comment by codeanticode** [comment] 2015-09-11 20:48
I tried to reproduce it on Mac 10.9.5, using beta 5 and the latest revision from the repo, but did not observe any native crash.

I first run fullScreen(P3D, 2) on a dual monitor setup, and then switched to a mirrored display config (laptop + projector) and run the sketch again. The output was shown as fullscreen on both the laptop screen and the projector, with this error message in the console:

```Display 2 does not exist, using the default display instead.
Display 1 is Monitor[Id 0x500cc35 [primary], 637 x 398 mm, pixelScale [1.0, 1.0], viewport [ 0 / 0  1280 x 800 ] [pixels], [ 0 / 0  1280 x 800 ] [window], orig [Id 0x0, [ 1280 x 800 pixels x 32 bpp ] @ 60.0 Hz, flags [], 0 degr], curr [Id 0x0, [ 1280 x 800 pixels x 32 bpp ] @ 60.0 Hz, flags [], 0 degr], modeChanged false, modeCount 176]
```

which is expected, since display 2 is not available. As I related thing, I could tweak the message so only the display resolution is printed out.

@jbum what version of Processing are you using?

**Comment by jbum** [comment] 2015-09-11 20:54
@codeanticode I am using 3.0b5.

I just tried to reproduce in the same conference room where the crash
occurred (it was during a lecture).  This time, no crash.  Meh.  Also tried
running all the other stuff I was running at the same time (Keynote,
Puredata).  Bummed I didn't capture the error log when it happened, since
it doesn't seem easily reproduced.

Its certainly possible the fullScreen() issue is a red herring - it just
seemed like the most likely culprit at the time, since the crash occurred
on sketch startup.

**Comment by codeanticode** [comment] 2015-09-16 16:06
Hi @jbum, do you think is it safe to close this issue? Where you able to reproduce?

**Comment by jbum** [comment] 2015-09-16 16:45
Unable to reproduce - go ahead and close it - thanks!

**Closed** 2015-09-16 17:02 UTC
Labels: opengl

**Comment by benfry** [comment] 2015-09-16 18:47
Let us know if you see anything like this again... Running on a projector is an important use case, both for teachers and people demonstrating work, so we take these really seriously.
