### ISSUE TITLE
Calling noSmooth in a P2D or P3D causes massive bug

### ISSUE THREAD

**Issue by bennyHacker** [processing/processing#6053] opened 2020-05-31 15:52 UTC
I noticed my sketch suddenly became unable to produce new "frames" (the screen was gray, and any new image was immediately replaced with a gray screen). This was fixed when I commented out noSmooth();

To reproduce

1. create sketch in P3D or P2D
2. call noSmooth();
3. try rendering PGraphics and PImages

**Comment by 2016James** [comment] 2020-06-01 01:20
how to unsubscribe this trend?

Bennett Hack <notifications@github.com> 于2020年5月31日周日 下午11:52写道：

**Comment by jeremydouglass** [comment] 2020-06-01 01:52
Can't reproduce on Processing 3.5.4, macOS 10.12.6.
P2D + noSmooth + PImage worked fine.

```
PImage img;
void settings() {
  size(600, 600, P2D);
  noSmooth();
}
void setup() {
  img = loadImage("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Processing_3_logo.png/600px-Processing_3_logo.png");
}
void draw() {
  image(img, 0, 0);
}
```

**Comment by bennyHacker** [comment] 2020-06-01 01:59
I'll try to create a working example that covers this bug more thoroughly

**Comment by benfry** [comment] 2020-09-23 23:58
No updates; closing.

**Closed by benfry** 2020-09-23 23:58 UTC
