### ISSUE TITLE
Won't open - 3.0a10

### ISSUE THREAD

**Issue by calebccff** [processing/processing#3458] opened 2015-07-07 13:17 UTC
When I run it a sketch, most of the time it doesn't load, by making all my functions print their function name and displaying the frame count draw() stops anywhere between 10 and 30 frames and the sketch window never opens, it gives the impression that Processing encounters an internal error with running draw() and stops, there is no error message. Hopefully this will be fixed by the next update. Thanks for and amazing piece of software, good luck.

**Comment by joelmoniz** [comment] 2015-07-07 13:29
I think this is the same as the issue [here](https://github.com/processing/processing/issues/3363), which has now been fixed (although this was after the 3.0a10 release, I think, which means that the next release won't have this issue). Could you please check if this issue occurs in the current build?

**Comment by benfry** [comment] 2015-07-14 12:57
Duplicate of #3363, #3315, #3316, or #3303. Fixed for the next release.

**Closed by benfry** 2015-07-14 12:57 UTC
