### ISSUE TITLE
Menu Refresh Problem

### ISSUE THREAD

**Issue by Force098** [processing/processing#4768] opened 2016-12-11 01:15 UTC
Using the menus causes the application to re-draw areas incorrectly. The entire application has to be closed and re-opened to work. 

Running Windows 10 64bit
![image](https://cloud.githubusercontent.com/assets/24500661/21077304/9db43554-bf04-11e6-8f2d-f078b58310ce.png)

**Comment by Zbarley** [comment] 2016-12-11 12:54
Same here

**Comment by benfry** [comment] 2016-12-11 14:02
Duplicate of https://github.com/processing/processing/issues/4700

**Closed by benfry** 2016-12-11 14:02 UTC
