### ISSUE TITLE
NoClassDefError: processing/core/PApplet on startup with Windows 10

### ISSUE THREAD

**Issue by SR--** [processing/processing#5495] opened 2018-05-01 06:23 UTC
![image](https://user-images.githubusercontent.com/1008059/39463538-dded7f90-4d5b-11e8-9982-2162cf924095.png)

**Comment by gohai** [comment] 2018-05-06 18:11
@SR-- Could you try re-download the ZIP file, and uncompressing it entirely into a folder before executing Processing.

**Comment by ganeshmuni** [comment] 2018-05-11 14:59
tried but didn't work

**Comment by benfry** [comment] 2018-07-19 13:55
Perhaps this issue? https://github.com/processing/processing/issues/5537

**Comment by benfry** [comment] 2018-07-19 22:57
Closing as duplicate of #5537.

**Closed by benfry** 2018-07-19 22:57 UTC
