### ISSUE TITLE
add option for tab/indent length

### ISSUE THREAD

**Issue by YoshiRulz** [processing/processing#4600] opened 2016-08-03 01:24 UTC
Some people just like to have more spaces.
Secondary request: use 'hard' tabs instead of spaces.

**Comment by alignedleft** [comment] 2016-08-03 02:14
I, too, prefer tabs (about 5 spaces' worth is right for me), but I suspect you'll be told to use Eclipse if you want that level of customization with your dev environment. The Processing IDE is meant to be simple, focused, and addressing beginners first and foremost.

**Comment by benfry** [comment] 2016-08-04 15:10
For the time being, you can modify `preferences.txt` by hand and modify this line:
```
editor.tabs.size = 2
```

**Comment by LoganDark** [comment] 2021-07-18 00:21
It's been almost five years and this is still sitting unresolved. Is adding two toggles really that big of a deal? I'm trying to understand why configuring how your code looks should not be an option in Processing. I know many beginners who prefer to use 4-wide tabs, because it makes it easier to read. I also prefer to use hard tabs. Supporting these use cases will not compromise any existing functionality, so why not?

**Comment by scotthmurray** [comment] 2021-07-19 00:22
@LoganDark I just logged in to reply to this… only to discover that I already replied to this issue, um, 5 years ago. 😀

I second what I wrote above, which is that: While I, too, prefer tabs (yay, tabs rule! spaces drool!), the Processing IDE is intended for *beginners* who are just learning to code for the first time. This is an essential and very important goal of the IDE — to minimize the amount of confusion that can be introduced (and, in programming, there is already plenty to be confused about!).

The Processing IDE is definitively *not* going to reproduce features from Sublime, Atom, Eclipse, and other full-featured IDEs. Doing so would go against the mission of the software and the Foundation. (I do not represent either the software or the Foundation, though I ♥️ them.)

Thus, we are stuck with 2 space indents, whether or not that suits our personal preference. If you want something else, you can use another IDE.

…That said, there used to be documentation on how to use Processing with Eclipse, but now I can't find it. [The FAQ page](https://github.com/processing/processing/wiki/FAQ) links to a tutorial and a forum thread, but both links are now broken. @benfry if there are new or current Eclipse instructions, I'd propose updating links to those, then closing this issue. (That is... unless you really want to humor us tabs people.) 😉

**Comment by LoganDark** [comment] 2021-07-19 00:33
> The Processing IDE is definitively not going to reproduce features from Sublime, Atom, Eclipse, and other full-featured IDEs. Doing so would go against the mission of the software and the Foundation.

So features are going to be denied simply because they exist in other products? The ability to set your tab width in the preferences menu? Surely a beginner must understand what tab width is. I do believe there is a difference between "simplicity and beginner-friendliness", and "lack of features".

> (I do not represent either the software or the Foundation, though I ♥️ them.)

Your posts are written very authoritatively, as if you _were_ a representative of the Foundation and/or the software. Additionally you are a member of the `processing` organization, so I'm really not sure what to believe here. I'm just going to assume that you have some power, going by the tone of your posts.

> Thus, we are stuck with 2 space indents, whether or not that suits our personal preference. If you want something else, you can use another IDE.

I don't have to, I was able to configure Processing just fine. I have 4-wide hard tabs. You can see my post for the preference options that set that.

> …That said, there used to be documentation on how to use Processing with Eclipse, but now I can't find it. The FAQ page links to a tutorial and a forum thread, but both links are now broken. @benfry if there are new or current Eclipse instructions, I'd propose updating links to those, then closing this issue. (That is... unless you really want to humor us tabs people.) 😉

Eclipse is an absolutely terrible IDE and I would not use it even if I were stuck in 1998 which is where that IDE belongs. The actual way to use Processing from outside the Processing application is simply to include processing-core.jar, and create a subclass of PApplet, which will be your sketch. Implement your desired functions there, and then that PApplet has a `main` method that you can call to run the program. I have done this. I have used Kotlin with Processing. It works fairly well, even with coroutines and other fun things.

**Comment by benfry** [comment] 2022-08-04 19:30
The Preferences window is already overwhelming, and this is a feature that would be used by an extremely small number of users, so we have to make the call that it's not worth making part of the available options in that window.

These aren't easy decisions, lots of people disagree on any number of them, but I always try to make things *possible* for people who feel strongly about it.

So as mentioned above, the solution is to open your `preferences.txt` file (which is also noted at the bottom of the Preferences window, and set the tab size via `editor.tabs.size = 4`.

If someone has a good idea for where that should be documented, please file an issue in https://github.com/processing/processing-docs or https://github.com/processing/processing-website

**Closed by benfry** 2022-08-04 19:30 UTC
Labels: enhancement
