### ISSUE TITLE
Processing interface icons very small on high resolution screen in Windows 8.1

### ISSUE THREAD

**Issue by sujithvakathanam** [processing/processing#3126] opened 2015-02-24 21:42 UTC
The various icons and buttons in the Processing Application(Visualisation application) interface are very, very small on a laptop with a 3200x1800px screen. The icons are difficult to see unless my nose is a few cm from the screen.

I've played around with adjusting the screen resolution and other settings in the operating system (Windows 8.1), which helps, but results in other applications appearing too large, and even then the Processing icons are uncomfortably small.

Is there any easy way to force larger icons? I also tried Compatibility view=>Disabled display Scaling on high DPI Still it does not work. Any help would be appreicated??

**Comment by benfry** [comment] 2015-02-25 14:44
Duplicate of https://github.com/processing/processing/issues/2411

**Closed by benfry** 2015-02-25 14:44 UTC
