### ISSUE TITLE
OpenJDK support

### ISSUE THREAD

**Issue by valerio-bozzolan** [processing/processing#4415] opened 2016-04-19 12:35 UTC
(First of all, thanks to this awesome community!)

Trust me, I know that OpenJDK has strange behaviors, but think about avoiding Oracle's JRE for future versions of Processing. 

Installing third-party software (or worse non-free as in freedom software) it's something normal for Microsoft Windows and OS X users, but this is a nasty thing for GNU/Linux distributions built over complex dependencies systems, with a wide web of already trusted and packaged software.

Mark this bug as `enhancement` if you want, but please don't close it. Processing, and Processing users, really deserves to be not forced to use Oracle's software.

**Comment by DigitalPublishingToolkit** [comment] 2016-04-19 16:20
I'd also be interested in OpenJDK support on Linux. I'd be volunteering to help triage any Linux bugs that might be caused by using OpenJDK - but as far as I understand, the difference between Oracle's Java and OpenJDK isn't that substantial (anymore).

**Comment by gohai** [comment] 2016-04-19 16:21
I'd also be interested in OpenJDK support on Linux. I'd be volunteering to help triage any Linux bugs that might be caused by using OpenJDK - but as far as I understand, the difference between Oracle's Java and OpenJDK isn't that substantial (anymore).

**Comment by monkstone** [comment] 2016-04-20 06:34
Just a comment really but JRubyArt (a port of processing-3.0.2) to ruby works absolutely fine with openjdk (including javafx since 1.8.0_77). There may still be advantages to Oracle java however  the javafx bug ahead of openjdk for example.

**Comment by neilcsmith-net** [comment] 2016-04-21 09:45
+1 to this. Differences between OpenJDK and Oracle Java are minimal, and Oracle's Java build is based on the OpenJDK source - they develop in the OpenJDK tree.  OpenJDK is also the Java reference build, so _theoretically_ if there's a difference in behaviour it's a bug in Oracle's version :smile:

I'd love to see Processing fully open (as distributed).  There are also certified OpenJDK builds for Windows and OSX by Azul (although not with OpenJFX). http://www.azul.com/downloads/zulu/

**Comment by guoyunhe** [comment] 2016-09-28 09:42
+1

Another reason is that how Linux package software. If the software wants to included in Debian/Ubuntu/Fedora/openSUSE/Arch/Gentoo Linux, it has to provide a source tarball that can be compiled independently, without downloading non-free binaries from a commercial company, like Orcale.

**Comment by monkstone** [comment] 2016-09-28 10:05
Actually Archlinux via community repository already provides https://www.archlinux.org/packages/community/i686/processing/ with Hotspot VM included (ie as supplied by processing.org). Debian on the other hand are very sniffy as a consequence packages such ruby, jruby and even java can be hopelessly out of date.

**Comment by gohai** [comment] 2016-09-28 11:07
There's a change already in git master (not yet in a released version, but it should be in the next one), that allows Processing to work with an unmodified JRE out of the box. This doesn't do anything for OpenJDK support per se, but now it is at least possible for distributors to have Processing work together with a standalone Java package without jumping through hoops.

**Comment by neilcsmith-net** [comment] 2016-09-28 11:18
@monkstone pity the licensing information in that Arch package is incorrect then! :smile: In fact, I wasn't aware that Arch allowed commercially licensed software in community packages, but maybe I'm wrong there?  Oh, and Debian OpenJDK should always be in sync with latest releases, because they're treated as security updates.

@guoyunhe I'd like to see this from a let's make Processing truly open-source point of view, even if still a completely self-contained download.  Packaging like standard Ubuntu / Debian packages if it forces dependency on other versions of JOGL, JNA, etc. is likely to go badly.

**Comment by gohai** [comment] 2016-09-28 11:46
@neilcsmith-net Agree with your last point. Believe that, in the age of `npn` and `pip`, it's pretty clear to everyone that all too strict policies when it comes to packaging and de-duplication aren't really what's working for users and developers.

**Comment by neilcsmith-net** [comment] 2016-09-28 11:51
@gohai yes, Snappy might be a more interesting packaging mechanism for Processing? http://snapcraft.io/

**Comment by gohai** [comment] 2016-09-28 12:34
@neilcsmith-net I meant that not against packaging Processing as distribution packages, but rather against the notion that it couldn't bundle _any_ components it requires. Because supporting this would just be insane. And it seems distributions too are warming up to the idea of the self-contained application that can come with its (tested & proven) libraries: see e.g. [Flatpack](http://flatpak.org/).

Thinking some simple package hierarchy, that doesn't impact actual development in a negative way could make sense: e.g. a package `processing-java-core` (just the `core` library plus JOGL, depending on some installed Java 8), and a package `processing` (basically the rest minus the bundled JRE, depending on the former).

**Comment by neilcsmith-net** [comment] 2016-09-28 13:40
@gohai see eg. Flatpak, Snappy! :smile: I think we're pretty much saying the same thing, and it wouldn't be Linux if there weren't at least two options to have a needless fight over. In fact, they're just the new kids on the block - I remember using some Autopackage distributed stuff over 10 years ago.

Your simple package hierarchy makes a lot of sense.

Somewhat tangential to this issue, I guess, but a good reason for doing it.

**Comment by xyproto** [comment] 2018-12-28 00:55
The processing package on Arch Linux uses OpenJDK, and it works pretty well.

There is one issue when downloading some extensions with the Contribution Manager (could be related to how HTTP redirects are handled), otherwise it seems to work fine.

**Comment by neilcsmith-net** [comment] 2018-12-28 17:00
Is the contribution manager issue different from #5554 ?

Given there will be no free Oracle Java 8 from the end of next month, and the right to distribute Oracle's JDK from then on is probably uncertain, this OpenJDK move could do with happening quite quickly!  AdoptOpenJDK 8 would be the obvious replacement at the moment.

No differences between free Oracle Java and OpenJDK going forward either! :smile:  Well, except in duration of free support, which will only be 6 months from Oracle.

**Comment by xyproto** [comment] 2018-12-28 19:53
Yes, the issue is very similar to #5554. I think it's the same problem.

**Comment by malan88** [comment] 2019-01-06 03:31
I've been trying to install Processing for the past few days now (I keep finding `Pillow` for Python [my preferred language] to produce rather ugly effects [no real antialiasing]) but every time I install it and try to launch it I get the error

```
[Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp                                                                               
-Djava.ext.dirs=/usr/share/processing/java/lib/ext is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.]`
```

I'm installing it in Arch via `sudo pacman -S processing`. Not sure what the heck that error is. But since I get this message when installing it:

```
---[ NOTE ]---------------------------------------------------------------
Processing does not really support OpenJDK, only Java from Sun and Oracle.
https://github.com/processing/processing/wiki/Supported-Platforms#linux
If you counter any issues with this package, please file bug reports with 
Processing and/or OpenJDK until Processing can officially support OpenJDK.
--------------------------------------------------------------------------
```

I decided to try it with the JDK8 from the AUR. It failed that way too.

I'd really like to try it. But @xyproto 's comment
>The processing package on Arch Linux uses OpenJDK, and it works pretty well.

Seems not to be the case for me.

**Comment by monkstone** [comment] 2019-01-06 06:39
@malan88 what I expect is happening for you is that Archlinux by default now installs jdk11, and the processing launch script doesn't play too well with jdk11. You need to install jdk8, and make that the default java/jdk, which on Archlinux you can easliy do using `archlinux-java`.

**Comment by xyproto** [comment] 2019-01-06 22:01
I updated the Arch Linux `processing` package to use OpenJDK 8, since it did not work with OpenJDK 10 or OpenJDK 11 here, but seems to work fine with OpenJDK 8.

**Comment by malan88** [comment] 2019-01-07 13:04
@monkstone Thank you. It worked. I am unsure why trying the JDK8 from the AUR didn't work. I am suspicious that I didn't _install_ the JDK8 (installing the JDK11 instead). I cannot remember. It works anyway, and I appreciate it.

Thank you, @xyproto for updating the Arch package: it makes far more sense to have it require OJDK8.

**Comment by trummerschlunk** [comment] 2019-10-04 12:11
> @malan88 what I expect is happening for you is that Archlinux by default now installs jdk11, and the processing launch script doesn't play too well with jdk11. You need to install jdk8, and make that the default java/jdk, which on Archlinux you can easily do using `archlinux-java` (_PS: I have seen the same error as you with jdk11_).
> See https://wiki.archlinux.org/index.php/java. My [ruby versions of processing](https://github.com/ruby-processing), work just fine (_if somewhat noisly_) with jdk11, so I suspect vanilla processing might work with an amended launch script `/usr/bin/processing`.

Thanks. I set default java to jdk8 using archlinux-java, but processing will still not look in the right folder for it, I guess... (missing /jre in the end) Any ideas? Here is the processing console error when I run a sketch:

_Exception in thread "Thread-9" java.lang.RuntimeException: Exception while attempting /usr/lib/jvm/java-8-openjdk/bin/java -agentlib:jdwp=transport=dt_socket,address=8850,server=y,suspend=y,quiet=y -Djna.nosys=true -Djava.ext.dirs=/usr/lib/jvm/java-8-openjdk/lib/ext -Djava.library.path=:/usr/share/processing/core/library:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -cp /tmp/sketch_191004a1977660392377741231temp:/usr/share/processing/core/library/gluegen-rt-natives-linux-amd64.jar:/usr/share/processing/core/library/gluegen-rt-natives-windows-amd64.jar:/usr/share/processing/core/library/gluegen-rt.jar:/usr/share/processing/core/library/jogl-all-natives-linux-armv6hf.jar:/usr/share/processing/core/library/jogl-all-natives-windows-amd64.jar:/usr/share/processing/core/library/gluegen-rt-natives-windows-i586.jar:/usr/share/processing/core/library/jogl-all.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-i586.jar:/usr/share/processing/core/library/core.jar:/usr/share/processing/core/library/jogl-all-natives-linux-i586.jar:/usr/share/processing/core/library/jogl-all-natives-linux-aarch64.jar:/usr/share/processing/core/library/gluegen-rt-natives-macosx-universal.jar:/usr/share/processing/core/library/jogl-all-natives-linux-amd64.jar:/usr/share/processing/core/library/jogl-all-natives-windows-i586.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-armv6hf.jar:/usr/share/processing/core/library/jogl-all-natives-macosx-universal.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-aarch64.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:/usr/share/processing/lib/ant-launcher.jar:/usr/share/processing/lib/ant.jar:/usr/share/processing/lib/jna-platform.jar:/usr/share/processing/lib/jna.jar:/usr/share/processing/lib/pde.jar:/usr/share/processing/core/library/core.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-aarch64.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-amd64.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-armv6hf.jar:/usr/share/processing/core/library/gluegen-rt-natives-linux-i586.jar:/usr/share/processing/core/library/gluegen-rt-natives-macosx-universal.jar:/usr/share/processing/core/library/gluegen-rt-natives-windows-amd64.jar:/usr/share/processing/core/library/gluegen-rt-natives-windows-i586.jar:/usr/share/processing/core/library/gluegen-rt.jar:/usr/share/processing/core/library/jogl-all-natives-linux-aarch64.jar:/usr/share/processing/core/library/jogl-all-natives-linux-amd64.jar:/usr/share/processing/core/library/jogl-all-natives-linux-armv6hf.jar:/usr/share/processing/core/library/jogl-all-natives-linux-i586.jar:/usr/share/processing/core/library/jogl-all-natives-macosx-universal.jar:/usr/share/processing/core/library/jogl-all-natives-windows-amd64.jar:/usr/share/processing/core/library/jogl-all-natives-windows-i586.jar:/usr/share/processing/core/library/jogl-all.jar:/usr/share/processing/modes/java/mode/JavaMode.jar:/usr/share/processing/modes/java/mode/antlr.jar:/usr/share/processing/modes/java/mode/classpath-explorer-1.0.jar:/usr/share/processing/modes/java/mode/com.ibm.icu.jar:/usr/share/processing/modes/java/mode/jdi.jar:/usr/share/processing/modes/java/mode/jdimodel.jar:/usr/share/processing/modes/java/mode/jdtCompilerAdapter.jar:/usr/share/processing/modes/java/mode/jsoup-1.7.1.jar:/usr/share/processing/modes/java/mode/org.eclipse.core.contenttype.jar:/usr/share/processing/modes/java/mode/org.eclipse.core.jobs.jar:/usr/share/processing/modes/java/mode/org.eclipse.core.resources.jar:/usr/share/processing/modes/java/mode/org.eclipse.core.runtime.jar:/usr/share/processing/modes/java/mode/org.eclipse.equinox.common.jar:/usr/share/processing/modes/java/mode/org.eclipse.equinox.preferences.jar:/usr/share/processing/modes/java/mode/org.eclipse.jdt.core.jar:/usr/share/processing/modes/java/mode/org.eclipse.osgi.jar:/usr/share/processing/modes/java/mode/org.eclipse.text.jar:/usr/share/processing/modes/java/mode/org.netbeans.swing.outline.jar -ea processing.core.PApplet --display=1 --sketch-path=/tmp/untitled3074897021926666506sketches/sketch_191004a sketch_191004a
	at processing.core.PApplet.exec(PApplet.java:3563)
	at processing.mode.java.runner.Runner$1.run(Runner.java:498)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk/bin/java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.core.PApplet.exec(PApplet.java:3561)
	... 2 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more_

**Comment by benfry** [comment] 2019-10-04 14:03
Closing this old thread since this isn't a discussion forum; there's work in progress [here](https://github.com/processing/processing/pull/5753) for OpenJDK.

**Closed by benfry** 2019-10-04 14:03 UTC
Labels: enhancement
