### ISSUE TITLE
P2D, P3D, OpenGL Error Making Context Current on Thread

### ISSUE THREAD

**Issue by JediExterm** [processing/processing#2221] opened 2013-11-18 06:32 UTC
Whenever I try running a processing sketch that explicitly lists a renderer in the size function, I encounter an error. Whatever shape I draw within setup properly draws, but  the draw function is never called. This is the error:

```
java.lang.RuntimeException: javax.media.opengl.GLException: Error making context 0x20000 current on Thread AWT-EventQueue-0, drawableWrite 0x300156f0, drawableRead 0x300156f0, werr: 0, WindowsWGLContext [Version 4.2 (Compat profile, arb, ES2 compat, FBO, hardware) - 4.2.11631 Compatibility Profile Context [GL 4.2.0, vendor 0.0.0 (n/a)], options 0xa03, this 0x4858cca9, handle 0x20000, jogamp.opengl.gl4.GL4bcImpl@6d4c4d61,
	 quirks: [NoDoubleBufferedBitmap, NeedCurrCtx4ARBCreateContext],
	Drawable: WindowsOnscreenWGLDrawable[Realized true,
	Factory   jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory@2c6c5356,
	Handle    0x300156f0,
	Surface   JAWT-Window[JAWT version: 0x10004, CA_LAYER: false, isLayeredSurface false, bounds [ 0 / 0  600 x 600 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], shallUseOffscreenLayer false, isOffscreenLayerSurface false, attachedSurfaceLayer 0x0, windowHandle 0x290c3e, surfaceHandle 0x300156f0, bounds [ 0 / 0  600 x 600 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], pos 0/0, size 600x600, visible true, lockedExt false,
	config AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection \Display1, unitID 0, awtDevice D3DGraphicsDevice[screen=1], handle 0x0], idx 1],
	chosen    GLCaps[wgl vid 0xb arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	sun.awt.Win32GraphicsConfig@e4600c0[dev=D3DGraphicsDevice[screen=1],pixfmt=11],
	encapsulated WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[]], idx 1], pfdID 11, ARB-Choosen true,
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[wgl vid 0xb arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]],
	awtComponent AWT-GLCanvas[Realized true,
	jogamp.opengl.windows.wgl.WindowsOnscreenWGLDrawable,
	Factory   jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory@2c6c5356,
	handle    0x300156f0,
	Drawable size 600x600,
	AWT pos 0/0, size 600x600,
	visible true, displayable true,
	AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection \Display1, unitID 0, awtDevice D3DGraphicsDevice[screen=1], handle 0x0], idx 1],
	chosen    GLCaps[wgl vid 0xb arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	sun.awt.Win32GraphicsConfig@e4600c0[dev=D3DGraphicsDevice[screen=1],pixfmt=11],
	encapsulated WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[]], idx 1], pfdID 11, ARB-Choosen true,
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[wgl vid 0xb arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]]],
	surfaceLock <7bd349e2, 6c97d3f0>[count 1, qsz 0, owner <AWT-EventQueue-0>]]]] 
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:100)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:205)
	at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
	at javax.media.opengl.Threading.invoke(Threading.java:191)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:483)
	at processing.opengl.PGL.requestDraw(PGL.java:1149)
	at processing.opengl.PGraphicsOpenGL.requestDraw(PGraphicsOpenGL.java:1604)
	at processing.core.PApplet.run(PApplet.java:2176)
	at java.lang.Thread.run(Thread.java:662)
Caused by: javax.media.opengl.GLException: Error making context 0x20000 current on Thread AWT-EventQueue-0, drawableWrite 0x300156f0, drawableRead 0x300156f0, werr: 0, WindowsWGLContext [Version 4.2 (Compat profile, arb, ES2 compat, FBO, hardware) - 4.2.11631 Compatibility Profile Context [GL 4.2.0, vendor 0.0.0 (n/a)], options 0xa03, this 0x4858cca9, handle 0x20000, jogamp.opengl.gl4.GL4bcImpl@6d4c4d61,
	 quirks: [NoDoubleBufferedBitmap, NeedCurrCtx4ARBCreateContext],
	Drawable: WindowsOnscreenWGLDrawable[Realized true,
	Factory   jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory@2c6c5356,
	Handle    0x300156f0,
	Surface   JAWT-Window[JAWT version: 0x10004, CA_LAYER: false, isLayeredSurface false, bounds [ 0 / 0  600 x 600 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], shallUseOffscreenLayer false, isOffscreenLayerSurface false, attachedSurfaceLayer 0x0, windowHandle 0x290c3e, surfaceHandle 0x300156f0, bounds [ 0 / 0  600 x 600 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], pos 0/0, size 600x600, visible true, lockedExt false,
	config AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection \Display1, unitID 0, awtDevice D3DGraphicsDevice[screen=1], handle 0x0], idx 1],
	chosen    GLCaps[wgl vid 0xb arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	sun.awt.Win32GraphicsConfig@e4600c0[dev=D3DGraphicsDevice[screen=1],pixfmt=11],
	encapsulated WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[]], idx 1], pfdID 11, ARB-Choosen true,
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[wgl vid 0xb arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]],
	awtComponent AWT-GLCanvas[Realized true,
	jogamp.opengl.windows.wgl.WindowsOnscreenWGLDrawable,
	Factory   jogamp.opengl.windows.wgl.WindowsWGLDrawableFactory@2c6c5356,
	handle    0x300156f0,
	Drawable size 600x600,
	AWT pos 0/0, size 600x600,
	visible true, displayable true,
	AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection \Display1, unitID 0, awtDevice D3DGraphicsDevice[screen=1], handle 0x0], idx 1],
	chosen    GLCaps[wgl vid 0xb arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	sun.awt.Win32GraphicsConfig@e4600c0[dev=D3DGraphicsDevice[screen=1],pixfmt=11],
	encapsulated WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[]], idx 1], pfdID 11, ARB-Choosen true,
	requested GLCaps[rgba 8/8/8/8, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[wgl vid 0xb arb: rgba 8/8/8/8, trans-rgba 0x0/0/0/0, accum-rgba 0/0/0/0, dp/st/ms 24/8/2, sample-ext default, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]]],
	surfaceLock <7bd349e2, 6c97d3f0>[count 1, qsz 0, owner <AWT-EventQueue-0>]]]] 
	at jogamp.opengl.windows.wgl.WindowsWGLContext.makeCurrentImpl(WindowsWGLContext.java:408)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:712)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:560)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:517)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1020)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:909)
	at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1065)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:666)
	at java.awt.EventQueue.access$400(EventQueue.java:81)
	at java.awt.EventQueue$2.run(EventQueue.java:627)
	at java.awt.EventQueue$2.run(EventQueue.java:625)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:636)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```
I haven't been able to find anything like this listed anywhere, and I'm really puzzled what's going wrong. Any help would be greatly appreciated. In case it matters, the computer in question has a Radeon HD 5780 graphics card.

**Comment by codeanticode** [comment] 2015-06-03 12:49
No updates from original poster and cannot reproduce, closing.

**Closed by codeanticode** 2015-06-03 12:49 UTC
Labels: opengl
