### ISSUE TITLE
blendMode operates differently in P2D vs default renderer

### ISSUE THREAD

**Issue by jsundram** [processing/processing#4376] opened 2016-03-28 04:24 UTC
`blendMode(SUBTRACT)` doesn't render the same results in P2D mode and default render mode. In fact, it looks like no subtraction is happening in the default renderer. Processing 3.0.2, OSX.

**Comment by codeanticode** [comment] 2016-03-30 20:27
@JakubValtar Any comments about this?

**Comment by JakubValtar** [comment] 2016-03-30 20:47
Hm. Could you post any code or screenshots for me, @jsundram? Are other blend modes ok?

**Comment by jsundram** [comment] 2016-04-02 23:00
@JakubValtar , here's code to repro: [jsundram/issue_4376.pyde](https://gist.github.com/jsundram/bc965876c3aba66c56217e3adba10b45)

You can see the results of the different renderers (4 is the blend mode for `SUBTRACT`, see PConstants.java#L260). 

![issue_4376_4xprocessing awt pgraphicsjava2d](https://cloud.githubusercontent.com/assets/150536/14229484/e186efba-f8e9-11e5-8985-66b531079fab.png)

![issue_4376_4xprocessing opengl pgraphics2d](https://cloud.githubusercontent.com/assets/150536/14229502/e8b85170-f8e9-11e5-9870-6332ba815eb9.png)

![issue_4376_4xprocessing opengl pgraphics3d](https://cloud.githubusercontent.com/assets/150536/14229504/ede26d20-f8e9-11e5-9b53-2382b5b746ae.png)

**Comment by jsundram** [comment] 2016-04-02 23:46
@JakubValtar , I wrote [jsundram/render_all_blend_modes.pyde](https://gist.github.com/jsundram/c23575c00bc1b66270d903c055fd3af3) to run through all the blend modes for all of the renderers, and make 3 different graphics, so you can see where they differ. There are a bunch of differences between P2D/P3D and Java2D, although P2D and P3D appear to be the same everywhere (I didn't do any pixel diffing, just eyeballing). Weirdly, the subtract issue that I raised above doesn't show up -- maybe you can look at my code and see why?

![issue_4376_processing awt pgraphicsjava2d](https://cloud.githubusercontent.com/assets/150536/14229775/58011064-f8f2-11e5-93de-140c3da94acc.png)

![issue_4376_processing opengl pgraphics2d](https://cloud.githubusercontent.com/assets/150536/14229776/5dda2318-f8f2-11e5-9004-92e8ff538240.png)

![issue_4376_processing opengl pgraphics3d](https://cloud.githubusercontent.com/assets/150536/14229777/62c9202c-f8f2-11e5-850c-a4aafadf4a6f.png)

**Comment by JakubValtar** [comment] 2016-04-03 02:06
This is a duplicate of #4019, blendMode is basically reset between setup() and draw(). For now, set it in draw() each frame. It should be fixed in #4341, which is waiting to be merged.

**Closed by JakubValtar** 2016-04-03 02:06 UTC

**Comment by JakubValtar** [comment] 2016-04-03 02:19
And btw, thanks for making the comparison. You see differences because DIFFERENCE, HARD_LIGHT, SOFT_LIGHT, OVERLAY, DODGE, and BURN modes are supported only in the default renderer (you are supposed to get an error message when you try to set unsupported mode). I revised and optimised all modes last year and I'm fairly confident they do what they should.
