### ISSUE TITLE
processing issue when trying to open

### ISSUE THREAD

**Issue by goaliegamer1** [processing/processing#4518] opened 2016-06-01 14:19 UTC
![image](https://cloud.githubusercontent.com/assets/19689354/15712946/5979edac-27e2-11e6-9ffe-0bb19f207c4e.png)

**Comment by benfry** [comment] 2016-06-02 20:26
Duplicate of https://github.com/processing/processing/issues/4476

**Closed by benfry** 2016-06-02 20:26 UTC
