### ISSUE TITLE
Application Exports report as "Damaged" on macOS Sierra

### ISSUE THREAD

**Issue by madparker** [processing/processing#4705] opened 2016-10-17 16:21 UTC
There seems to be a serious signing issue when trying to run an exported processing Mac application on computers other than the one it was created. I consistently get this error:

<img width="425" alt="screen shot 2016-10-17 at 12 19 52 pm" src="https://cloud.githubusercontent.com/assets/199709/19445795/cd6353a0-9463-11e6-94be-0903ea302fc5.png">

To reproduce:

1) Open up a new processing sketch (or any processing sketch, really)

2) Go to File>Export Application

3) Select Mac OS X and click export

4) Move the exported application to another Mac OS X machine, running El Capitan

5) Attempt to run application on new machine

**Comment by madparker** [comment] 2016-10-17 16:22
I believe this is a code signing issue, but right clicking and selecting "open" no longer allows it to run.

**Comment by gohai** [comment] 2016-10-18 21:06
@madparker Both machines on El Capitan (10.11)?

**Comment by benfry** [comment] 2016-10-18 22:37
And this is with 3.2.1?

**Comment by madparker** [comment] 2016-10-19 04:27
Yes and Yes.

However, I have an update. It seems to only be a problem when the application is zipped and emailed/drop boxed/google drive/etc. 

When I put it on a thumb drive and bring that to another machine, it works fine. When I zip it, transmit it through whatever means online, then unzip it, it appears as damaged.

Thanks for the quick response, let me know if there are any other questions (and thanks for all the great work on Processing in general).

Matt

**Comment by benfry** [comment] 2016-10-19 23:42
And that's not the case for the same application exported with earlier releases?

**Comment by madparker** [comment] 2016-10-20 01:02
Sorry, turns out the other user I was mailing with was confused and was using Sierra. I apologize for not confirming more throughly before commenting. Seems like you can work around it Sierra, but this seems like a major issue:

http://apple.stackexchange.com/questions/243687/allow-applications-downloaded-from-anywhere-in-macos-sierra

**Comment by benfry** [comment] 2016-10-20 23:30
Ok, that's a huge difference; Apple is kneecapping folks like us with the changes in Sierra. We'll have to figure something out…

**Comment by rwelti** [comment] 2016-11-02 19:01
Glad to see this noted, as I was tearing hair out!! 

I went so far as to join Developer program, so I can sign my own exported apps.

Here's what I learned:

I can confirm:  **binary** transfers such as

-    ftp command line
-    wget / curl
-    scp

**DO** work, because the Finder or whatever hasn't had the chance to inspect them as they are stored.

But via ftp GUI clients like CyberDuck, any browser, or cloud storage - MacOS/Finder intercepts and tags them as insecure (i.e. quarantines them).

The easiest way to _unquarantine_ them and allow them to run is:

> xattr -d -r com.apple.quarantine <target>   # to remove GateKeeper quarantine

But I can't ask my users to do that ,of course, nor require them to use command-line ftp.

Also useful:

> sudo spctl --master-disable  # disable Gatekeeper
> sudo spctl --master-enable
> 

The above will return the options "_Apps from identified developers_" and "_Anywhere_" to the Security preferences.

Finally, there is a download at Apple Dev site called **check-signature**. It is a wrapper around **codesign**, but it ends with a simple "YES" or "NO" as to whether the given file/folder would pass Gatekeeper:

> $ check-signature EQC_v2.app/                                   
> (c) 2014 Apple Inc.  All rights reserved.
> EQC_v2.app/: invalid Info.plist (plist or signature have been modified)
> In architecture: x86_64
> **NO**
> 

A final chuckle: the check-signature utility itself triggered Gatekeeper as being untrusted! haha:
![coreservicesuiagent-1](https://cloud.githubusercontent.com/assets/334205/19943296/04883bec-a0f4-11e6-8411-c3f7a93dd136.jpg)

**Comment by benfry** [comment] 2016-11-03 00:07
Within Processing, we self-sign the application so that you can run it on your own machine without it being reported as damaged. This was already a lot of effort to implement a year or two ago. And before 10.12, that method worked (with a warning to users, and them needing to allow the app) on other machines. 

It looks like we'll have to get into something where people have to install Xcode (yech) in order to use exported applications, and set up an app signing key for themselves (double yech). All around really lousy. It's like… like trying to do serious work on a laptop with no USB ports that match anything I own, no HDMI connector, and no MagSafe for power.

**Comment by rwelti** [comment] 2016-11-03 15:15
I discovered that if you use a shell script to launch the app, the shell script can launch the app successfully -- even though directly launching the app does not work. Interesting.

So I considered using a double clickable shell script called **launch.command** or whatever. (No need to use Terminal, if a shell script ends in .command – you must know that already. )

What about a script in the exported app folder called run-me-1st.command? Inside of it it does the xattr command on the folder... hmmm   Not ideal, but

It sounds maybe better than downloading and installing Xcode, which can take _two hours_ --that's what it took me just yesterday. I was shocked at the incredible slowness of that process. I used to install it at least once a year and it was never such an undertaking. I think watchOS and tvOS might be causing bloat...

**Comment by rwelti** [comment] 2016-11-03 15:17
The **run-me-1rst.command** script would only be need to be run ONCE, I did not make that clear. It isn't a launcher script, it merely performs a single command, the **xattr** command, to unquarantine the .app/ folder.

**Comment by madparker** [comment] 2016-11-03 16:18
Yeah, not ideal, but certainly better than the current situation. Once you have a clickable shell script working, maybe post it here as an example?

**Comment by rwelti** [comment] 2016-11-03 18:27
I certainly will, and I'll point you to a download of my app so you can play with all of it if you like, but first I wanted to say that there may no longer be a need for Ben to self-sign the exported apps at all.

Here is why I'm wondering:
 I found and compiled a program  **unsign**  to remove signatures, from
[https://github.com/steakknife/unsign](url)

First I made sure the exported app was signed (by Ben):
```
$ codesign -dvvv EQC_v2.app/
Executable=/Users/russwelt/Downloads/application.macosx.latest/EQC_v2.app/Contents/MacOS/EQC_v2
Identifier=org.processing.app
Format=app bundle with Mach-O universal (i386 x86_64)
CodeDirectory v=20200 size=338 flags=0x0(none) hashes=5+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=40512ef260f3e0409b982c4e59886952ee567739
CandidateCDHash sha256=11ee6579f4b69181bdb622399c245a7206315375
Hash choices=sha1,sha256
CDHash=11ee6579f4b69181bdb622399c245a7206315375
Signature size=8896
Authority=Developer ID Application: Ben Fry LLC
Authority=Developer ID Certification Authority

```
Then I unsigned my exported app, the actual executable, with:

```
 $ unsign  /Users/russwelt/Downloads/application.macosx.latest/EQC_v2.app/Contents/MacOS/EQC_v2
 reading infile: /Users/russwelt/Downloads/application.macosx.latest/EQC_v2.app/Contents/MacOS/EQC_v2
   processing fat architecture 1 of 2
     found LC_CODE_SIGNATURE
   processing fat architecture 2 of 2
     found LC_CODE_SIGNATURE
 wrote outfile: /Users/russwelt/Downloads/application.macosx.latest/EQC_v2.app/Contents/MacOS/EQC_v2.unsigned

```

Then I renamed the unsigned version above to be the actual one, down in the MacOS/ dir:

`$ mv EQC_v2.unsigned EQC_v2 
`

Now it seems to be unsigned alright:

```
$ codesign -dvvv EQC_v2.app/   
EQC_v2.app/: code object is not signed at all

```
Then I tested that it still ran for me on my own machine where all this took place, and it did.

So I zipped the whole thing up and ftp'd it to my other Mac, and when I double-clicked EQC_v2.app on that Mac I did NOT get the "Move to Trash" dialog, I got the "Unidentified developer" (which can be overridden by right mousing it as we all know)

The point is not that it's possible to "**unsign**" things!  I was simulating the scenario where the exported app _was not signed at all_ at export time from Processing.

So it may, MAY be a case where "less is more".   

Of course the devs will have explored this far deeper than I  have, I'm just a dabbler.

Later I'll post my scripts, I need to sanitize them from stuff that is not related and would confuse folks.

**Comment by rwelti** [comment] 2016-11-03 18:31
To clarify, when I ftp'd it to the other Mac, I used **CyberDuck**, NOT the command line ftp (which already transfers stuff as "unquarantined").  CyberDuck and browser downloads are where stuff gets marked as quarantined, AFAIK.

**Comment by benfry** [comment] 2016-11-03 21:01
Hm, that would be surprising since part of the reason we had to start signing was that applications were reported as damaged.

**Comment by rwelti** [comment] 2016-11-03 22:19
I feel your pain! Too many permutations of OS versions and Security settings and testing scenarios. I've had a headache for 3 days on this.  

You are right to be surprised, I could not duplicate what I just said -- **using a ZIP file**.

However when I use a **disk image** (with the same CyberDuck in both cases) I do indeed get "_unidentified developer_" for the unsigned one.

I made a super simple disk image to show this.  **Link at end.**

There are two export folders, one left alone after export, the other I ran "unsign" on the .app/  .

When I used the (great) DropDMG utility to make a disk image of them, and transferred it that way instead of ZIP, the unsigned app can be launched.

Both xferred with CyberDuck to same testing machine (10.11 Capitan), but the disk image, unsigned app can launch.  Interesting.  ... So Maybe it's 'cuz it's 10.11? 

I will now try same by CyberDucking the DMG file _back_ to the machine I made it on,   **Sierra 10.12.1.**

It still works if it was unsigned and not if it was self-signed.

Here is the untouched, self-signed one:

![banners and alerts](https://cloud.githubusercontent.com/assets/334205/19987117/bcfdaab2-a1d6-11e6-9a4f-18877f64a523.jpg)

```
$ codesign -dvv ArcLengthParametrization_SelfSigned.app/
Executable=/Users/russwelt/Downloads/signingTestAsDownloadedDMG/ArcLengthParametrization_SelfSigned/application.macosx/ArcLengthParametrization_SelfSigned.app/Contents/MacOS/ArcLengthParametrization_SelfSigned
Identifier=org.processing.app
Format=app bundle with Mach-O universal (i386 x86_64)
CodeDirectory v=20200 size=242 flags=0x0(none) hashes=5+3 location=embedded
Signature size=8543
Authority=Developer ID Application: Ben Fry LLC
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Oct 23, 2015 j=296, 2:04:56 PM
Info.plist=not bound
TeamIdentifier=8SBRM6J77J
Sealed Resources=none
Internal requirements count=1 size=180

```


And now the **unsigned** one:

![banners and alerts-1](https://cloud.githubusercontent.com/assets/334205/19987152/e47a5e1e-a1d6-11e6-94c9-113ba7314235.jpg)

```
$ codesign -dvv ArcLengthParametrization_UnSigned.app/
ArcLengthParametrization_UnSigned.app/: code object is not signed at all

```

Sharp eyes will notice the words "disk image" in the dialog above.
I realized I launched it from the mounted image by mistake.
But same behavior after dragging to a local folder.

Here is a link to the above code. 

[ftp://ftp.iris.washington.edu/pub/pickup/signingTest.dmg](url)

I sincerely hope this is helpful, I'm not trying to muddy the water or contradict your guys' experience, in the past or present.

**Comment by rwelti** [comment] 2016-11-03 22:23
I would be curious to know if you experience the same behavior as I showed above, if you get time to download it.

**Comment by rwelti** [comment] 2016-11-03 22:35
It occurred to me to search for other signed items in my "unsigned" app folder.

I did find a few files still signed, Oracle-related, obviously not preventing app from running:

```
$ find .  -exec codesign -dvv {} \; 2>&1 | grep ^Identifier=
Identifier=com.oracle.java.8u51.jdk
Identifier=net.java.openjdk.cmd
Identifier=net.java.openjdk.cmd
Identifier=net.java.openjdk.cmd
Identifier=com.oracle.java.8u51.jdk

```

the self-signed, untouched one, for comparison:

```
$ find .  -exec codesign -dvv {} \; 2>&1 | grep ^Identifier=
Identifier=org.processing.app
Identifier=org.processing.app
Identifier=com.oracle.java.8u51.jdk
Identifier=net.java.openjdk.cmd
Identifier=net.java.openjdk.cmd
Identifier=net.java.openjdk.cmd
Identifier=com.oracle.java.8u51.jdk

```

**Comment by rwelti** [comment] 2016-11-03 23:04
@madparker 
I have written a lot today so for now, here is a link to a description with actual code that I made of the "scripted launch" workaround to "damaged" apps. It's brittle and not a solution but interesting perhaps. It has one advantage: console output is logged to a file.

[ftp://ftp.iris.washington.edu/pub/pickup/launchProcAppViaScript.txt](url)

**Comment by benfry** [comment] 2016-11-04 00:36
Really appreciate you taking the time to look into this. 

Other tidbits that might be useful:
* The embedded Java and the app itself need to be signed in separate steps (see `build.xml` for how Processing.app is handled, or `JavaBuild` for how it's done for exported apps)
* Disk images have another layer of messiness in Sierra. I don't know all the details, but there's additional changes to randomize where app code is located that's giving headaches to a lot of developers.
* There's a decent chance that a double-clickable `remove-xattr.tool` or `remove-xattr.command` will itself need xattr's removed once shuttled around this way. (However, I haven't had time to dig through your whole thread here, so there might be things I'm missing.)

Again, thanks for the help. You're getting a window into the many, many hours of time that go into the maintenance of keeping this stuff in working condition, let alone adding anything new or fixing actual bugs.

**Comment by StanLepunK** [comment] 2016-12-20 12:13
Add information : 
It's a same result on El Capitan, and maybe Yosemite.
I do a lot versions of my App Romanesco, and now all the zip app receive the message "File Damaged cannot be open.... blah blah" work fine for download last year, and now don't work after download it.
those oldest version is not build with under OS_Sierra, and not downloaded on OS_Sierra. 
This type of problem can be outside from Processing and OS, from Internet Protocole or something like that ?
I try to download an non ziped file with Dropbox. Dropbox make an automatic zip, and when I download  and unzip the file from the link the thumbnail of my app is changed – is not the case when I zip the file by my self.
So my idea is maybe Dropbox or the other carryer change something in the app to stock it on the own server ? 

![capture d ecran 2016-12-20 a 12 55 23](https://cloud.githubusercontent.com/assets/3332269/21350050/90667980-c6b5-11e6-8da9-0e3f73d59a83.png)

**Comment by benfry** [comment] 2016-12-21 14:13
Re-reading [this comment](https://github.com/processing/processing/issues/4705#issuecomment-258291417) makes me think that our larger problem may be that the embedded copy of Java is causing the problem because it still shows as signed by me. Mixed signing states will cause the "damaged" messages. 

So… if there were a standard way to unsign the app using Apple's tools that are installed by default (i.e. codesign), that might be a good fix for Sierra.

**Comment by liasomething** [comment] 2016-12-26 20:59
for me i found two quick "solutions" to get an app to a client (maybe this could be announced on the processing site until the issue is fixed so that people don't freak out like me ...  ;) ?):
a) tell the client to write only xattr -rc myApplicaiont.app in the terminal. 
(this could be explained in an easy read-me file and does not make the clients machine not save in general)
b) use dropbox, put your app there and ask the client to just _sync_ their dropbox folder, but not (!) use the dropbox download link. at least that worked for me (today).

**Comment by benfry** [comment] 2017-05-04 15:26
Thanks to @rwelti's work, I was able to track this down today. So this will be fixed in the next release (3.3.4 or 3.4).

**Closed** 2017-05-05 22:35 UTC
Labels: high, macosx

**Comment by thierry75** [comment] 2017-05-19 08:44
just to let you know i bypassed this issue by unsigning the binary of my exported app using:
https://github.com/steakknife/unsign
then it goes back to "unknown" in place of damaged and allow right click open trick to open it...

**Comment by philipp-lehmann** [comment] 2021-04-30 07:58
I bypassed it with xattr
https://github.com/processing/processing/issues/4214#issuecomment-829916359

**Comment by benfry** [comment] 2021-06-14 20:38
Locking this issue because it's become a catch-all for unrelated issues with the same error message. If you have signing errors, please file a new issue. The issue here was fixed in May 2017.
