### ISSUE TITLE
PRocessing 3.1 with Sublim Text

### ISSUE THREAD

**Issue by StanLepunK** [processing/processing#4461] opened 2016-05-10 13:08 UTC
Processing 3.1 does not work Sublim text.
I reinstall java Processing as usual but now Sublim Text return this message : 
````
Exception in thread "main" java.lang.NullPointerException
	at processing.mode.java.Commander.<init>(Commander.java:263)
	at processing.mode.java.Commander.main(Commander.java:86)
[Finished in 2.3s with exit code 1]
[cmd: ['processing-java', '--force', '--sketch=/Users/stanislasmarcais/Desktop/CODE/PROCESSING/BUG PROCESSING/Processing 3.1/SublimText', '--run']]
[dir: /Users/stanislasmarcais/Desktop/CODE/PROCESSING/BUG PROCESSING/Processing 3.1/SublimText]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
````

I try to change the place of ProcessingJava but the result is the same.

I post this message on SublimText Processing too
![bug_sublimtext](https://cloud.githubusercontent.com/assets/3332269/15147437/f970437a-16c0-11e6-8878-0544a1f643b9.jpg)

**Comment by JakubValtar** [comment] 2016-05-10 13:43
Thanks for the report, it's already fixed for 3.1.1, duplicate of https://github.com/processing/processing/issues/4452

**Closed** 2016-05-10 13:43 UTC
Labels: duplicate
