### ISSUE TITLE
Menu bar visible in full screen on a mac

### ISSUE THREAD

**Issue by Euphorbium** [processing/processing#4812] opened 2017-01-05 21:23 UTC
This seems like a known problem, which has been solved a while [ago](https://github.com/kritzikratzi/fullscreen-p5), but a lot of time has passed, and it would be really nice if this was solved again.

**Comment by benfry** [comment] 2017-01-06 15:10
The `fullScreen()` function should be working fine, [except perhaps](https://github.com/processing/processing/issues/4527) when using `FX2D`. Please post some code or some background on what you're doing that is causing the problem.

**Comment by GKFX** [comment] 2017-01-09 12:01
I get the same problem on Linux (Debian, Gnome), for the default renderer only. `FX2D`, `P2D`, and `P3D` work fine.
![screenshot from 2017-01-09 11-30-28](https://cloud.githubusercontent.com/assets/5357642/21765223/628ba7ba-d65f-11e6-9df6-448f28ae6aeb.png)
Code is just
````java
void setup() {
  fullScreen();
}

void draw() {
  background(0);
  ellipse(frameCount % width, frameCount % height, 120, 120); 
}
````
I obviously don't know if this is caused by the same or a different issue as on Mac.

**Comment by benfry** [comment] 2017-05-04 02:42
@GKFX That's your window manager and how it interacts with Java2D. Out of our control, unfortunately, which is part of why FX2D (and the others) are available. 

Closing since there hasn't been any followup on the original issue.

**Closed by benfry** 2017-05-04 02:42 UTC
