### ISSUE TITLE
UI Problems

### ISSUE THREAD

**Issue by DeltaZero** [processing/processing#4874] opened 2017-02-02 07:59 UTC
![image](https://cloud.githubusercontent.com/assets/11534729/22541274/5f95907a-e960-11e6-8455-cf7d0b8ea0ce.png)

I'm not really sure what's happening here, but the UI is messed up. When I startup Processing, I see that window with messed-up text. I ignored it, but once I interact with some elements in the main editor, the editor will bug out and show a white screen, then eventually crashes.

**Comment by n1ckfg** [comment] 2017-02-02 17:02
Me too. Win10 Home. Happened suddenly (without restart) and affects both 3.2.3 and 3.2.4. Clean and reinstall does not help.

**Comment by benfry** [comment] 2017-02-03 14:58
Duplicate of https://github.com/processing/processing/issues/4747

**Closed by benfry** 2017-02-03 14:58 UTC
