### ISSUE TITLE
Unicode char doesn't display when textSize(); is called

### ISSUE THREAD

**Issue by bombnuc77** [processing/processing#5130] opened 2017-06-14 17:09 UTC
In this code, we write a unicode char (here the katakana char "ゥ")
<code>void setup(){
    text(getCharFromUni("30A5"), 10, 10);
}

String getCharFromUni(String uni){
  int n = unhex(uni);
  String sh = new String(Character.toChars(n));
  return sh;
}<code/>
It works but if we just want to resize the text with the "textSize()" command (with any value),
<code>void setup(){
    textSize(20);
    text(getCharFromUni("30A5"), 10, 10);
}

String getCharFromUni(String uni){
  int n = unhex(uni);
  String sh = new String(Character.toChars(n));
  return sh;
}<code/>
it prints the "ࡠ" char on the screen.

**Comment by tolkanabroski** [comment] 2017-06-14 19:51
Not an fully explanation
I think becouse the defaultFont in Processing has Unicode but a fixed size 12ppt and when you request a scaled version the (new)Font has no Katakana Unicode.

A workaround
+ Open Processing 
+ go under Create Font search for a font that supports katakana
+ MS-Gothic  
  

```java
//https://processing.org/reference/PFont.html
PFont font;

void setup(){
  //localy you can use loadFont, becourse i share this example online per download i use createFont
  //font = loadFont("MS-Gothic-48.vlw");
  font = createFont("https:"+"//drive.google.com/uc?export=download&id=0BwTQLXGKzDbZUmFkdEl0RW9IX2c",48);
  
}

void draw(){
background(127);
textFont(font, 12+frameCount*.1f);
text(getCharFromUni("30A5"), 10, 50);
}

String getCharFromUni(String uni) { 
  int n = unhex(uni); 
  String sh = new String(Character.toChars(n)); 
  return sh;
}
```
> //output
![](https://gifyu.com/images/katakana.gif)

**Comment by benfry** [comment] 2017-06-14 20:11
Duplicate of https://github.com/processing/processing/issues/4956

**Closed by benfry** 2017-06-14 20:11 UTC

**Comment by javierfilgueira** [comment] 2019-12-27 22:56
Buenas.. yo utilizando el font =  Bank Gothic Medium BT
utilize la funcion getCharFromUni(); que indicaron pero aun asi seguia apareciendo la ventanita..
luego verifique buscando en la fuente si existia el caracter que necesitaba y encontre que estaba llamandolo mal.
Para mi caso que necesitaba el superindice 3
getCharFromUni("B3") osea el 0xB3
Saludos a todos!
