### ISSUE TITLE
adding username and password to proxy settings?

### ISSUE THREAD

**Issue by SayalHajare** [processing/processing#5835] opened 2019-04-06 07:12 UTC
I am behind a proxy server that requires an username and a password, however, all the solutions are regarding setting host and port, which did nothing for me, as mine requires an authentication, and I get an error 407.

The exact error message:

```
java.io.IOException: Server returned HTTP response code: 407 for URL: http://download.processing.org/contribs
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:103)
	at processing.app.contrib.ContributionListing$1.run(ContributionListing.java:385)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 407 for URL: http://download.processing.org/contribs
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at processing.app.contrib.ContributionManager.download(ContributionManager.java:87)
	... 2 more
 ```

* Processing version: 3.5.3
* Operating System and OS version: Ubuntu 19.04

## Possible Causes / Solutions
any way to add username and password to proxy settings?

**Comment by jeremydouglass** [comment] 2019-05-13 18:10
I think this may be a duplicate of an open enhancement request: https://github.com/processing/processing/issues/5203

**Comment by benfry** [comment] 2019-10-05 13:55
Yes, closing as duplicate.

**Closed by benfry** 2019-10-05 13:55 UTC
