### ISSUE TITLE
Problem when I launch V3.3.7

### ISSUE THREAD

**Issue by AwkweirdMan** [processing/processing#5448] opened 2018-03-21 17:20 UTC
Hello guys I've downloaded processing this morning but I have an error when I launch it. Do you know how to fix it ? Because I will need it really soon for a school project.
![capture d ecran 22](https://user-images.githubusercontent.com/37631818/37725951-752bc59e-2d34-11e8-84bd-886a07d6e20c.png)

**Comment by JakubValtar** [comment] 2018-03-22 17:31
What is the full path of this directory?

**Comment by AwkweirdMan** [comment] 2018-03-24 09:34
![capture d ecran 23](https://user-images.githubusercontent.com/37631818/37862544-e41efae0-2f4e-11e8-815c-141794210ffa.png)

**Comment by JakubValtar** [comment] 2018-03-24 09:44
I mean the file path. Like C:\something\something\processing-3.3.7

**Comment by AwkweirdMan** [comment] 2018-03-24 11:01
Ok, I solved the problem, Windows defender prevent processing to launch, kinda strange, I've tried this yesterday and it wasn't working but it does now so it's good. Thank you !

**Comment by benfry** [comment] 2018-03-24 11:48
Thanks for reporting back. Closing as duplicate of https://github.com/processing/processing/issues/5442

**Closed by benfry** 2018-03-24 11:48 UTC
