### ISSUE TITLE
Cycle through open Processing windows not working for all windows (Mac OS X 13.4)

### ISSUE THREAD

**Issue by ddownn** [processing/processing#5634] opened 2018-08-30 15:12 UTC
## Description
Using keyboard shortcut to cycle through open Processing application windows only switches between the two most recently "active" windows, leaving the others in the background.

## Expected Behavior
With most Mac OS X applications, the keyboard shortcut Cmd + ` will cycle through all open application windows.

## Current Behavior
In Processing, Cmd + ` only switches between two application windows, apparently the last two which have been active. It leaves all other Processing windows in the background.

## Steps to Reproduce
1. Start Processing
2. Create or open three or more Sketches
3. Select any two windows sequentially, then use Cmd + ` to cycle through windows; this only switches between those two windows, leaving all other windows "inactive."

## Your Environment
* Processing version: 3.3.7
* Operating System and OS version: Mac OS X 13.4
* Other information:

**Comment by liquid600pgm** [comment] 2018-08-30 19:06
Possible duplicate of #5473

**Comment by ddownn** [comment] 2018-08-30 20:07
Yes, same issue. Sorry I didn’t find that when I searched to see if it was already reported.

**Comment by benfry** [comment] 2018-09-04 22:11
Closed as duplicate.

**Closed** 2018-09-04 22:11 UTC
Labels: duplicate
