### ISSUE TITLE
Cannot use static methods declared in interfaces

### ISSUE THREAD

**Issue by fukuchi** [processing/processing#6078] opened 2020-07-31 10:07 UTC
#Description
Now Processing uses JRE 1.8 (Java8) and some features newly introduced in Java8 are already available in the latest Processing, but others are not. For example, static methods declared in interfaces are not usable in Processing. Here is an example:

```
import java.util.Comparator;

void setup() {
  ArrayList<String> list = new ArrayList<String>();
  list.add("foo");
  list.add("bar");
  list.add("buz");
  list.sort(Comparator.naturalOrder());
  println(list);
}
```

Reference: [Comparator.naturalOrder()](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#naturalOrder--)

## Expected Behavior

The code above should be compiled and the expected output is "[bar, buz, foo]".

## Current Behavior
I received the following error.

"This static method of interface Comparator can only be accessed as Comparator.naturalOrder"

## Your Environment

* Processing 3.5.4
* Ubuntu 18.04 and Windows 10

## Possible Causes / Solutions

PDE X specifies VERSION_1_6 as JavaCore and Compiler options.

**Comment by benfry** [comment] 2020-08-16 14:31
Duplicate of https://github.com/processing/processing/issues/3054

**Closed by benfry** 2020-08-16 14:31 UTC
