### ISSUE TITLE
Undo sometimes causes the editor to go blank

### ISSUE THREAD

**Issue by REAS** [processing/processing#3003] opened 2014-12-09 19:25 UTC
I have heard reports from a number of my students that Undo is eating code. This is a note to record the potential issue. I need to research further.

**Comment by REAS** [comment] 2015-02-06 21:54
OK, I have finally seen this after continued reports from students. The situation here is that with multiple undos (more than a few) all of the code can disappear from the editor window. Then on the next undo, the code reappeared in its different "undone" state. My guess is that students are panicking when they see the code completely gone and they may not continue to undo to bring it back. So, what might be causing this?

**Comment by benfry** [comment] 2015-03-31 09:42
The issue is probably tied to the idea of “compound edits”... The editor has to be blanked before new code is added, but those two actions have to be bundled together as a compound edit to avoid this situation. 

Where possible, the code should already be doing this, but perhaps we're missing a case.

**Comment by joelmoniz** [comment] 2015-08-21 17:25
I was testing out the undo functionality during the process of easing in the RSTA, and noticed that undo clears everything in the current tab when one does a format. Undoing again adds back the text in its original form. Is it possible that this is one of the cases not bundled as a compound edit, and causing this issue to arise?

**Comment by benfry** [comment] 2015-08-22 13:02
@joelmoniz's patch for the auto-format case is now merged in for 3.0 beta 5. For people who have seen this, do you think this is the likely cause of the issue?

**Comment by shiffman** [comment] 2015-08-22 15:38
Well, the good news is that this has helped my identify the error and reproduce it consistently.  The bad news is that I am still getting it.   Here is a screen capture of "auto-format-undo-code-disappearing" sequence.

https://www.dropbox.com/s/qizua1oyv18cpch/auto_format_error.mov?dl=0

**Comment by joshgiesbrecht** [comment] 2015-08-22 17:55
Were you doing something specific before Auto Format in that video?  I'm trying the same thing here and unable to reproduce the bug.

Steps I've done:
1) Type some code.
2) Select AutoFormat from the Edit menu.
3) Undo

In fact ... in a case where Auto-Format responds that no changes are necessary, the Undo actually undoes the last thing I typed.  ie. the Auto-Format isn't even put on the Undo stack.

**Comment by shiffman** [comment] 2015-08-22 21:30
@joshgiesbrecht My steps:

1. Open new sketch.
2. Type code
3. Auto-format.
4. Undo

I'm running 0243 on Mac OS X 10.10.4.

**Comment by benfry** [comment] 2015-08-23 00:59
And you're definitely running the latest source? I can't reproduce it.

**Comment by shiffman** [comment] 2015-08-23 02:18
Yes, just pulled and tested again. Same result.  No one else seeing this, perhaps something is off on my machine.  Will test from another one tomorrow.

**Comment by joelmoniz** [comment] 2015-08-23 09:56
I've managed to reproduce this on the latest source (in particular, post #3693):

1. Type in something like `void setup() { int x = 20;}` in a single line.
2. Hit `Ctrl+T`

NB: These steps need to be done as quickly as possible in succession
NB2: The text has to be typed in. Copy-pasting doesn't trigger this.

**Comment by benfry** [comment] 2015-08-23 11:43
@joelmoniz can we actually take the `begin/endCompoundEdit()` calls out of auto-format now? I think the problem may have been in not calling `endTextEditHistory()`, since `setText()` already had `begin/endCompoundEdit()` around it.

**Comment by joelmoniz** [comment] 2015-08-23 12:59
Ah, I'd left the calls in an attempt to have the changing caret position is recorded as well, but I'm not sure if I've handled that part correctly.

**Comment by shiffman** [comment] 2015-08-23 13:10
The error is now fixed for me and the actual "auto-formatting" is undone instead of code going blank!

**Comment by benfry** [comment] 2015-08-23 16:37
Wow, shall we close this?

**Comment by shiffman** [comment] 2015-08-23 17:17
I think maybe yes. . and with this bug, I believe we have finally finished everything there is to be done with Processing, see you on the tropical island!

**Comment by benfry** [comment] 2015-08-23 19:52
May as well call it "4.0" and be done with it.

**Closed by benfry** 2015-08-23 19:52 UTC
Labels: help, high
