### ISSUE TITLE
Website Processing.org very slow

### ISSUE THREAD

**Issue by agrignard** [processing/processing#4689] opened 2016-10-03 20:12 UTC
Hi all, 

I know that this issue should not be post here but just to let you know the website processing.org is getting very very slow those last days.

**Comment by alignedleft** [comment] 2016-10-03 22:29
Duplicate of: https://github.com/processing/processing-docs/issues/477

Please post any details you have there! e.g. browser, where you're visiting from, which pages are slow, what you're trying to do…

**Closed by alignedleft** 2016-10-03 22:29 UTC

**Comment by agrignard** [comment] 2016-10-03 22:34
Ok i can see I am not the only one. Well it's a global problem for any page I want to access. But that's ok I was just sure that you get the issue and hopefully it has already been report in processing/processing-docs#477
