### ISSUE TITLE
Transparency problem when using OpenGL-based renderer for PGraphics

### ISSUE THREAD

**Issue by tillnagel** [processing/processing#3447] opened 2015-07-01 13:03 UTC
When creating a PGraphics to draw on, and then displaying that onto the main canvas, transparency seems off for OpenGL-based renderers (P2D, P3D, OPENGL).

I saw #90 and looked through the referenced bug reports, and think this is related but not the same. I tried blendModes, changing mentioned GL-hints, re-ordering the draw calls of the objects, and translating the objects on the z-axis, but all that fails. 

![transparency-bug](https://cloud.githubusercontent.com/assets/908847/8455113/8306c7a0-2002-11e5-8976-fd11f8941574.png)

```java
PImage img;

PGraphics pg;
PGraphics pg3D;

void setup() {
  size(800, 250, P2D);

  img = loadImage("http://globalheat.strava.com/tiles/cycling/color5/13/2415/3081.png");

  pg = createGraphics(255, 255);
  pg.beginDraw();
  pg.clear();
  pg.image(img, 0, 0);
  pg.endDraw();

  pg3D = createGraphics(255, 255, P2D);
  pg3D.beginDraw();
  pg3D.clear();
  pg3D.image(img, 0, 0);
  pg3D.endDraw();
}

void draw() {
  background(90);

  fill(0, 255, 0);
  ellipse(138, 138, 100, 100);
  ellipse(403, 138, 100, 100);
  ellipse(668, 138, 100, 100);

  image(img, 10, 10);
  image(pg, 275, 10);
  image(pg3D, 540, 10);
}
```

**Comment by neilcsmith-net** [comment] 2015-07-01 18:27
Looks like #3391 to me!

**Comment by JukePlz** [comment] 2015-07-09 07:24
Probably a duplicate of #3317 or related to it.

**Comment by JakubValtar** [comment] 2015-08-01 16:30
This is how blending in Processing works right now, because we don't use pre-multiplied colors. You can get around this by drawing the image onto the PGraphics with REPLACE blend mode.
```
  pg3D = createGraphics(255, 255, P2D);
  pg3D.beginDraw();
  pg3D.clear();
  pg3D.blendMode(REPLACE);
  pg3D.image(img, 0, 0);
  pg3D.endDraw();
```
I'll mark this as a duplicate of #3391, which is a feature request to add support for pre-multiplied color model.

**Closed by JakubValtar** 2015-08-01 16:30 UTC
Labels: opengl
