### ISSUE TITLE
A flood of directories in %TEMP%

### ISSUE THREAD

**Issue by chrisjj** [processing/processing#5684] opened 2018-10-16 21:56 UTC
My %TEMP% folder contains tens of thousands of directories apparently created by the Processing IDE - almost as if one is created per run and never deleted.

E.g.

![image](https://user-images.githubusercontent.com/6157073/47053693-04cb2a80-d1a6-11e8-8019-b559fe7b7b68.png)

Processing V3.3.7, Windows 7 64-bit.

**Comment by benfry** [comment] 2018-10-27 14:06
Closing as duplicate of https://github.com/processing/processing/issues/1896

**Closed by benfry** 2018-10-27 14:06 UTC
