### ISSUE TITLE
CTRL + / does not work with international keyboard or / from numeric island

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing#3115] opened 2015-02-20 15:00 UTC
Hey, me again. These students are great at finding problems, it seems!

Class full of Swedish keyboards. ````/```` is under ````SHIFT + 7````. This is a problem, of course, because it requires the key combination of ````CTRL + SHIFT + /````, which won't trigger the short-cut.

Some of my students have a big-ass laptop with a numeric island, with a dedicated ````/```` symbol. This for some mysterious reason also doesn't work.

**Comment by benfry** [comment] 2015-02-21 18:36
Duplicate of https://github.com/processing/processing/issues/2199

**Closed by benfry** 2015-02-21 18:36 UTC

**Comment by JobLeonard** [comment] 2015-02-21 19:43
Sorry for the noise, I forgot to do a search first in my end-of-workweek tiredness.

**Comment by benfry** [comment] 2015-02-21 20:35
No problem!
