### ISSUE TITLE
CM filter input glitchy

### ISSUE THREAD

**Issue by alignedleft** [processing/processing#3612] opened 2015-08-15 04:57 UTC
I'm trying to use the "Filter" box in the CM on, say, the Tools panel, and it gets confused about my keyboard input.

I click "Filter", then a text input cursor appears.  I try to type the letters "tab", but they are transposed as "tba".  Or just "ta" and the "b" is ignored.  Sometimes while I'm typing, the input cursor moves to the left, so letters are input out of order, e.g. "hair" is input as "hari".

**Comment by Akarshit** [comment] 2015-08-15 17:33
@alignedleft I am unable to reproduce this one.

**Comment by alignedleft** [comment] 2015-08-15 17:36
Thanks, @Akarshit. I just retested with the current build and it works fine. Closing.

**Comment by Akarshit** [comment] 2015-08-15 20:31
@alignedleft Please reopen this one, i faced this issue just now.

**Comment by benfry** [comment] 2015-08-16 12:21
Closing with #3630.

**Closed** 2015-08-16 12:21 UTC
