### ISSUE TITLE
Can't reach all tabs when sketch has many tabs

### ISSUE THREAD

**Issue by glasscanvas** [processing/processing#3226] opened 2015-04-27 12:31 UTC
If a sketch has many tabs it is not possible to reach the right most tabs.
If one has a big screen it might be possible but on a smaller screen like an 11"mac laptop even with the window as wide as possible there is no way to get to the remaining tabs. There should be an arrow at the far right. This is true from 2.x through 3.07a.

**Comment by glasscanvas** [comment] 2015-04-28 12:04
Correction. There is a down arrow in Processing 3.05a but not in 3.07a

**Comment by spasmsaps** [comment] 2015-04-28 12:29
duplicate of this closed issue #1968 marked as wontfix.

**Comment by REAS** [comment] 2015-05-02 04:44
Yes, this is a repeat and the referenced issue has a long discussion on the topic. I am going to close this version. To summarize the other thread, Processing isn't meant to be used with that many tabs, but yes, it would be nice for the arrow to be persistent as it is in a web browser. But, we have other priorities, so we aren't going to do it right now. However, someone from the community could take it on.

**Closed by REAS** 2015-05-02 04:44 UTC
