### ISSUE TITLE
why am i getting this msg?

### ISSUE THREAD

**Issue by FrankOcean11** [processing/processing#5858] opened 2019-05-10 00:55 UTC
What does this error implies Processing 3.4?

" No such Gstreamer factory: v4l2src"

**Comment by FrankOcean11** [comment] 2019-05-10 00:59
![57310215-052e0300-70af-11e9-9d3c-fb7531662248](https://user-images.githubusercontent.com/10504709/57495602-f73dd500-729c-11e9-8c63-bf6626ab3e5d.jpg)
![57310523-97cea200-70af-11e9-8eba-dbdbb2ae45a6](https://user-images.githubusercontent.com/10504709/57495603-f73dd500-729c-11e9-9174-013857f41346.jpg)

**Comment by kfrajer** [comment] 2019-05-12 07:41
Hi, please post this error in the [forum](https://discourse.processing.org/)

Have a look at this [post](https://forum.processing.org/one/topic/gsvideo-question.html)

If problem persists, make sure you try one of the examples available from the Processing IDE. Let the Forum know what example they can use to reproduce the problem. Do not forget to mention:
* What is your OS
* Processing version
* Was this working before? Was there a recent change?

**Comment by FrankOcean11** [comment] 2019-05-12 13:08
in what forum ? because i noticed that i read to post here if any issues
and did not mention anything about posting in forums so do you have a link?

**Comment by FrankOcean11** [comment] 2019-05-17 21:53
?

**Comment by kfrajer** [comment] 2019-05-18 05:15
https://discourse.processing.org/
You can click the link in the previous post. You need to hover over "forum"

**Comment by FrankOcean11** [comment] 2019-05-20 02:06
?

**Comment by benfry** [comment] 2019-06-11 17:57
(Closing since this belongs on the forum.)

**Closed by benfry** 2019-06-11 17:57 UTC
