### ISSUE TITLE
Can't find Library folder on startup with macOS

### ISSUE THREAD

**Issue by Siralde** [processing/processing#5857] opened 2019-05-09 22:09 UTC
![Screenshot 2019-05-10 at 00 05 37](https://user-images.githubusercontent.com/24629066/57489782-658f9100-72b7-11e9-8ee4-8790a522f0a8.png)

**Comment by Bobby54** [comment] 2019-05-11 14:45
There might be a problem with your anti-virus Software. Have you  allowed your system to run applications which you have installed from the web?
Or have you moved any of the processing folders or files after the Installation?

**Comment by Siralde** [comment] 2019-05-11 16:29
I have installed and run applications from the web. But I deleted my antivirus software

**Comment by WesleyM77** [comment] 2019-05-13 14:45
Duplicate of #5851.

**Comment by benfry** [comment] 2019-06-11 18:04
That error means that it can't access your “Library” folder in your Home directory. Do you have odd permissions set for it? Antivirus software that might be causing trouble? What version of macOS are you using?

**Comment by benfry** [comment] 2019-10-04 14:14
No response; closing.

**Closed by benfry** 2019-10-04 14:14 UTC
Labels: macosx
