### ISSUE TITLE
" Could not run the sketch (Target VM failed to initialize)" - After updating Windows

### ISSUE THREAD

**Issue by t0mr0bins0n** [processing/processing#4865] opened 2017-01-30 18:01 UTC
Processing has completely stopped working after Windows 10 infuriatingly decided to update itself.
I am using Processing 3.2.4 on the latest release of Windows 10 Pro and this line of text comes up no matter which sketch I try to open:

Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

I know that this is related to Java and after some searching online have seen that others have come across the same problem. Screen size changes and compatibility mode for windows 8 have been suggested on other forums but these have now effect. I am running all the latest drivers for my machine.

Any help would be greatly appreciated, my degree is depending on it!

**Comment by itisltw** [comment] 2017-01-30 18:31
Hi, I have got same problem. It is caused by Nvidia Graphic card driver.
Just go to official website to download previous version

https://github.com/processing/processing/issues/4853

**Comment by benfry** [comment] 2017-01-30 19:39
Closing as duplicate of #4853.

**Closed by benfry** 2017-01-30 19:39 UTC
Labels: duplicate
