### ISSUE TITLE
Installing contributions gives error

### ISSUE THREAD

**Issue by Akarshit** [processing/processing#3445] opened 2015-07-01 07:34 UTC
The stack trace is as follows  
`java.lang.NoClassDefFoundError: processing/app/Editor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at processing.app.contrib.ToolContribution.<init>(ToolContribution.java:62)
	at processing.app.contrib.ToolContribution.load(ToolContribution.java:42)
	at processing.app.contrib.ContributionType.load(ContributionType.java:199)
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:156)
	at processing.app.contrib.ContributionManager$1.run(ContributionManager.java:176)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: processing.app.Editor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more`

**Comment by joelmoniz** [comment] 2015-07-01 07:40
I think that the source if the error might be that the Editor (along with
several other classes) were shifted from processing/app to
processing/app/ui, which means that the imports of all the tools have to be
updated/changed ( there might be an error in ToolContributions file as
well, but I'm definitely sure that the first will cause a problem).

**Comment by Akarshit** [comment] 2015-07-01 07:45
@joelmoniz Yes i guessed that but i opened this so that the people who have moved the stuff will handle this, as it might require some changes.

**Comment by benfry** [comment] 2015-07-03 14:28
Duplicate of https://github.com/processing/processing/issues/3080

**Closed by benfry** 2015-07-03 14:28 UTC
