### ISSUE TITLE
Renaming tabs by only changing case does nothing

### ISSUE THREAD

**Issue by ganercrafter** [processing/processing#5416] opened 2018-02-17 22:33 UTC
For example, I have a tab called game
I click rename, type in Game, and click enter, and nothing happens, it stays the same name
To fix this I have been adding a letter on the end and when I go to change it again I remove the letter and made the g capitalized

**Comment by benfry** [comment] 2018-02-20 00:31
Yeah, sorry, there isn't a good cross-platform way to do this. Under the hood, all we'd be doing is what you've just done manually, which would be more prone to errors, and you wouldn't know what was going on. 

Duplicate of https://github.com/processing/processing/issues/71#issuecomment-13351743

**Closed by benfry** 2018-02-20 00:31 UTC
