### ISSUE TITLE
messy temp directory

### ISSUE THREAD

**Issue by derVedro** [processing/processing#4627] opened 2016-08-18 12:27 UTC
I use my temp directory for any stuff. Any start of a sketch produce 2 new directories with some java sources or classes. It's realy messy. Is there a possibility to define a new temp directory or to put all processing stuff to a separate directory in temp?

**Comment by benfry** [comment] 2016-08-18 13:30
Duplicate of https://github.com/processing/processing/issues/1896

**Closed by benfry** 2016-08-18 13:30 UTC

**Comment by derVedro** [comment] 2016-08-23 05:05
Ok, I found a workaround that helps me. 

It's possible to use _JAVA_OPTIONS environment variable to change the default JVM temp directory. 

`$ _JAVA_OPTIONS="$_JAVA_OPTIONS -Djava.io.tmpdir=/tmp/processing" ./processing`
