### ISSUE TITLE
Immersive Designer PRO software conflicts with Processing(P3D)

### ISSUE THREAD

**Issue by only104** [processing/processing#5464] opened 2018-04-08 07:25 UTC
## Description

I am using Immersive Designer PRO in Company. Immersive Designer PRO software is mapping solution(https://fly.elise-ng.net/) But, This software is conflicts with Processing.

When, P3D Processing is not run.

I got messages " [0x7FFEA13D8160] ANOMALY : meaningless REX prefix used"

But, When I remove Immersive Designer PRO software is Processing work!!

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version: 3.3.7
* Operating System and OS version: Windows 10 pro
* Other information: Nvidia 1070 graphic card

**Comment by gohai** [comment] 2018-04-10 03:33
You might want to try getting in touch with Immersive Designer PRO support, and ask them what the problem is (since Processing works fine without it).

**Comment by benfry** [comment] 2018-04-10 13:47
Closing since this is someone else's product (and out of our control).

**Closed by benfry** 2018-04-10 13:47 UTC
