### ISSUE TITLE
Broken characters in the Welcome Page and the Contribution Manager

### ISSUE THREAD

**Issue by lisandroperalta** [processing/processing#4747] opened 2016-11-19 18:20 UTC
Hi everyone.
When I run Processing the Welcome page shows with broken characters instead of text. Same happens with the contribution manager.
Version 3.1.1 was the last one without this issue, since then every other version I've downloaded (including 3.2.3) presents this problem.
I'm using Windows 10 64bits and I have java v8 upd 101 if its any help. My Languaje is Spanish (Argentina)
Thanks!
I've atttached a screenshot to make myself more clear

![captura de pantalla 2016-11-19 15 10 13](https://cloud.githubusercontent.com/assets/23583735/20457501/9a3980ea-ae6b-11e6-98c9-6017e291beb0.png)

**Comment by Cubit-Games** [comment] 2016-11-20 20:30
Same issue here, really really annoying.

**Comment by jeremydouglass** [comment] 2016-11-20 20:57
@Cubit-Games -- what operating system are you on, what version of Processing are you using, and is your OS configured for a language other than English?

**Comment by Cubit-Games** [comment] 2016-11-21 14:25
I am on Windows 10 and the latest version of processing 3 i downloaded yesterday. My OS is configured for English.

**Comment by benfry** [comment] 2016-11-21 16:28
@gohai could this be a regression from the font loading changes?

**Comment by benfry** [comment] 2016-11-21 16:29
@lisandroperalta Thanks for letting us know about it—we've (obviously) not seen this problem before.

**Comment by gohai** [comment] 2016-11-21 16:36
@lisandroperalta You write that every version after 3.1.1 didn't work for you, is this correct? Asking because we did a change in 3.2.2, which could have been the culprit, but if e.g. 3.2.1 also didn't work, that would rule it out.

**Comment by lisandroperalta** [comment] 2016-11-21 16:45
@gohai  Indeed, I have 3.1.1 running without problems right now, but all the newer versions I've tried presented this issue. (I may have overlooked some, but I'm pretty sure it must be present in everyone)

**Comment by gohai** [comment] 2016-11-21 16:48
@lisandroperalta Thank you for confirming.
@benfry The JRE update in 3.1.2 maybe?

**Comment by benfry** [comment] 2016-11-22 17:18
@gohai good idea…

@lisandroperalta Try the following:
* Make sure Processing is not already running
* Rename the `java` folder in the processing-3.2.3 directory to something else `java2` or `java.bad` or `ihopethisworks`
* Copy the `java` folder from 3.1.1 to the 3.2.3 directory
* Try running the 3.2.3 version of `processing.exe`

Does that fix it?

**Comment by matteolegna** [comment] 2016-11-23 16:12
Same issue here. Where would we find version 3.1.1 to download?

**Comment by gohai** [comment] 2016-11-23 16:32
@matteolegna You find it here: https://github.com/processing/processing/releases/tag/processing-0250-3.1.1

**Comment by matteolegna** [comment] 2016-11-23 16:47
@gohai Thank you very much. I'm not too much used to GitHub.
@benfry Yes! Replacing the Java folder in the way you said makes it work as it should. Thanks!

**Comment by lisandroperalta** [comment] 2016-11-23 20:33
@benfry: the same as @matteolegna , replacing the java folder made it work!
Is it safe to run it like this?

**Comment by benfry** [comment] 2016-11-23 21:59
Yes, safe to run like that. 

Do you have the font “Source Sans” installed on your system? Trying to figure out why this would be causing trouble… Unfortunately it's not our bug, but we need to figure out how to get around it.

**Comment by lisandroperalta** [comment] 2016-11-23 22:31
Checking.... "source sans pro" (!?)
 Is the same?

**Comment by gohai** [comment] 2016-11-24 10:39
@lisandroperalta Not exactly, but that could perhaps explain the issue - could you temporarily delete the Source Sans Pro font from your system and see if this changes things? (You can download the font later [here](https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.020R-ro/1.075R-it).)

Could you also attach a screenshot of the Welcome page (_Help_ > _Welcome..._)? Thanks.

@benfry 
I found this [change](https://bugs.openjdk.java.net/browse/JDK-8146035) to font rendering on Windows that was introduced with 8u102. There's [another one](https://bugs.openjdk.java.net/browse/JDK-8078382) for 8u112, but I believe this only makes a difference for bold & italic. (Both are triggered by a particular font on certain systems fyi.)

**Comment by lisandroperalta** [comment] 2016-11-24 15:32
Hey! As soon as I get to my computer I'll try it. In the meantime, I've tried the following with the computer at work (just in case it is any help)
Windows 7 64  without java installed
Downloaded the 3.2.3 version and deleted the open sans font. 
It works just fine :-P

**Comment by lisandroperalta** [comment] 2016-11-25 00:57
@gohai  Once in my computer tried it. Deleting Source Sans Pro seems to solve it

![captura de pantalla 2016-11-24 21 55 20](https://cloud.githubusercontent.com/assets/23583735/20611865/e04ac6ec-b290-11e6-8535-ac90768bbf29.png)

**Comment by DollarAkshay** [comment] 2016-12-07 21:22
Hey I just downloaded Processing and launched it and had the same problem

### Screenshot :
![Screenshot Processing Bug](https://i.stack.imgur.com/Wa5A8.png)

After deleting Source Sans Pro it is working fine.

### User Details
 - **OS :** Windows 10 64 Bit
 - **Processing Version :** 3.2.3 64-Bit

**Comment by benfry** [comment] 2016-12-09 10:57
For someone having this problem, can you compare the Source Sans file that's included with Processing and the version installed on your system to see if they're identical?

**Comment by InfInt** [comment] 2016-12-10 17:36
I compared both Fonts and they are *not identical* Byte wise. 
![image](https://cloud.githubusercontent.com/assets/833535/21074945/7555acda-bf06-11e6-8412-1ace410e8a13.png)

But Glyph wise they seem to be identical:
![image](https://cloud.githubusercontent.com/assets/833535/21074958/d9233520-bf06-11e6-8b5a-74da47225247.png)
While looking at both versions I found out that their type varies from otf to ttf. However, both are registered as OpenType

**Comment by benfry** [comment] 2016-12-11 14:10
Ouch, I suspected that might be the case… I'm a little concerned that it's using the lookup tables for glyphs and dimensions from the installed version, but the glyph data from the version embedded with Processing (or vice versa).

Do you know where your copy of Source Sans came from? Did you install it? Did another application install it? Could you post it somewhere?

**Comment by InfInt** [comment] 2016-12-14 16:00
I obtained my Version from [Typekit](https://typekit.com/fonts/source-code-pro/) It is tied into my installation of Adobe CC. As far as my knowledge goes, Adobe released that font as open source. At least a paragraph on the Typekit site says so.

**Comment by benfry** [comment] 2016-12-15 14:36
Yeah, the open source version is the one that's included with the software. I suspect that Typekit must be subsetting it in some way (given the drastic size differences in the files) and the differences in the character tables are conflicting with one another.

**Comment by InfInt** [comment] 2016-12-15 14:39
Is there anything I can do to help resolve this bug/issue?

**Comment by gohai** [comment] 2016-12-16 12:23
@benfry Curious whether Processing could ship a modified version of the font using a custom name?

http://superuser.com/questions/120593/how-do-you-change-a-ttf-font-name

**Comment by benfry** [comment] 2016-12-17 14:58
Yeah, that's one possible solution… Not sure if that violates the license, though, and I'd hate to introduce other unintended consequences. 

Could also try reporting the bug to Oracle and see if they—oh, ha! Never mind, not sure what happened to me there.

Since it seems limited to some Windows machines, the best option is to check whether the font is installed and if so, not loading the font from the disk. That's our best option… since Java doesn't actually have a way to test if a font is loaded, you instead try to load the font and then call `getPSName()` to see if it's the expected font. Example:

```
import java.awt.Font;

Font f1 = new Font("Source Sans Pro", Font.PLAIN, 12);
Font f2 = new Font("Source Sans Pro Semibold", Font.PLAIN, 12);

println(f1.getPSName() + " ... " + f2.getPSName());
```
When the font is installed, it'll print `SourceSansPro-Regular ... SourceSansPro-Semibold`. When not installed, it'll print `Dialog.plain ... Dialog.plain`.

So inside a `Base.isWindows()` block, the code should check whether the fonts are installed, and if so, use those `Font` objects and not load them from the .otf files that we supply.

**Comment by benfry** [comment] 2016-12-21 22:22
No takers, so just checked in a fix. 

For anyone having this problem, are you running a version from the source? Or do I need to post a test version to see if it's fixed?

**Comment by DavidPitcher** [comment] 2016-12-26 00:49
I am having the same issue as reported with the Welcome screen.  I did a build with the latest sources and that did not resolve the problem for me.

![image](https://cloud.githubusercontent.com/assets/16139584/21473467/84777bd2-cac1-11e6-8330-a81865485c6a.png)

**Comment by benfry** [comment] 2017-02-12 14:32
Going with the renamed font to fix it for 3.3.

**Closed** 2017-02-12 14:31 UTC
Labels: high

**Comment by benfry** [comment] 2017-02-13 17:49
For anyone who was having this problem, can you please try with 3.3 and report back?

**Comment by lisandroperalta** [comment] 2017-02-13 17:57
Hey!
 just downloaded 3.3 it and it works as it should!
:-)  👍

**Comment by benfry** [comment] 2017-02-13 19:20
Great, thanks for letting me know.
