### ISSUE TITLE
PShape doesn't draw lines containing only 2 vertices

### ISSUE THREAD

**Issue by yblake** [processing/processing#6171] opened 2021-04-06 15:35 UTC
## Description

beginShape(POLYGON) and endShape(OPEN) doesn't draw anything if only 2 vertices are supplied

## Expected Behavior

When 2 vertices are provided, a single line segment should be drawn

## Current Behavior

Actually, nothing is drawn

## Steps to Reproduce

```
void setup() {
  size(500, 500, P2D);
}

void draw() {
  background(0x00);
  noFill();
  stroke(0xFF);
  beginShape();
  vertex(30, 20);
  vertex(85, 20);
  endShape();
}
```

## Your Environment

 

* Processing version: 3.5.4
* Operating System and OS version: Windows 10
* Other information:

**Comment by yblake** [comment] 2021-04-06 16:17
In fact, I found a workaround using `beginShape(LINE_STRIP);`

May be the issue is not the code, but the beginShape() documentation :

- doesn't explain that default type is POLYGON which may need at least tree points (a triangle) ?

- doesn't mention the LINE_STRIP shape type that is working well for polylines !

**Comment by ertdfgcvb** [comment] 2022-02-01 10:10
Duplicate? 
https://github.com/processing/processing/issues/5270

**Comment by benfry** [comment] 2022-02-01 13:18
Yep, closing as duplicate of #5270.

**Closed by benfry** 2022-02-01 13:18 UTC
Labels: opengl, help wanted
